### ISSUE TITLE
concatenate and layers for scEU-seq data

### ISSUE THREAD

**Issue by 117999** [aristoteleo/dynamo-release#110]
When we tried to import the scEU-seq data from the two libraries, labelled and unlabelled, using `anndata.concat()`,
we have encountered some problems reported that `InvalidIndexError: Reindexing only valid with uniquely valued Index objects`.
So, we seek to direct output the merged libraries via using one library as basis and borrowing layers from another, and it goes like this

```
merged=unlablled.copy()
merged.layers['ls']=labelled.layers['spliced']
merged.layers['lu']=labelled.layers['unspliced']
merged.layers['us']=unlabelled.layers['spliced']
merged.layers['uu']=unlabelled.layers['unspliced']
del merged.layers['spliced']
del merged.layers['unspliced']
del merged.layers['matrix']
del merged.layers['ambiguous']
merged.layers['new']=merged.layers['ls']+merged.layers['lu']
merged.layers['total']=merged.layers['ls']+merged.layers['lu']+merged.layers['us']+merged.layers['uu']
del merged.layers['ls']
del merged.layers['lu']
del merged.layers['us']
del merged.layers['uu']
merged
```
but when we examined the merged files with `dyn.pl.basic_stats()`, it reports only the unlabelled data
So, we are wondering an appropriate way to merge the two libraries and import them as dynamo input

**Comment by Xiaojieqiu** [comment]
Hi @117999 thanks for using our tool. Your error mentions that there are either duplicated gene or cell names. please first do something like the following before merging: 

adata.obs_names_make_unique()
adata.var_names_make_unique()

Regarding the code, can you try the following (a minor point for future reference: note that dynamo uses, uu, ul, su, sl)
```
merged=unlablled.copy()
merged.layers['uu']=unlabelled.layers['unspliced'].copy()
merged.layers['ul']=labelled.layers['unspliced'].copy()
merged.layers['su']=unlabelled.layers['spliced'].copy()
merged.layers['sl']=labelled.layers['spliced'].copy()
merged.layers['new']=merged.layers['ul'].copy()+merged.layers['sl'].copy()
merged.layers['total']=merged.layers['new'].copy()+merged.layers['uu'].copy()+merged.layers['su'].copy()
del merged.layers['uu'],  merged.layers['ul'], merged.layers['su'], merged.layers['sl']
del merged.layers['spliced'], merged.layers['unspliced'], merged.layers['matrix'], merged.layers['ambiguous']
merged
```
Let me know how it goes. 

Meanwhile, I am in the process of preparing a few more sophisticated tutorials for our package.  So stay tuned. Lastly, my schedule is more open during the Christmas holiday season, you are welcome to shot me a meeting for a quick 30 minute zoom meeting if you confront future issues.

**Comment by 117999** [comment]
Hi Dr.Qiu@Xiaojieqiu,

Thanks a lot for your kindly reply, your suggestions work well, we can now successfully integrate the two libraries to run dynamo. 

However, when we apply this method to concatenate, the basic plot `dyn.pl.basic_stats()` would only show the dataset that serves as the basis for concatenating. So, I am wondering whether it could be further improved to show the nGene/nCounts/mito% when the two datasets are integrated.

Also, we would be very happy to discuss with you with some additional questions via zoom during Christmas. I will appreciate it a lot if you could give me your zoom account email so that we can add you contact and further discuss about the meeting

**Comment by Xiaojieqiu** [comment]
hi, if you want to plot the statistics for the concentated adata, please make sure no previous run of `dyn.pl.basic_stats()` has done or alternatively, remove the `'nGenes', 'nCounts', 'pMito'` in your concated adata that prodcued from previous `dyn.pl.basic_stats()` run. 

Regarding the zoom meeting, I am happy to offer more bits of help but please make sure the meeting to be about 30 minutes. You can send me the zoom conference invitation to xqiu@wi.mit.edu. Some time (probably between 9 am to 10 pm) scheduled between Dec. 25 to Jan. 2 will work for me. Please note I am currently in Boston (the time Zone is GMT-5).

**Comment by 117999** [comment]
Hi Dr.Qiu,

Sorry for my late response.  And Thanks a lot for sparing your precious time discussing with us about some technique issue with dynamo.

I have already scheduled a zoom meeting on Dec 27th from 9 am to 9:30 am (Boston time), and the meeting invitation has been sent to your mailbox. Will the time be convenient for you? Please let me know if the time does not work for you so that I can pick up another time during Christmas.

Also, my supervisor, Prof. Peng would also like to join our discussion.  Hope we would have a nice and efficient meeting then.
