### ISSUE TITLE
Animate fate transition for PCA plot

### ISSUE THREAD

**Issue by linwang6** [aristoteleo/dynamo-release#112]
Hi Xiaojie,

Thanks for this excellent tool. Is there a way to perform animate fate transition for PCA plot, not UMAP? Please see below, I tried, but it not work for me,

>>> ax = dyn.pl.streamline_plot(adata, color='CellTypes', basis='pca', ax=ax, save_show_or_return='return')
>>> instance = dyn.mv.StreamFuncAnim(adata=adata, basis='pca', color='CellTypes', ax=ax)
        ...........
        raise ValueError('XA and XB must have the same number of columns '
        ValueError: XA and XB must have the same number of columns (i.e. feature dimension.)

Thanks in advance.
Lin

**Comment by Xiaojieqiu** [comment]
Hi @linwang6 thanks for your interest in our work. I will look into more details for this (and may support it natively) (I believe this is because there are more than 2 dimension in the pca basis). However, my quick suggestion is that you can take the first two pca dimension and create a new basis and then operation on that, something like the following: 
```
adata.obsm['X_twoPCs'] = adata.obsm['X_pca'][:, :2]
ax = dyn.pl.streamline_plot(adata, color='CellTypes', basis='twoPCs', ax=ax, save_show_or_return='return')
instance = dyn.mv.StreamFuncAnim(adata=adata, basis='twoPCs', color='CellTypes', ax=ax)

import matplotlib
matplotlib.rcParams['animation.embed_limit'] = 2**128 # Ensure all frames will be embedded.

from matplotlib import animation
import numpy as np

anim = animation.FuncAnimation(instance.fig, instance.update, init_func=instance.init_background,
                               frames=np.arange(100), interval=100, blit=True)
from IPython.core.display import display, HTML
HTML(anim.to_jshtml()) # embedding to jupyter notebook.
```

Let me know how it goes

**Comment by linwang6** [comment]
Hi @Xiaojieqiu , it works! Thanks so much!

**Comment by Xiaojieqiu** [comment]
glad it worked. In fact I will reopen this issue as I would like to enable animating on any two pca components (or actually any two components of any basis if there are more than two). Probably sometime good for me to work on if I got bored during the Christmas or new year

**Comment by linwang6** [comment]
Great. Should rerun dyn.vf.VectorField(adata, basis='twoPCs') after creating the new basis.
