### ISSUE TITLE
error when install this program

### ISSUE THREAD

**Issue by Golden-proteogenomics** [aristoteleo/dynamo-release#116]
when I use the code "python3 -m pip install git+https://github.com:aristoteleo/dynamo-release" to install this software, but the error was rraised as follow.
Collecting git+https://github.com:aristoteleo/dynamo-release
  Cloning https://github.com:aristoteleo/dynamo-release to /tmp/pip-req-build-3yrf835a
  Running command git clone -q https://github.com:aristoteleo/dynamo-release /tmp/pip-req-build-3yrf835a
  fatal: unable to access 'https://github.com:aristoteleo/dynamo-release/': URL using bad/illegal format or missing URL
ERROR: Command errored out with exit status 128: git clone -q https://github.com:aristoteleo/dynamo-release /tmp/pip-req-build-3yrf835a Check the logs for full command output.
So, what your suggestion for this error?

**Comment by Xiaojieqiu** [comment]
Hi @Golden-proteogenomics , please refer to our installation guidance: 

https://dynamo-release.readthedocs.io/en/latest/ten_minutes_to_dynamo.html#how-to-install

If you have further issues, please let me know.

**Comment by Golden-proteogenomics** [comment]
ok，thanks. but there are a new question when I use the code
 `import matplotlib
matplotlib.use('Agg')
import dynamo as dyn
dyn.get_all_dependencies_version()
dyn.configuration.set_figure_params('dynamo', background='white')
adata = dyn.sample_data.zebrafish()`
the error will arise in this formation “    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shuai/.local/lib/python3.8/site-packages/dynamo/sample_data.py", line 80, in zebrafish
    adata = get_adata(url, filename)
  File "/home/shuai/.local/lib/python3.8/site-packages/dynamo/sample_data.py", line 29, in get_adata
    urlretrieve(url, filename)  # download the data
  File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1369, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1329, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>” and Ithis this example_data of zebrafish couldnot download, please could tell me what that reason?

**Comment by Xiaojieqiu** [comment]
Those datasets are hosted on dropbox. If the dropbox service is blocked, you cannot download it. You may need a VPN to resolve this. Feel free to email me to get those datasets if you still have troubles. I will take some time to host the dataset on our institute's public server sometime soon.

**Comment by Golden-proteogenomics** [comment]
I am sorry that although we have opened VPN, we still can’t download this data. So, we need your help to give us a way to download the data. 
On the other hand, the code in the web "https://dynamo-release.readthedocs.io/en/latest/scEU_seq_rpe1_analysis_kinetic.html" is "rpe1 = dyn.read('/Users/xqiu/Dropbox (Personal)/dynamo/dont_remove/rpe1.h5ad')" meaning to use the cell cycle dataset from Battich, et al (2020). So, I want to know what and how to produce those datasets in GEO GSE128365, which mentioned by Battich, et al, because I searched for the data they uploaded, but did not find the file in the format you mentioned.

**Comment by Xiaojieqiu** [comment]
The source code for the ` dyn.sample_data.zebrafish()` is here:
https://github.com/aristoteleo/dynamo-release/blob/master/dynamo/sample_data.py

If you do have vpn, try to download the file linked in the source code:
https://www.dropbox.com/s/5wk3q2xhgqai2xq/zebrafish.h5ad?dl=1

The data for rep1 is processed by us. I am extremely busy these days so if you want the data from us, you may need to wait for 1 or two weeks for me to update the package and readthedocs page. If you want the data now, email me to request the data as I mentioned above (xqiu@wi.mit.edu). 

(For rep1 data, however, a little thinking and scrambling our github issues (e.g: https://github.com/aristoteleo/dynamo-release/issues/110) from your side should enable you to produce the same data. )

**Comment by Golden-proteogenomics** [comment]
I'm sorry to bother you so much, and you have been eager to help us. this is my email `sun_jinshuai@grmh-gdl.cn` for communication issues. Could you give me both data for me in mailbox attachment?
