### ISSUE TITLE
[related to paper]What is cscRNA-seq

### ISSUE THREAD

**Issue by brianpenghe** [aristoteleo/dynamo-release#119]
I couldn't find the definition of cscRNA-seq. Do you know what it is?

**Comment by Xiaojieqiu** [comment]
it is defined multiple times in the updated preprint (https://www.biorxiv.org/content/10.1101/696724v2), see introduction and result section on page 4. Same for tscRNA-seq. 

cscRNA-seq: conventional single cell RNA sequencing
tscRNA-seq: time-resolved single cell RNA sequencing (or metabolic labeling enabled scRNA-seq)

**Comment by brianpenghe** [comment]
You are right. Thanks!
