### ISSUE TITLE
From Seurat to Dynamo

### ISSUE THREAD

**Issue by RM-SCB** [aristoteleo/dynamo-release#18]
Hello,

I would be interested in trying Dynamo, however, all the data pre-processing of my data has been done in seurat and scater. Would it be feasible to start with Dynamo from a pre-processed dataset? (I also have a loom file as output of velocyto)

Many thanks

**Comment by Xiaojieqiu** [comment]
Thanks for your interest in using dynamo. It is certainly feasible to do that, though you may need to know the data infrastructure for both seurat or scater. Here are some of my suggestions: 

1. you may start with the loom file directly and use it for dynamo analysis. Dynamo's preprocessing steps are pretty robust in my hand and we are happy to improve it if any specific suggestion provided. Also, Dynamo supports projecting velocity vectors to arbitrary space, which means you can take the umap or tsne, etc. from seurat, scater and project on to that space. 

2. as far as I understand, seurat / scater don't support preprocessing on the spliced or unspliced matrix. However, you could still manually configure a dynamo object (based on anndata) to force it uses the same feature genes, reduced pca space, etc if you really like what seurat / scater's preprocessing steps. If you can get those relevant data from seurat or scater object, I can provide detailed scripts for you on how to construct a dynamo object that uses those data. 

Let me know if you need anything else we didn't cover in our tutorials or workflow. Happy to help!

**Comment by Xiaojieqiu** [comment]
hey @RM-SCB, dynamo is now on PyPi after more than 1100 commits and I would like to get some feedback before I advocate it. please let me know what I should accommodate to the issue you raised
