### ISSUE TITLE
Harmonize anndata layer nomenclature in a pulse - chase experiment

### ISSUE THREAD

**Issue by jmartinrufino** [aristoteleo/dynamo-release#183]
Hi Xiaojie, 

Currently the input to dyn.tl.recipe_deg_data requires the layer with labeled counts to be named 'new'. To better reflect the nature of those counts in a pulse chase experiment, it could be good to use 'labeled' as the name for that layer instead. 

Thanks,
Jorge

**Comment by Xiaojieqiu** [comment]
thanks Jorge, this is a good point! We probably harmonize adata layers with labeled, total instead of new, total. Will make a refactor soon
