### ISSUE TITLE
dyn.pl.plot_energy

### ISSUE THREAD

**Issue by terooatt** [aristoteleo/dynamo-release#205]
Hi,

Thanks for this package. I updated dynamo to the latest version and I get this error when I run dyn.pl.plot_energy. Can yo help?

dyn.get_all_dependencies_version()
package	cvxopt	dynamo-release	hdbscan	loompy	matplotlib	networkx	numdifftools	numpy	pandas	python-igraph	scikit-learn	scipy	setuptools	trimap	umap-learn	pre-commit	statsmodels	seaborn	colorcet	tqdm	pynndescent	numba
version	1.2.3	1.0.0	0.8.27	3.0.6	3.3.4	2.5	0.9.39	1.20.3	1.2.0	0.9.1	0.23.2	1.6.0	52.0.0.post20210125	1.0.14	0.5.1	2.13.0	0.12.2	0.11.1	2.0.6	4.56.2	0.5.2	0.52.0

dyn.pl.plot_energy(adata)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-112-a726a8e48e90> in <module>
----> 1 dyn.pl.plot_energy(adata)

~/miniconda3/envs/scanpy/lib/python3.7/site-packages/dynamo/plot/scVectorField.py in plot_energy(adata, basis, vecfld_dict, figsize, fig, save_show_or_return, save_kwargs)
   1199         if vf_key not in adata.uns.keys():
   1200             raise ValueError(
-> 1201                 f"Your adata doesn't have the key for Vector Field with {basis} basis."
   1202                 f"Try firstly running dyn.tl.VectorField(adata, basis={basis})."
   1203             )

ValueError: Your adata doesn't have the key for Vector Field with None basis.Try firstly running dyn.tl.VectorField(adata, basis=None).

**Comment by Xiaojieqiu** [comment]
Hi @terooatt the error is self-explanatory, you need to of course first run `dyn.tl.VectorField(adata, basis='umap')` before you can plot the loss over optimization iterations. 

Btw, just to make sure, is this what you expected?

**Comment by terooatt** [comment]
Thanks, I tried that but the dyn.tl.VectorField function doesn't exist! 

dyn.tl.VectorField(adata, basis='umap')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-155-ae4e5bc2fa5c> in <module>
----> 1 dyn.tl.VectorField(adata, basis='umap')

AttributeError: module 'dynamo.tl' has no attribute 'VectorField'

**Comment by Xiaojieqiu** [comment]
sorry, I need to update the error message, it should be `dyn.vf.VectorField(adata, basis='umap')`. 

Also please follow the notebooks to run the vector field learning first before showing the loss over optimization iteration

**Comment by terooatt** [comment]
Thanks!

**Comment by Zifeng1995** [comment]
> sorry, I need to update the error message, it should be `dyn.vf.VectorField(adata, basis='umap')`.
> 
> Also please follow the tutorials to run the vector field learning first before trying to plot the loss over optimization iteration:
> 
> https://dynamo-release.readthedocs.io/en/latest/Differential_geometry.html

![image](https://user-images.githubusercontent.com/53402047/135242452-c7b34783-7ca5-4a2e-adec-3781da3e3287.png)
I had the same error. I should rerun the VectorField with none basis?
