### ISSUE TITLE
Adjusting the transparency of dynamo plot

### ISSUE THREAD

**Issue by 117999** [aristoteleo/dynamo-release#209]
Hi Dr.Qiu, 

I have found that the transparency of the point of cells in dynamo plots (UMAP, Streamline Plot, grid vector plot, etc) is too high, sometimes making it difficult to distinguish and visualize different cell clusters. However, I did not find the parameter, like the alpha value, that could be used to adjust the transparency in these plots. 

I will appreciate it a lot if you could help us to adjust the transparancy of the plots. 

Sincerely,
Yuchen

**Comment by Xiaojieqiu** [comment]
I think you can pass alpha = 0.8, for example to all those plots to reduce the transparency. 

umap, streamline and other plots are based on dyn.pl.scatters which has an alpha argument. let me know how it goes

**Comment by 117999** [comment]
The alpha value changes works for dyn.pl.umap(), but for streamlined plot and grid vector, the transparency did not change.

**Comment by Xiaojieqiu** [comment]
you need to pass `s_kwargs_dict={"alpha": 0.8}` to streamline and grid plot
