### ISSUE TITLE
Issues about pp.recipe_monocle

### ISSUE THREAD

**Issue by Zifeng1995** [aristoteleo/dynamo-release#237]
Sorry to bother you again! I learned your tutorial and tried this method on our data. However, I have some problems with the API pp.recipe_monocle. Can I skip the process step and use our normalized data and the PCA matrix? If this can be done, I can keep the data with the previous analysis. BTW, can I regress out the cell cycle gene before calculating the velocity? Thanks for your help!

**Comment by Xiaojieqiu** [comment]
Can you please let me know what is error when you run pp.recipe_monocle? 

You certainly can use other normalization data or PCA matrix (alternatively you can use your own UMAP) but you need to set up the adata object properly to ensure no other downstream issues

**Comment by Zifeng1995** [comment]
Hi @Xiaojieqiu，I just want to know how to use other normalization data or PCA matrix. I should add what kind of matrix in to the adata object?
