### ISSUE TITLE
ValueError: looks like your var_names may be corrupted (i.e. include nan values)

### ISSUE THREAD

**Issue by Fra-Mante** [aristoteleo/dynamo-release#238]
Thank you developing Dynamo! I would like to familiarise with you software but I get errors early on following the commands in the online tutorial (https://dynamo-release.readthedocs.io/en/latest/scEU_seq_rpe1_analysis_kinetic.html). Could you please help me?

1. Downloaded 'rpe1.h5ad' from 'https://www.dropbox.com/s/25enev458c8egn7/rpe1.h5ad?dl=1'

2. Set virtual environment:
      - Python 3.7.9
      - pip freeze: algopy==0.5.7 anndata==0.7.5 annoy==1.17.0 appnope==0.1.2 backcall==0.2.0 backports.entry-points selectable==1.1.0 cached-property==1.5.2 cfgv==3.3.1 click==8.0.1 colorcet==2.0.6 cvxopt==1.2.7 cycler==0.10.0 Cython==0.29.24 decorator==5.1.0 distlib==0.3.3 dynamo-release==1.0.0 filelock==3.3.0 h5py==3.4.0 hdbscan==0.8.27 identify==2.3.0 importlib-metadata==4.8.1 ipython==7.28.0 jedi==0.18.0 joblib==1.0.1 kiwisolver==1.3.2 llvmlite==0.37.0 loompy==3.0.6 matplotlib==3.4.3 matplotlib-inline==0.1.3 natsort==7.1.1 networkx==2.6.3 nodeenv==1.6.0 numba==0.54.0
numdifftools==0.9.40 numpy==1.20.0 numpy-groupies==0.9.14 packaging==21.0 pandas==1.3.3 param==1.11.1 parso==0.8.2 patsy==0.5.2 pexpect==4.8.0 pickleshare==0.7.5 Pillow==8.3.2 platformdirs==2.4.0 pre-commit==2.15.0 prompt-toolkit==3.0.20 ptyprocess==0.7.0 pyct==0.4.8 Pygments==2.10.0 pynndescent==0.5.4 pyparsing==2.4.7 python-dateutil==2.8.2 python-igraph==0.9.6 pytz==2021.3 PyYAML==5.4.1 scikit-learn==1.0 scipy==1.7.1 seaborn==0.11.2
six==1.16.0 statsmodels==0.13.0 texttable==1.6.4 threadpoolctl==3.0.0 toml==0.10.2 tqdm==4.62.3 traitlets==5.1.0 trimap==1.0.15 typing-extensions==3.10.0.2 umap-learn==0.5.1 virtualenv==20.8.1 wcwidth==0.2.5 zipp==3.6.0 

3. Run:
`import warnings
warnings.filterwarnings('ignore')
import dynamo as dyn
import anndata
import pandas as pd
import numpy as np
import scipy.sparse
from anndata import AnnData
from scipy.sparse import csr_matrix
dyn.get_all_dependencies_version()
rpe1 = dyn.read('/my/path/rpe1.h5ad')
rpe1_kinetics = rpe1[rpe1.obs.exp_type=='Pulse', :]
rpe1_kinetics.obs['time'] = rpe1_kinetics.obs['time'].astype(str)
rpe1_kinetics.obs.loc[rpe1_kinetics.obs['time'] == 'dmso', 'time'] = -1
rpe1_kinetics.obs['time'] = rpe1_kinetics.obs['time'].astype(float)
rpe1_kinetics = rpe1_kinetics[rpe1_kinetics.obs.time != -1, :]
rpe1_kinetics.layers['new'], rpe1_kinetics.layers['total'] = rpe1_kinetics.layers['ul'] + rpe1_kinetics.layers['sl'], rpe1_kinetics.layers['su'] + rpe1_kinetics.layers['sl'] + rpe1_kinetics.layers['uu'] + rpe1_kinetics.layers['ul']
del rpe1_kinetics.layers['uu'], rpe1_kinetics.layers['ul'], rpe1_kinetics.layers['su'], rpe1_kinetics.layers['sl']
dyn.pl.basic_stats(rpe1_kinetics)`

4. Error obtained: 
> ... ValueError: Length of values (1) does not match length of index (2793) ... ValueError: looks like your var_names may be corrupted (i.e. include nan values).

Similar error when I run:
`dyn.pl.basic_stats(rpe1_kinetics)`
or
`adata = dyn.sample_data.zebrafish()
dyn.pp.recipe_monocle(adata)`

Dynamo dependencies versions match the packages install in my virtual environment. 
Thank you for your help.

**Comment by Xiaojieqiu** [comment]
Hi @Fra-Mante thank you for using dynamo. 

This looks like a pandas version error. What is your pandas version? 
Have you tried using the version shown in the notebook? (the version is 1.1.1). 

I can check this issue with a newer version of pandas later

**Comment by Fra-Mante** [comment]
oh yes. it is working now. thanks! 
Based on your experience, how many cells are necessary for obtaining proper estimated transcriptomic RNA velocity with cell cycle staging (as in scEU-seq cell cycle)? I can see that in the dataset use for the tutorial there are ~2800 cells. Would you say that this is the minimum required? Thanks

**Comment by Fra-Mante** [comment]
Thanks for the information!

**Comment by Fra-Mante** [comment]
Downgrading pandas solved the problems with dyn.pl.basic_stats() but not with the remaining dyn of the scEU-seq tutorial.
First, it asked to install the package "mygene". After installing it, the code stops after running the command
`dyn.pp.recipe_monocle(rpe1_kinetics, n_top_genes=1000, total_layers=False)`
and outputs the following error again: 

> ValueError: looks like your var_names may be corrupted (i.e. include nan values)

(don't know if it is relevant but dyn.pp.recipe_monocle outputs 33 input query terms found no hit rather than 29 as in the tutorial.)
The dependencies are:

> package pre-commit colorcet cvxopt dynamo-release hdbscan loompy matplotlib  \
> version     2.15.0    2.0.6  1.2.6          1.0.0  0.8.27  3.0.6      3.4.3   
> 
> package networkx   numba numdifftools   numpy pandas pynndescent  \
> version    2.6.3  0.54.0       0.9.40  1.20.3  1.1.1       0.5.4   
> 
> package python-igraph scikit-learn  scipy seaborn setuptools statsmodels  \
> version         0.9.6       0.24.2  1.7.1  0.11.2     47.1.0      0.12.2   
> 
> package    tqdm  trimap umap-learn  
> version  4.62.2  1.0.15      0.5.1  

I then created a different venv with the same dependencies as shown in the tutorial. But the code got an early stop and the following error was output:

> numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

When I then update numpy to 1.21.0, the following error is output (same when upgrated to 1 .20.0:

> TypeError: Cannot use .str.upper with values of inferred dtype 'bytes'.

Here the dependences after upgrading numpy:

> package anndata colorcet cvxopt dynamo-release hdbscan loompy matplotlib  \
> version   0.7.4    2.0.2  1.2.3         0.95.2  0.8.26  3.0.6      3.3.0   
> 
> package   numba numdifftools   numpy pandas pynndescent python-igraph  \
> version  0.51.0       0.9.39  1.21.0  1.1.1       0.4.8         0.8.2   
> 
> package scikit-learn  scipy seaborn setuptools statsmodels    tqdm  trimap  \
> version       0.23.2  1.5.2   0.9.0     49.6.0      0.11.1  4.48.2  1.0.12   
> 
> package umap-learn  
> version      0.4.6 


Could you please give me any indication on how to solve this? 
Thank you in advance.
