### ISSUE TITLE
Error when using dyn.vf.Potential(adata)

### ISSUE THREAD

**Issue by behroozazarkhalili** [aristoteleo/dynamo-release#242]
Hi. A problem seems to be occurring when utilizing the `dyn.vf.Potential(adata)`. It appears that the problem stems from the way you define `Function` based on the `VecFld `key, which should instead be replaced by `VecFld_umap` or `VecFld_pca`.

```
import dynamo as dyn
dyn.get_all_dependencies_version()
adata = dyn.sample_data.DentateGyrus()

dyn.pp.recipe_monocle(adata)
dyn.tl.dynamics(adata)

dyn.tl.reduceDimension(adata, basis='umap', enforce=True)
dyn.tl.cell_velocities(adata, basis='umap')
dyn.tl.cell_wise_confidence(adata)

dyn.vf.VectorField(adata, basis='umap')
dyn.vf.topography(adata, basis='umap')

dyn.ext.ddhodge(adata, basis="umap")
dyn.vf.Potential(adata)
```

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-26-cfb8d7f31f26> in <module>
----> 1 `dyn.vf.Potential(adata)`

python3.8/site-packages/dynamo/vectorfield/scPotential.py in `Potential(adata, DiffMat, method, **kwargs)`
    450     
    451 
--> 452     `Function = adata.uns["VecFld"]`
    453     `DiffMat = DiffusionMatrix if DiffMat is None else DiffMat`
    454     `pot = Pot(Function, DiffMat, **kwargs)`

python3.8/site-packages/anndata/compat/_overloaded_dict.py in `__getitem__(self, key)`
     98            ` return self.overloaded[key].get()`
     99        ` else:`
--> 100             `return self.data[key]`
    101 
    102     `def __setitem__(self, key, value):`

`KeyError: 'VecFld'`

**Comment by Xiaojieqiu** [comment]
hey @behroozazarkhalili , thanks for using dynamo. please refer to the answer to this issue: https://github.com/aristoteleo/dynamo-release/issues/353
