### ISSUE TITLE
TypeError: fit() missing 3 required positional arguments: 'adata', 'x_lim', and 'y_lim'

### ISSUE THREAD

**Issue by behroozazarkhalili** [aristoteleo/dynamo-release#243]
I encountered the following error when calling `dyn.vf.Potential(adata)`

```
import dynamo as dyn
dyn.get_all_dependencies_version()
adata = dyn.sample_data.DentateGyrus()

dyn.pp.recipe_monocle(adata)
dyn.tl.dynamics(adata)

dyn.tl.reduceDimension(adata, basis='umap', enforce=True)
dyn.tl.cell_velocities(adata, basis='umap')
dyn.tl.cell_wise_confidence(adata)

dyn.vf.VectorField(adata, basis='umap')
dyn.vf.topography(adata, basis='umap')

dyn.ext.ddhodge(adata, basis="umap")

adata.uns["VecFld"] = adata.uns.get("VecFld_umap")
dyn.vf.Potential(adata)
```

---------------------------------------------------------------------------------------------------------------------------------------
TypeError Traceback (most recent call last)
----> 1 `dyn.vf.Potential(adata)`

python3.8/site-packages/dynamo/vectorfield/scPotential.py in `Potential(adata, DiffMat, method, **kwargs)`
    453     `DiffMat = DiffusionMatrix if DiffMat is None else DiffMat`
    454     `pot = Pot(Function, DiffMat, **kwargs)`
--> 455    ` pot.fit(method=method)`
    456 
    457     `return adata`

TypeError: `fit() `missing 3 required positional arguments: `'adata'`, `'x_lim'`, and` 'y_lim'`

**Comment by Xiaojieqiu** [comment]
btw, vector field and all downstream analyses can be calculated in pca space (and in the original gene expression if you like) also.

**Comment by behroozazarkhalili** [comment]
> btw, the vector field and all downstream analyses can be calculated in PCA space (and in the original gene expression if you like) also.

Dear @Xiaojieqiu, 
Thanks for your prompt reply.

It appears that the problem stems from the implementation of the `fit` method in the `Pot `class, which requires three variables: 'adata', 'x_lim', and 'y_lim'.

**Comment by Xiaojieqiu** [comment]
thanks again @behroozazarkhalili  
I got the problem you are talking about. That bug was something I left unfixed for a while for historical reasons and because the ddhoge approach seems to work pretty well. But I should be able to fix this specific bug shortly.

**Comment by behroozazarkhalili** [comment]
> thanks again, @behroozazarkhalili I got the problem you are talking about. That bug was something I left unfixed for a while for historical reasons and because the ddhoge approach seems to work pretty well. But I should be able to fix this specific bug shortly.

Hi again,
Although `dyn.ext.ddhodge(adata, basis="umap")` works well, it generates `VecFld_umap` or `VecFld_pca`, not `VecFld` in `adata.uns`. Moreover, It appears that the problem in `dyn.vf.Potential(adata)` stems from the implementation of the `fit `method in the `Pot` class, which requires three variables: `adata`, `x_lim`, and `y_lim`, and this issue is irrelevant to `dyn.ext.ddhodge(adata, basis="umap")` execution.

**Comment by behroozazarkhalili** [comment]
@Xiaojieqiu, Are you able to provide an approximate time frame for when this issue will be fixed?

**Comment by Xiaojieqiu** [comment]
basically, I was suggesting you use pseudotime from ddhodge as a measure of potential which is better than the vf.Potential function in many ways. just out of curiosity, why are insisted to use the Potential function to get the potential? What end results are you expecting to have? I may be able to fix it next week

**Comment by behroozazarkhalili** [comment]
> > basically, I was suggesting you use pseudotime from ddhodge as a measure of potential which is better than the vf.Potential function in many ways. just out of curiosity, why are insisted to use the Potential function to get the potential? What end results are you expecting to have? I may be able to fix it next week
> 
> Hi, At this time, there is no specific reason; however, I thought it would be better to either modify or correct this section of the code as I move forward with your official tutorial.

BTW, even `dyn.ext.ddhodge(adata, basis="umap")` works well, it generates `VecFld_umap` or `VecFld_pca`, not `VecFld` in `adata.uns`, which can raise an error.

**Comment by Xiaojieqiu** [comment]
I see the issue now, looks like you are following the 10 minutes to dynamo section (unfortunately both the Potential function and that section have not been updated because of historial reasons--- can fix those next week). I would suggest you start with other tutorials, such as zebrafish, to get started with dynamo: 

https://dynamo-release.readthedocs.io/en/latest/notebooks/zebrafish.html

**Comment by behroozazarkhalili** [comment]
> I see the issue now, looks like you are following the 10 minutes to dynamo section (unfortunately both the Potential function and that section have not been updated because of historial reasons--- can fix those next week). I would suggest you start with other tutorials, such as zebrafish, to get started with dynamo:
> 
> https://dynamo-release.readthedocs.io/en/latest/notebooks/zebrafish.html

Please also update the last cell of the tutorial as well.

```
import matplotlib.pyplot as plt

fig1, f1_axes = plt.subplots(ncols=2, nrows=2, constrained_layout=True, figsize=(12, 10))
f1_axes
f1_axes[0, 0] = dyn.pl.cell_wise_vectors(adata, color='umap_ddhodge_potential', pointsize=0.1, alpha = 0.7, ax=f1_axes[0, 0], quiver_length=6, quiver_size=6, save_show_or_return='return')
f1_axes[0, 1] = dyn.pl.grid_vectors(adata, color='speed_umap', ax=f1_axes[0, 1], quiver_length=12, quiver_size=12, save_show_or_return='return')
f1_axes[1, 0] = dyn.pl.streamline_plot(adata, color='divergence_pca', ax=f1_axes[1, 0], save_show_or_return='return')
f1_axes[1, 1] = dyn.pl.topography(adata, color='acceleration_umap', ax=f1_axes[1, 1], save_show_or_return='return')
plt.show()
```
