### ISSUE TITLE
TypeError: Categorical is not ordered for operation max

### ISSUE THREAD

**Issue by pigraul** [aristoteleo/dynamo-release#254]
Hi,

I encountered the following error when calling  `adata = dyn.pp.recipe_monocle(adata)`

>    1491         """ assert that we are ordered """
   1492         if not self.ordered:
-> 1493             raise TypeError(
   1494                 f"Categorical is not ordered for operation {op}\n"
   1495                 "you can use .as_ordered() to change the "</br>
TypeError: Categorical is not ordered for operation max
you can use .as_ordered() to change the Categorical to an ordered one

Which data should I order?

Thank you.

**Comment by Xiaojieqiu** [comment]
Hey @pigraul this is an error I never see before. Can you please provide more context? 

Also, in the newest dynamo version, by default dyn.pp.recipe_monocle will update the anndata object in place and return nothing. So you should not return it to adata itself

**Comment by pigraul** [comment]
Hi @Xiaojieqiu ,

I found the cause of the error.

If I set the tkey as category, it gave the error.

```python
adata.obs['label_time'] = 1
tkey = 'label_time'
adata.obs['label_time'] = adata.obs.label_time.astype('category')
```

If I delete the last line,  it works well.

Thanks for your information.

**Comment by Xiaojieqiu** [comment]
oh yeah, the labeling time has to be numeric value because it will be used in kinetic parameters estimation
