### ISSUE TITLE
TypeError when using dyn.tl.gene_wise_confidence

### ISSUE THREAD

**Issue by pigraul** [aristoteleo/dynamo-release#257]
Hi,

I got an error when evaluate the confidence of gene-wise velocity,

`dyn.tl.gene_wise_confidence(adata,group='cell_type', lineage_dict={'Progenitor': ['HSC']}, ekey="M_t", vkey="velocity_T")`

>calculating gene velocity vectors confidence based on phase portrait location with priors of progenitor/mature cell types: 0it [00:00, ?it/s]
>---------------------------------------------------------------------------
>TypeError                                 Traceback (most recent call last)
> \<ipython-input-38-e4bd21336d21\> in \<module\>
>----> 1 dyn.tl.gene_wise_confidence(adata,group='cell_type', lineage_dict={'Progenitor': ['HSC']}, ekey="M_t", vkey="velocity_T")
>
>/Database/script/soft/python3.8/lib/python3.8/site-packages/dynamo/tools/metric_velocity.py in gene_wise_confidence(adata, group, lineage_dict, genes, ekey, vkey, X_data, V_data, V_threshold)
>      355                     else:
>      356                         # induction phase (upper curve -- phase curve above the linear line indicates steady states)
>--> 357                         prog_confidence = 1 - sum(prog_vals_v < threshold_val)[0] / len(
>      358                             prog_vals_v
>      359                         )  # most cells should upregulate / ss
>
>TypeError: 'int' object is not subscriptable

I am not sure about the parameter "lineage_dict", did I set it wrong, or other parameters? 
adata after dyn.tl.dynamics:
>AnnData object with n_obs × n_vars = 8518 × 22699
>    obs: 'cell_type', 'sample', 'cluster', 'umap_1', 'umap_2', 'label_time', 'time', 'nGenes', 'nCounts', 'pMito', 'use_for_pca', 'Size_Factor', 'initial_cell_size', 'total_Size_Factor', 'initial_total_cell_size', 'new_Size_Factor', 'initial_new_cell_size', 'ntr', 'cell_cycle_phase'
>     var: 'nCells', 'nCounts', 'pass_basic_filter', 'log_cv', 'score', 'log_m', 'use_for_pca', 'frac', 'ntr', 'alpha', 'beta', 'gamma', 'half_life', 'alpha_b', 'alpha_r2', 'gamma_b', 'gamma_r2', 'gamma_logLL', 'delta_b', 'delta_r2', 'bs', 'bf', 'uu0', 'ul0', 'su0', 'sl0', 'U0', 'S0', 'total0', 'beta_k', 'gamma_k', 'use_for_dynamics'
>    uns: 'pp', 'velocyto_SVR', 'PCs', 'explained_variance_ratio_', 'pca_mean', 'pca_fit', 'feature_selection', 'cell_phase_genes', 'dynamics'
>    obsm: 'X_umap', 'X_pca', 'X', 'cell_cycle_scores'
>    varm: 'alpha'
>    layers: 'new', 'total', 'X_total', 'X_new', 'M_t', 'M_tt', 'M_n', 'M_tn', 'M_nn', 'velocity_N', 'velocity_T'
>    obsp: 'moments_con'

Thank you!

**Comment by Xiaojieqiu** [comment]
Hey @pigraul 
you can check this github issue (#218) to understand how to set up that parameter. 
https://github.com/aristoteleo/dynamo-release/issues/218

You only need to use this when you believe the RNA velocity flow may be problematic (see more details from the documentation of this function)

**Comment by pigraul** [comment]
Thank you @Xiaojieqiu , it's helpful~~

Yes, I observed backward vector flow from Erythroblasts to Ery_progenitor, so I wanna filter some low confidence genes.
