### ISSUE TITLE
Installation Issues 

### ISSUE THREAD

**Issue by Pinolinoo** [aristoteleo/dynamo-release#261]
Hi, 

Thanks for this great tool! I wanted to get familiar with it a bit and tried to install it via pip `pip install dynamo-release`. I created a new blank conda env and got an error during installation. 

The error occured during the step ` Running setup.py install for cvxopt ... error` ... ` 1 error generated.
    error: command '/usr/bin/clang' failed with exit code 1`

Can you help me with that?

**Comment by Xiaojieqiu** [comment]
Hi @Pinolinoo, this error is related to clang setting in your computer.  a quick google search lead to discussions on this topic: 
https://stackoverflow.com/questions/50940302/installing-mysql-python-causes-command-clang-failed-with-exit-status-1-on-mac

Can you try this solution from the above thread? 
`sudo xcode-select --switch /Library/Developer/CommandLineTools`

**Comment by Pinolinoo** [comment]
Thanks for you quick reply. 
I tried this but sadly it still gives me the same error!

**Comment by Pinolinoo** [comment]
mh I see.. I tried playing around with it for a bit and thought maybe it's a common issue. But in this case I will keep tryin to solve it on my own :) thanks for your help, will keep you updated
