### ISSUE TITLE
AttributeError: can't set attribute [when using animation]

### ISSUE THREAD

**Issue by anshu957** [aristoteleo/dynamo-release#279]
My code is simply one of the examples provided by the dynamo in its docs. I'm able to construct the vector field and stream line plots, however when I generate the animation it always runs into the following error:

![image](https://user-images.githubusercontent.com/32687084/154361551-41d0ae2c-60ac-46a1-980a-fcb111a6c65b.png)

I've tried this on my server (linux machine) and on my local Mac as well, both throws this error.  I have also tried all the variations of animation as per the docs but still ends up with the same error.  I could generate the `anim` object without any problem, however I think the error arises when I try to render it.

**Comment by Xiaojieqiu** [comment]
@anshu957 thanks for using our tool. This seems like an issue related to HTML function. maybe you need to upgrade your IPython version? 

can you please try `HTML(anim.to_html5_video())` ? 

Alternatively, just save animation as a gif file: 
```
dyn.mv.animate_fates(adata, color='Cell_type', basis='umap', n_steps=100, fig=fig, ax=ax,
                     save_show_or_return='save', logspace=True, max_time=None)
```

**Comment by anshu957** [comment]
Thank you ! 
Updating Ipython worked for me.

**Comment by hyjforesight** [comment]
hello @anshu957 
I also update IPython, didn't work.

**Comment by hyjforesight** [comment]
hello @Xiaojieqiu 
Could you please share the codes for saving gif in another name instead of the default one 'fate_ani', because we tried setting different progenitor cells and run the animation function to get a different gif, but the later gif always covers the previous one because of the same gif file name?
We tried below codes, but got errors.
```python
fig, ax = plt.subplots()
ax = dyn.pl.topography(adata, color='Cell_type', ax=ax, save_show_or_return='return')
dyn.mv.animate_fates(adata, color='Cell_type', basis='umap', n_steps=100, fig=fig, ax=ax,
                     save_show_or_return='save', save_kwargs={"prefix": 'dynamo_fate_animation', "ext": 'gif', "transparent": True, "close": True, "verbose": True},
                     logspace=True, max_time=None)
```
Thanks!
Best,
YJ
