### ISSUE TITLE
Issue about ten_minutes_to_dynamo

### ISSUE THREAD

**Issue by ChristopherLeeZG** [aristoteleo/dynamo-release#281]
Dear Dr.Xiao,
The dynamo is a amazing tools! 
I run the code step by step from  `dynamo-release/tree/master/docs/source)/ten_minutes_to_dynamo.rst`.
But I get some report error about it.
The first error:

`dyn.tl.gene_wise_confidence(adata, group='group', lineage_dict={'Progenitor': ['terminal_cell_state']})`
> /public/home/lzg/anaconda3/lib/python3.8/site-packages/pandas/core/arrays/categorical.py:2487: FutureWarning: The `inplace` parameter in pandas.Categorical.remove_unused_categories is deprecated and will be removed in a future version.
>   res = method(*args, **kwargs)
> calculating gene velocity vectors confidence based on phase portrait location with priors of progenitor/mature cell types: 0it [00:00, ?it/s]
> KeyError                                  Traceback (most recent call last)
> ~/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
>    3079             try:
> -> 3080                 return self._engine.get_loc(casted_key)
>    3081             except KeyError as err:
> 
> pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()
> 
> pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()
> 
> pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()
> 
> pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()
> 
> KeyError: 'group'
> 
> The above exception was the direct cause of the following exception:
> 
> KeyError                                  Traceback (most recent call last)
> <ipython-input-19-06ced1cab493> in <module>
> ----> 1 dyn.tl.gene_wise_confidence(adata, group='group', lineage_dict={'Progenitor': ['terminal_cell_state']})
> 
> ~/anaconda3/lib/python3.8/site-packages/dynamo/tools/metric_velocity.py in gene_wise_confidence(adata, group, lineage_dict, genes, ekey, vkey, X_data, V_data, V_threshold)
>     337     else:
>     338         if genes is None or len(genes) != X_data.shape[1]:
> --> 339             raise ValueError(
>     340                 f"When providing V_data, a list of genes name that corresponds to the columns of X_data "
>     341                 f"must be provided"
> 
> ~/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py in __getitem__(self, key)
>    3022             if self.columns.nlevels > 1:
>    3023                 return self._getitem_multilevel(key)
> -> 3024             indexer = self.columns.get_loc(key)
>    3025             if is_integer(indexer):
>    3026                 indexer = [indexer]
> 
> ~/anaconda3/lib/python3.8/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
>    3080                 return self._engine.get_loc(casted_key)
>    3081             except KeyError as err:
> -> 3082                 raise KeyError(key) from err
>    3083 
>    3084         if tolerance is not None:
> 
> KeyError: 'group'

And the second error:
`dyn.vf.VectorField(adata)`

> |-----> vectorfield calculation begins...
> |-----> Retrieve X and V based on `genes`, layer: None. 
>         Vector field will be learned in the gene expression space.
> 
> KeyError                                  Traceback (most recent call last)
> <ipython-input-24-a7c5fb61a59f> in <module>
> ----> 1 dyn.vf.VectorField(adata)
> 
> ~/anaconda3/lib/python3.8/site-packages/dynamo/vectorfield/topography.py in VectorField(adata, basis, layer, dims, genes, normalize, grid_velocity, grid_num, velocity_key, method, model_buffer_path, return_vf_object, map_topography, pot_curl_div, cores, result_key, copy, **kwargs)
>     644             "Retrieve X and V based on `genes`, layer: %s. \n "
>     645             "       Vector field will be learned in the gene expression space." % layer
> --> 646         )
>     647         valid_genes = (
>     648             list(set(genes).intersection(adata.var.index))
> 
> ~/anaconda3/lib/python3.8/site-packages/anndata/_core/aligned_mapping.py in __getitem__(self, key)
>     146 
>     147     def __getitem__(self, key: str) -> V:
> --> 148         return self._data[key]
>     149 
>     150     def __setitem__(self, key: str, value: V):
> 
> KeyError: None

The following code is all get error. ( Those need running dyn.vf.VectorField ）

Thanks for you reading.

**Comment by Xiaojieqiu** [comment]
hey @ChristopherLeeZG, thanks for using dynamo. the 10 minutes was used as a general intro and was written more than one year ago (I will need to update it). For now, I would suggest you go through the reproducible notebooks from our readthedocs: https://dynamo-release.readthedocs.io/en/latest/notebooks/Differential_geometry.html

Regarding to your specific question, you will need to update those strings (`group`, 'terminal_cell_state') to the corresponding ones in your own data. I am not sure about the vectorfield one without more context, though. 

Please do go through our other tutorials and if you find any issues in your data (or our sample data), please report to me. I will assist you ASAP. 

(I will also update the 10 minutes  page shortly also).

**Comment by ChristopherLeeZG** [comment]
Thank you for your reply！I'm going to practice again

**Comment by ChristopherLeeZG** [comment]
您好，已经收到您的信件。我会及时阅读并回复。谢谢。                                                                       Lee.ZG

**Comment by alexpiccinich** [comment]
How do we find the group str to our corresponding data? 
Also, when running the vector field I am also getting KeyError: None. 
Please let me know if you know how to resolve these errors from 10 minutes to dynamo tutorial?

**Comment by ChristopherLeeZG** [comment]
您好，已经收到您的信件。我会及时阅读并回复。谢谢。                                                                       Lee.ZG

**Comment by Xiaojieqiu** [comment]
thanks @alexpiccinich 
for the `group` str, that is the cell type annoation in `adata.obs`. You will need to define yourself. 

The 10 minutes tutorial is rather outdated. Things are getting crazy for me these days, I am on a few interviews and grants and papers, but I should have the bandwidth to update the 10 minutes tutorial by the end of this month. 

For now, please check out tutorials like those under `DIFFERENTIAL GEOMETRY` sections.
