### ISSUE TITLE
scNT-seq data not found

### ISSUE THREAD

**Issue by mkyriak** [aristoteleo/dynamo-release#283]
Hello Qiu,
Thank you for all the information provided and the very detailed tutorials.
I went through the zebrafish tutorial and now I would like to compare the estimated lineages when having splicing data only and when having labeling data. Hence, I tried to follow the scNT-seq tutorial, however,  I realized that the provided dropbox links for the labeling and the splicing information are not working. Could you please provide the links once again?

Thank you in advance!
Maria

**Comment by Xiaojieqiu** [comment]
Could you please try `dyn.tl.scNT_seq_neuron_splicing()` and `dyn.tl.scNT_seq_neuron_labeling`. 

Thanks,
Xiaojie

**Comment by mkyriak** [comment]
Thank your for your rapid response, I have tried it and I am getting the following error: 
AttributeError: module 'dynamo.tl' has no attribute 'scNT_seq_neuron_splicing'

Thank you once again,
Maria

**Comment by Xiaojieqiu** [comment]
sorry.  I was mean to be `sample_data` instead of `tl`.

**Comment by mkyriak** [comment]
I tried using `dyn.sample_data.` to load the data. I can see all the datasets available, I am also able to load them (i.e. `dyn.sample_data.hgForebrainGlutamatergic()`, `dyn.sample_data.pancreatic_endocrinogenesis()`, `dyn.sample_data.zebrafish()`). However, when I am trying to load dyn.sample_data.scNT_seq(), I see that it is empty. Also, I tried both your suggestions; `dyn.sample_data.scNT_seq_neuron_splicing()` and `dyn.sample_data.scNT_seq_neuron_labeling`, and again it's giving me the following errors:
`>>> neuron_labeling = dyn.sample_data.scNT_seq_neuron_labeling()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'dynamo.sample_data' has no attribute 'scNT_seq_neuron_labeling'`
`>>> neuron_splicing = dyn.sample_data.scNT_seq_neuron_labeling()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'dynamo.sample_data' has no attribute 'scNT_seq_neuron_labeling'`

**Comment by enzeas** [comment]
> dyn.sample_data.scNT_seq_neuron_labeling()

hi， I see the URL from the source code， scNT_seq‘s URL will auto redirect to the zebrafish data， is this normal？
scNT_seq_neuron_labeling：https://www.dropbox.com/s/5wk3q2xhgqai2xq/neuron_labeling.h5ad?dl=1
zebrafish：https://www.dropbox.com/s/5wk3q2xhgqai2xq/zebrafish.h5ad?dl=1

**Comment by 3254c** [comment]
Hi,
I have recently learned about dynamo and find it a very interesting tool.
I have tried the tutorial on scEU-seq organoid, but perhaps the download of the sample data is not working.
When I used `dyn.sample_data.scEU_seq_organoid()`, different data(rpe1.h5ad) is downloaded. I opened the source code URL and it seems that a redirect is also happening when downloading this data.
I would like to do some more tutorials to understand dynamo, so I would appreciate it if you could help me.
Thanks,
