### ISSUE TITLE
Question about dyn.pl.umap

### ISSUE THREAD

**Issue by lh12565** [aristoteleo/dynamo-release#284]
Hi, I try to run "Zebrafish pigmentation" tutorial as follows:
```python
adata=dyn.read('zebrafish.h5ad')
dyn.pp.recipe_monocle(adata)
dyn.tl.dynamics(adata, model='stochastic', cores=10)
dyn.tl.reduceDimension(adata)
dyn.pl.umap(adata, color='Cell_type',pointsize=0.5, alpha = 0.7,save_show_or_return='save')
```
The output feels strange:

![dyna](https://user-images.githubusercontent.com/24219321/154927493-ef13ed71-0216-48b7-a27d-5710ad99b555.png)

The file comes from #116:  https://www.dropbox.com/s/5wk3q2xhgqai2xq/zebrafish.h5ad?dl=1

**Comment by Xiaojieqiu** [comment]
dear @lh12565 this is a umap version issue. We have fixed this in our latest dynamo. Please pull the latest dynamo and setup install. I will release a new dynamo version this week. 

Thanks,
Xiaojie

**Comment by lh12565** [comment]
Thanks, when I install last dynamo, it works! But there is a another problem about "dyn.vf.rank_jacobian_genes", when I run "DIFFERENTIAL GEOMETRY" tutorial. I run the code as below:
```python
full_reg_rank = dyn.vf.rank_jacobian_genes(adata,
                                           groups='Cell_type',
                                           mode="full_reg",
                                           abs=True,
                                           output_values=True)
full_eff_rank = dyn.vf.rank_jacobian_genes(adata,
                                           groups='Cell_type',
                                           mode='full_eff',
                                           abs=True,
                                           exclude_diagonal=True,
                                           output_values=True)
```
It returns NULL both full_reg_rank and full_eff_rank as below:
```python
type(full_reg_rank)
#<class 'NoneType'>
```
The strange thing is that I can draw the picture normally when I run other codes after that:
```python
dyn.ext.ddhodge(adata, basis='pca')
transition_genes = adata.var_names[adata.var.use_for_transition]
dyn.pl.kinetic_heatmap(adata,
                       genes=transition_genes,
                       tkey='pca_ddhodge_potential',
                       gene_order_method='maximum',
                       mode='pseudotime',
                       color_map='viridis',
                       yticklabels=False,
                      save_show_or_return='save',
                      save_kwargs={"prefix": 'umap_kinetic_heatmap'})
dyn.pl.streamline_plot(adata, color=['pca_ddhodge_potential', 'Cell_type'],save_show_or_return='save',save_kwargs={"prefix": 'umap_dynamo_streamline',"ext": 'png'})
```

**Comment by Xiaojieqiu** [comment]
Dear @lh12565, thanks for reporting this. 

For your first question: 

The API to this function has been changes. please set `return_df = True` instead of `output_values` and the adata are also saved in the adata. 

@dummyindex can you please update the corresponding notebook

**Comment by lh12565** [comment]
Thanks, it works! But the result is a little different:
```
              tmsb4x  tmsb4x_values  ...    slc6a2  slc6a2_values
0    si:dkey-183i3.5       0.001212  ...     tubb5       0.000508
1                mt2       0.001088  ...    elavl4       0.000445
2               mbpb       0.000976  ...     rtn1a       0.000342
3               mbpa       0.000934  ...      tmsb       0.000338
4         zgc:136930       0.000932  ...     rtn1b       0.000335
5               rgcc       0.000874  ...     ptmaa       0.000332
6  si:ch211-156j16.1       0.000855  ...    stmn2a       0.000327
7         zgc:153704       0.000754  ...     sparc       0.000302
8               fosb       0.000654  ...    stmn2b       0.000281
9              mcl1b       0.000640  ...  atp6v0cb       0.000257
```
The top genes (mbpb and si:ch211-156j16.1) in your results are ranked 3 and 7 for me. Did this mean that the reliability of these two regulators is not high?

**Comment by Xiaojieqiu** [comment]
these could be just numerical instability, as many steps may be not fully deterministic such as dimension reduction, vector field reconstruction, etc. -- I would not worry about this too much if the overall conclusion is the same
