### ISSUE TITLE
recipe_monocle on kb_python output

### ISSUE THREAD

**Issue by jmartinrufino** [aristoteleo/dynamo-release#285]
Hi Xiaojie!

When running dyn.pp.recipe_monocle on the output from kb_python (for conventional scRNAseq), some input ENSEMBL IDs find duplicate hits for gene symbols, or find no hit, as shown in the error below:
```
45 input query terms found dup hits:
	[('ENSG00000229425', 2), ('ENSG00000182378', 2), ('ENSG00000178605', 2), ('ENSG00000226179', 2), ('E
192 input query terms found no hit:
	['ENSG00000278198', 'ENSG00000273496', 'ENSG00000278782', 'ENSG00000277761', 'ENSG00000277726', 'ENS
Pass "returnall=True" to return complete lists of duplicate or missing query terms.
```
To avoid errors from dynamo in subsequent steps, a workaround is to use 
`adata[:, adata.var_names.notnull()]`

after running dyn.pp.recipe_monocle. But I was wondering if there is a more permanent solution? It looks like this is an issue of the mygene dependency that contains a different ENSEMBL ID dataset than the one used in kb_python. @Lioscro might have some thoughts too from kb_python?

Thanks, 
Jorge

**Comment by Lioscro** [comment]
Is working with gene names directly an option? You can provide `--gene-names` to `kb count` to have all the vars be gene names (gene names that have multiple gene IDs will be summed).

**Comment by Xiaojieqiu** [comment]
Thanks Joseph! I think your `collapse_anndata` function in kb-python collapses the adata object right? We can call it outside to manually collapse the adata object then. I remeber you always return the `gene_short_name` column in the` .var`, right? 

Kb-python doesn't export any functions though so we need to import directly from the file  installed in the `site-packages` folder.

**Comment by jmartinrufino** [comment]
@Lioscro to your point, running the following command (using `--gene-names`)
`kb count --h5ad -i ~/utilities/kb/index.idx -g ~/utilities/kb/t2g.txt -x 10XV3 -o "${cDNA_seq[i]}_kb_output" --tmp "${cDNA_seq[i]}_tmp" --workflow lamanno -c1 ~/utilities/kb/spliced_t2c.txt  -c2 ~/utilities/kb/unspliced_t2c.txt --filter bustools --gene-names -t 40 ${cDNA_seq1[i]} ${cDNA_seq2[i]}`

still results in an anndata object where the vars are ENSEMBL IDs
