### ISSUE TITLE
KeyError with dyn.pp.recipe_monocle (pandas)

### ISSUE THREAD

**Issue by dietmar113** [aristoteleo/dynamo-release#286]
Dear dynamo-developer,

I have an issue with "dyn.pp.recipe_monocle". I tried already pandas 1.1.5 and 1.1.1. -> see below.
my adata.var looks like this, and there are no duplicated gene_ids or missing values (nan) -> the complete data are attached:

gene_ids	feature_types	genome	nCells	nCounts
MIR1302-2HG	ENSG00000243485	Gene Expression	GRCh38	0	0.0
FAM138A	ENSG00000237613	Gene Expression	GRCh38	0	0.0
OR4F5	ENSG00000186092	Gene Expression	GRCh38	0	0.0
AL627309.1	ENSG00000238009	Gene Expression	GRCh38	10	10.0
AL627309.3	ENSG00000239945	Gene Expression	GRCh38	1	1.0
AL627309.2	ENSG00000239906	Gene Expression	GRCh38	0	0.0
AL627309.5	ENSG00000241860	Gene Expression	GRCh38	100	100.0
AL627309.4	ENSG00000241599	Gene Expression	GRCh38	0	0.0
AP006222.2	ENSG00000286448	Gene Expression	GRCh38	5	5.0
AL732372.1	ENSG00000236601	Gene Expression	GRCh38	1	1.0
OR4F29	ENSG00000284733	Gene Expression	GRCh38	0	0.0
AC114498.1	ENSG00000235146	Gene Expression	GRCh38	0	0.0
OR4F16	ENSG00000284662	Gene Expression	GRCh38	0	0.0

Another question:
How can I load 10x .h5 data without using the read_10x_h5 function of scanpy?

`import dynamo as dyn
import scanpy as sc
impoer anndata

adata = sc.read_10x_h5('.../outs/count/filtered_feature_bc_matrix.h5', genome='GRCh38', gex_only=True)
adata.obs['sample_id'] = 'a032'
dyn.pp.recipe_monocle(adata)

|-----> apply Monocole recipe to adata...
|-----> <insert> pp to uns in AnnData Object.
|-----------> <insert> has_splicing to uns['pp'] in AnnData Object.
|-----------> <insert> has_labling to uns['pp'] in AnnData Object.
|-----------> <insert> splicing_labeling to uns['pp'] in AnnData Object.
|-----------> <insert> has_protein to uns['pp'] in AnnData Object.
|-----> ensure all cell and variable names unique.
|-----> ensure all data in different layers in csr sparse matrix format.
|-----> ensure all labeling data properly collapased
|-----------> <insert> tkey to uns['pp'] in AnnData Object.
|-----------> <insert> experiment_type to uns['pp'] in AnnData Object.
|-----> filtering cells...
|-----> filtering genes...
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/anaconda3/envs/dynamo/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2897             try:
-> 2898                 return self._engine.get_loc(casted_key)
   2899             except KeyError as err:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 0

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-130-68f58723e74a> in <module>
----> 1 dyn.pp.recipe_monocle(adata)

~/anaconda3/envs/dynamo/lib/python3.6/site-packages/dynamo/preprocessing/preprocess.py in recipe_monocle(adata, reset_X, tkey, t_label_keys, experiment_type, normalized, layer, total_layers, splicing_total_layers, X_total_layers, genes_use_for_norm, genes_to_use, genes_to_append, genes_to_exclude, exprs_frac_max, method, num_dim, sz_method, scale_to, norm_method, pseudo_expr, feature_selection, n_top_genes, maintain_n_top_genes, relative_expr, keep_filtered_cells, keep_filtered_genes, keep_raw_layers, scopes, fc_kwargs, fg_kwargs, sg_kwargs, copy)
   1622     adata = filter_genes(
   1623         adata,
-> 1624         **filter_genes_kwargs,
   1625     )
   1626 

~/anaconda3/envs/dynamo/lib/python3.6/site-packages/dynamo/preprocessing/preprocess.py in filter_genes(adata, filter_bool, layer, min_cell_s, min_cell_u, min_cell_p, min_avg_exp_s, min_avg_exp_u, min_avg_exp_p, max_avg_exp, min_count_s, min_count_u, min_count_p, shared_count)
   1110     if shared_count is not None:
   1111         layers = get_layer_keys(adata, "all", False)
-> 1112         tmp = get_shared_counts(adata, layers, shared_count, "gene")
   1113         if tmp.sum() > 2000:
   1114             detected_bool &= tmp

~/anaconda3/envs/dynamo/lib/python3.6/site-packages/dynamo/preprocessing/utils.py in get_shared_counts(adata, layers, min_shared_count, type)
    336 def get_shared_counts(adata, layers, min_shared_count, type="gene"):
    337     layers = list(set(layers).difference(["X", "matrix", "ambiguous", "spanning"]))
--> 338     layers = np.array(layers)[~pd.DataFrame(layers)[0].str.startswith("X_").values]
    339 
    340     _nonzeros, _sum = None, None

~/anaconda3/envs/dynamo/lib/python3.6/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2904             if self.columns.nlevels > 1:
   2905                 return self._getitem_multilevel(key)
-> 2906             indexer = self.columns.get_loc(key)
   2907             if is_integer(indexer):
   2908                 indexer = [indexer]

~/anaconda3/envs/dynamo/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2898                 return self._engine.get_loc(casted_key)
   2899             except KeyError as err:
-> 2900                 raise KeyError(key) from err
   2901 
   2902         if tolerance is not None:

KeyError: 0
[a032.txt.gz](https://github.com/aristoteleo/dynamo-release/files/8123106/a032.txt.gz)
`

**Comment by Xiaojieqiu** [comment]
Dear @dietmar113, thanks for using our tool. May I kindly ask do you have `spliced` and `unspliced` layers in your data (or any labeling data)? If not, that may explain the error. Please note that the real error happens here: 

`--> 338 layers = np.array(layers)[~pd.DataFrame(layers)[0].str.startswith("X_").values]`

dynamo assumes spliced/unspliced data or labeling data is used because it centers on vector fields learning and predicting 

Regarding 10x data, we rely on anndata for data IO. Although we could write our own version of 10 x data loader, I saw discussion in anndata issue tracker about moving scanpy's 10x reader to anndata: https://github.com/theislab/anndata/issues/195
