### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by wulabupenn** [aristoteleo/dynamo-release#3]
Hi dynamo group,

I used bellow command to install however it didn't work for me. Is something wrong with my set-up?
`pip install git+https://github.com:aristoteleo/dynamo-release` 

> Collecting git+https://github.com:aristoteleo/dynamo-release
  Cloning https://github.com:aristoteleo/dynamo-release to /tmp/pip-req-build-i1smn3l5
  Running command git clone -q https://github.com:aristoteleo/dynamo-release /tmp/pip-req-build-i1smn3l5
  fatal: unable to access 'https://github.com:aristoteleo/dynamo-release/': Port number ended with 'a'
ERROR: Command "git clone -q https://github.com:aristoteleo/dynamo-release /tmp/pip-req-build-i1smn3l5" failed with error code 128 in None

Best,
Peng

**Comment by Xiaojieqiu** [comment]
Hi Peng, can you please try the second approach as I mentioned? git clone the repo and `pip install directory_to_dynamo_release_repo`?

**Comment by wulabupenn** [comment]
Hi Xiaojie,

Thanks for your reply promptly! I can git clone the repo. However when I tried pip install, the error message is:
`pip install dynamo-release`

> Collecting dynamo-release
  ERROR: Could not find a version that satisfies the requirement dynamo-release (from versions: none)
ERROR: No matching distribution found for dynamo-release

Peng

**Comment by Xiaojieqiu** [comment]
you need to use 'pip install dynamo-release/'

**Comment by wulabupenn** [comment]
Cool, it works. Thank you!

**Comment by Xiaojieqiu** [comment]
Thanks, please let us know how other things go! The current package is in alpha version so please use it with cautions. We are working hard to make it more user-friendly by following conventions in single cell field. For now, you may look at dynamo-notebooks to check for the analysis dynamo can do. The notebooks are prepared with source code directly but you should be able to figure out how to run with functions in the package. Updated notebooks will be released shortly.

**Comment by wulabupenn** [comment]
Thank you for your kind notes. I am very exciting that this package can fit into the nascent related single cell data sets. We have some data sets which would be a good fit for this package. The dynamo notebooks are well organized. I will start from there and may bother you if i have some problem with that. Thanks again!

**Comment by Xiaojieqiu** [comment]
glad to hear that dynamo is helpful for your project. and totally, it is my pleasure to help
