### ISSUE TITLE
NotImplementedError: Failed to write value for uns/velocyto_SVR/SVR

### ISSUE THREAD

**Issue by cubense** [aristoteleo/dynamo-release#300]
Hi Dr.Qiu,

When i try to  save the result of the dynamo analysis 
`adata.write('D:/PROJECT/pm/2/2-fastmnn/stromal/stfilanalysis/mnstromal.h5ad', compression='gzip')`
 ,  error has been reported:

`NotImplementedError                       Traceback (most recent call last)
E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\utils.py in func_wrapper(elem, key, val, *args, **kwargs)
    187         try:
--> 188             return func(elem, key, val, *args, **kwargs)
    189         except Exception as e:

E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\h5ad.py in write_not_implemented(f, key, value, dataset_kwargs)
    156     # and have explicit implementations for everything else
--> 157     raise NotImplementedError(
    158         f"Failed to write value for {key}, "

NotImplementedError: Failed to write value for uns/velocyto_SVR/SVR, since a writer for type <class 'method'> has not been implemented yet.

The above exception was the direct cause of the following exception:

NotImplementedError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_4244/1051686763.py in <module>
----> 1 mn.write('mnstromal.h5ad', compression='gzip')

E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_core\anndata.py in write_h5ad(self, filename, compression, compression_opts, force_dense, as_dense)
   1842             filename = self.filename
   1843 
-> 1844         _write_h5ad(
   1845             Path(filename),
   1846             self,

E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\h5ad.py in write_h5ad(filepath, adata, force_dense, as_dense, dataset_kwargs, **kwargs)
    123         write_attribute(f, "varp", adata.varp, dataset_kwargs=dataset_kwargs)
    124         write_attribute(f, "layers", adata.layers, dataset_kwargs=dataset_kwargs)
--> 125         write_attribute(f, "uns", adata.uns, dataset_kwargs=dataset_kwargs)
    126     if adata.isbacked:
    127         adata.file.open(filepath, "r+")

E:\conda\miniconda\envs\draw\lib\functools.py in wrapper(*args, **kw)
    875                             '1 positional argument')
    876 
--> 877         return dispatch(args[0].__class__)(*args, **kw)
    878 
    879     funcname = getattr(func, '__name__', 'singledispatch function')

E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\h5ad.py in write_attribute_h5ad(f, key, value, *args, **kwargs)
    137     if key in f:
    138         del f[key]
--> 139     _write_method(type(value))(f, key, value, *args, **kwargs)
    140 
    141 

E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\h5ad.py in write_mapping(f, key, value, dataset_kwargs)
    297 def write_mapping(f, key, value, dataset_kwargs=MappingProxyType({})):
    298     for sub_key, sub_value in value.items():
--> 299         write_attribute(f, f"{key}/{sub_key}", sub_value, dataset_kwargs=dataset_kwargs)
    300 
    301 

E:\conda\miniconda\envs\draw\lib\functools.py in wrapper(*args, **kw)
    875                             '1 positional argument')
    876 
--> 877         return dispatch(args[0].__class__)(*args, **kw)
    878 
    879     funcname = getattr(func, '__name__', 'singledispatch function')

E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\h5ad.py in write_attribute_h5ad(f, key, value, *args, **kwargs)
    137     if key in f:
    138         del f[key]
--> 139     _write_method(type(value))(f, key, value, *args, **kwargs)
    140 
    141 

E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\h5ad.py in write_mapping(f, key, value, dataset_kwargs)
    297 def write_mapping(f, key, value, dataset_kwargs=MappingProxyType({})):
    298     for sub_key, sub_value in value.items():
--> 299         write_attribute(f, f"{key}/{sub_key}", sub_value, dataset_kwargs=dataset_kwargs)
    300 
    301 

E:\conda\miniconda\envs\draw\lib\functools.py in wrapper(*args, **kw)
    875                             '1 positional argument')
    876 
--> 877         return dispatch(args[0].__class__)(*args, **kw)
    878 
    879     funcname = getattr(func, '__name__', 'singledispatch function')

E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\h5ad.py in write_attribute_h5ad(f, key, value, *args, **kwargs)
    137     if key in f:
    138         del f[key]
--> 139     _write_method(type(value))(f, key, value, *args, **kwargs)
    140 
    141 

E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\utils.py in func_wrapper(elem, key, val, *args, **kwargs)
    189         except Exception as e:
    190             parent = _get_parent(elem)
--> 191             raise type(e)(
    192                 f"{e}\n\n"
    193                 f"Above error raised while writing key {key!r} of {type(elem)}"

NotImplementedError: Failed to write value for uns/velocyto_SVR/SVR, since a writer for type <class 'method'> has not been implemented yet.

Above error raised while writing key 'uns/velocyto_SVR/SVR' of <class 'h5py._hl.files.File'> from /.`

Appreciate it a lot if you can help me fix the problem.

Sincerely,

Cubense

**Comment by Xiaojieqiu** [comment]
@cubense thanks for using our tool. could you please run `dyn.clean(adata)` and delete adata.uns['velocyto_SVR'] with `del adata.uns['velocyto_SVR']` and resave then?. 

Thanks,
Xiaojie

**Comment by cubense** [comment]
@Xiaojieqiu 
Thank you for your reply. But after i run 
`dyn.cleanup(adata)
adata.uns['velocyto_SVR']
adata.write('adata.h5ad')` 
,a new error has been reported.
`TypeError                                 Traceback (most recent call last)
E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\utils.py in func_wrapper(elem, key, val, *args, **kwargs)
    187         try:
--> 188             return func(elem, key, val, *args, **kwargs)
    189         except Exception as e:

E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\h5ad.py in write_array(f, key, value, dataset_kwargs)
    193         value = _to_hdf5_vlen_strings(value)
--> 194     f.create_dataset(key, data=value, **dataset_kwargs)
    195 

E:\conda\miniconda\envs\draw\lib\site-packages\h5py\_hl\group.py in create_dataset(self, name, shape, dtype, data, **kwds)
    148 
--> 149             dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
    150             dset = dataset.Dataset(dsid)

E:\conda\miniconda\envs\draw\lib\site-packages\h5py\_hl\dataset.py in make_new_dset(parent, shape, dtype, data, name, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times, external, track_order, dcpl, allow_unknown_filter)
    139     if (data is not None) and (not isinstance(data, Empty)):
--> 140         dset_id.write(h5s.ALL, h5s.ALL, data)
    141 

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\h5d.pyx in h5py.h5d.DatasetID.write()

h5py\_proxy.pyx in h5py._proxy.dset_rw()

h5py\_conv.pyx in h5py._conv.str2vlen()

h5py\_conv.pyx in h5py._conv.generic_converter()

h5py\_conv.pyx in h5py._conv.conv_str2vlen()

TypeError: Can't implicitly convert non-string objects to strings

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\utils.py in func_wrapper(elem, key, val, *args, **kwargs)
    187         try:
--> 188             return func(elem, key, val, *args, **kwargs)
    189         except Exception as e:

E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\h5ad.py in write_list(f, key, value, dataset_kwargs)
    169 def write_list(f, key, value, dataset_kwargs=MappingProxyType({})):
--> 170     write_array(f, key, np.array(value), dataset_kwargs=dataset_kwargs)
    171 

E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\utils.py in func_wrapper(elem, key, val, *args, **kwargs)
    190             parent = _get_parent(elem)
--> 191             raise type(e)(
    192                 f"{e}\n\n"

TypeError: Can't implicitly convert non-string objects to strings

Above error raised while writing key 'uns/VecFld_umap/nullcline' of <class 'h5py._hl.files.File'> from /.

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_4244/2748614903.py in <module>
      1 #dyn.cleanup(mn)
      2 del mn.uns['velocyto_SVR']
----> 3 mn.write('D:/PROJECT/pm/2/2-fastmnn/stromal/stfilanalysis/mnstromal.h5ad', compression='gzip')

E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_core\anndata.py in write_h5ad(self, filename, compression, compression_opts, force_dense, as_dense)
   1842             filename = self.filename
   1843 
-> 1844         _write_h5ad(
   1845             Path(filename),
   1846             self,

E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\h5ad.py in write_h5ad(filepath, adata, force_dense, as_dense, dataset_kwargs, **kwargs)
    123         write_attribute(f, "varp", adata.varp, dataset_kwargs=dataset_kwargs)
    124         write_attribute(f, "layers", adata.layers, dataset_kwargs=dataset_kwargs)
--> 125         write_attribute(f, "uns", adata.uns, dataset_kwargs=dataset_kwargs)
    126     if adata.isbacked:
    127         adata.file.open(filepath, "r+")

E:\conda\miniconda\envs\draw\lib\functools.py in wrapper(*args, **kw)
    875                             '1 positional argument')
    876 
--> 877         return dispatch(args[0].__class__)(*args, **kw)
    878 
    879     funcname = getattr(func, '__name__', 'singledispatch function')

E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\h5ad.py in write_attribute_h5ad(f, key, value, *args, **kwargs)
    137     if key in f:
    138         del f[key]
--> 139     _write_method(type(value))(f, key, value, *args, **kwargs)
    140 
    141 

E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\h5ad.py in write_mapping(f, key, value, dataset_kwargs)
    297 def write_mapping(f, key, value, dataset_kwargs=MappingProxyType({})):
    298     for sub_key, sub_value in value.items():
--> 299         write_attribute(f, f"{key}/{sub_key}", sub_value, dataset_kwargs=dataset_kwargs)
    300 
    301 

E:\conda\miniconda\envs\draw\lib\functools.py in wrapper(*args, **kw)
    875                             '1 positional argument')
    876 
--> 877         return dispatch(args[0].__class__)(*args, **kw)
    878 
    879     funcname = getattr(func, '__name__', 'singledispatch function')

E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\h5ad.py in write_attribute_h5ad(f, key, value, *args, **kwargs)
    137     if key in f:
    138         del f[key]
--> 139     _write_method(type(value))(f, key, value, *args, **kwargs)
    140 
    141 

E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\h5ad.py in write_mapping(f, key, value, dataset_kwargs)
    297 def write_mapping(f, key, value, dataset_kwargs=MappingProxyType({})):
    298     for sub_key, sub_value in value.items():
--> 299         write_attribute(f, f"{key}/{sub_key}", sub_value, dataset_kwargs=dataset_kwargs)
    300 
    301 

E:\conda\miniconda\envs\draw\lib\functools.py in wrapper(*args, **kw)
    875                             '1 positional argument')
    876 
--> 877         return dispatch(args[0].__class__)(*args, **kw)
    878 
    879     funcname = getattr(func, '__name__', 'singledispatch function')

E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\h5ad.py in write_attribute_h5ad(f, key, value, *args, **kwargs)
    137     if key in f:
    138         del f[key]
--> 139     _write_method(type(value))(f, key, value, *args, **kwargs)
    140 
    141 

E:\conda\miniconda\envs\draw\lib\site-packages\anndata\_io\utils.py in func_wrapper(elem, key, val, *args, **kwargs)
    189         except Exception as e:
    190             parent = _get_parent(elem)
--> 191             raise type(e)(
    192                 f"{e}\n\n"
    193                 f"Above error raised while writing key {key!r} of {type(elem)}"

TypeError: Can't implicitly convert non-string objects to strings

Above error raised while writing key 'uns/VecFld_umap/nullcline' of <class 'h5py._hl.files.File'> from /.

Above error raised while writing key 'uns/VecFld_umap/nullcline' of <class 'h5py._hl.files.File'> from /.`
Do you have any suggestions for this? What should I do next?
Thank you!

**Comment by Xiaojieqiu** [comment]
please consider further delete those keys before saving. We will figure out a more robust mechanism for doing so later

**Comment by cubense** [comment]
Thank you for your reply and look forward to the further notes on the software Docs!

**Comment by jefferyUstc** [comment]
how is it now?

> please consider further delete those keys before saving. We will figure out a more robust mechanism for doing so later
