### ISSUE TITLE
How to find UMAP coordinate of attractor 

### ISSUE THREAD

**Issue by kzxkzx** [aristoteleo/dynamo-release#306]
Great work! Now I am following the Most probable path predictions tutorial, and I wonder how to get the UMAP coordinate of attractor ,you just write :
attractors = np.array(
    [
        [8.45201833, 9.37697661],
        [14.00630381, 2.53853712],
        [17.30550636, 6.81561775],
        [18.06891717, 11.9840678],
        [14.13613403, 15.22244713],
        [9.72644402, 14.83745969],
    ]
but for my data ,how can I get that information,thanks

**Comment by dummyindex** [comment]
Hi @kzxkzx ,

The resulted coordinates are stored in `adata.uns['VecFld_umap']['Xss']`. (assume you are using `umap` basis).

You can selected points similar to what is presented below.
```
Xss, ftype = adata_labeling.uns['VecFld_umap']['Xss'], adata_labeling.uns['VecFld_umap']['ftype']
good_fixed_points = [4, 1, 5, 7, 16, 26]
Xss[good_fixed_points], ftype[good_fixed_points]

adata_labeling.uns['VecFld_umap']['Xss'] = Xss[good_fixed_points]
adata_labeling.uns['VecFld_umap']['ftype'] = ftype[good_fixed_points]
dyn.pl.topography(adata_labeling, 
                  markersize=500,
                  basis='umap', 
                  fps_basis='umap', 
                  color=['pca_ddhodge_potential'],)
```
