### ISSUE TITLE
Results are not consistent between Windows and Linux

### ISSUE THREAD

**Issue by hyjforesight** [aristoteleo/dynamo-release#310]
Hello @Xiaojieqiu and dynamo team,
I know Linux/Mac is recommended for scientific computing, but I tried the Zebrafish pigmentation tutorial both on Windows (Windows 11 x64 21H2) and Unbuntu (v2004.2022.1.0) and found that the results are not consistent between Windows and Linux.
For Windows, I follow the tutorial coding and got results like below.
![image](https://user-images.githubusercontent.com/75048821/158709725-bd0c34f6-f3f7-41d1-b077-ed98a38a1608.png)

Which should look like this in the tutorial.
![image](https://user-images.githubusercontent.com/75048821/158709677-4149b95f-4cba-4ea0-b764-3a85ee1d4385.png)

Is it because of the `float`? Shall I do `adata.X = adata.X.astype('float64')` first?
Thanks!
Best,
YJ

**Comment by Xiaojieqiu** [comment]
Hi @hyjforesight, in the ideal world, we would expect everything can be reproduced exactly. However, the steps to get the streamline plot involves steps that are not fully deterministic, for example, the UMAP dimension reduction is stochastic and can depend on the seed. In additional, any small numerical changes across different operation systems, python and numpy versions may also contribute the difference you see in the above figure. If you are interested in ensuring the reproducibility or any additional improvements, you are welcome to look into this more systematically and contribute to dynamo.

**Comment by hyjforesight** [comment]
hello @Xiaojieqiu , thanks for the response. I will try to fix the seed for my future running. I think the different directions don't change the conclusion. It works quite well and the animation is awesome!
