### ISSUE TITLE
question about the one-shot model on develop version

### ISSUE THREAD

**Issue by KaKaPan2022** [aristoteleo/dynamo-release#312]
Hi Dr.Qiu,
We are recently running Dynamo’s one-shot model, here follows our code
`‘dyn.pp.recipe_monocle(adata,tkey=’time’,experiment_type=’one-shot’)’`
`‘dyn.tl.dynamics(adata)’`
`‘dyn.tl.reduceDimension(adata)’`
‘`dyn.tl.cell_velocities(adata,calc_rnd_vel=True)’`
However, we have encountered the error report
`‘Exception: only less than 5 genes satisfies transition gene selection criteria’.` We are not sure how it would appear like this.
Also, we have noticed that an develop version of Dynamo <1.0.0.dev200+a17ee0a> would successfully run the same code, while it fails on the 1.0.0 version. 
Though, when I updated my virtual environment and tried to re-install the dynamo, I failed to install the develop version. I am wondering whether the develop version can still be installed?
When I tried to check the version of my Dynamo
`‘dyn.__version__’`
It appears ’0.0.0’, which is also weird.
Could you help us figure them out.
Thanks
Luyao

**Comment by Xiaojieqiu** [comment]
thanks for using dynamo! Please git clone the latest dynamo version from github and then setup install. 

Meanwhile, we will release a new dynamo version this weekend or early next week.

thanks,
Xiaojie

**Comment by KaKaPan2022** [comment]
Dear Dr.Qiu,
Thanks a lot for your kindly reply.
We are looking forward to your update and will appreciate it a lot if you can inform us once it is released.
Thanks again,
Luyao
