### ISSUE TITLE
implement read_h5() similar to what other packages provide

### ISSUE THREAD

**Issue by pereperi** [aristoteleo/dynamo-release#316]
Hi,

I am trying to use the Dynamo software (version 1.0.0) with python (version 3.7.3) in order to analyze scRNAseq data and I am having trouble in properly loading the data (already preprocessed using CellRanger). I understand that the way to do it would be by using the .h5 matrix generated by CellRanger, but the read_h5() function that is mentioned in the "10 minutes to Dynamo" section does not appear to be found. I see all the other functions such as read_csv(), read_h5ad(), etc. but I can't find a way to load the data. When I run the get_all_dependencies_version() command I obtain the following output:

package setuptools pre-commit colorcet cvxopt dynamo-release hdbscan loompy  \
version     40.8.0     2.17.0         3.0.0       1.3.0       1.0.0            0.8.28     3.0.7   

package matplotlib networkx   numba numdifftools   numpy pandas pynndescent  \
version      3.5.1       2.6.3        0.55.1       0.9.40       1.21.5   1.3.5       0.5.6   

package python-igraph scikit-learn  scipy seaborn statsmodels    tqdm trimap  \
version         0.9.9        1.0.2              1.7.3  0.11.2      0.13.2        4.63.0  1.1.2   

package umap-learn  
version      0.5.2 

Any help will be appreciated!

**Comment by Xiaojieqiu** [comment]
Dear @pereperi thanks for your question. We rely on anndata for loading the data object. You may consider using scanpy to load the data with something like 
```
import scanpy as sc
sc.read_h5(file_path)
```

There are discussion on porting the read_h5 function in scanpy to anndata. If not, we may eventually include this function in dynamo package. 

Also, my understanding is that cellranger data may don't output spliced / unspliced RNA, you may need to use other tools, such as kb-python (https://github.com/pachterlab/kb_python/tree/master/kb_python) to process your data first and then you can load the resultant h5ad file. dynamo is especially designed for processing splicing and labeling data 

Please let me know if you need any additional helps 

Thanks,
Xiaojie

**Comment by Xiaojieqiu** [comment]
@dummyindex please help writting a `read_h5` function in dynamo too
