### ISSUE TITLE
Question about kmc

### ISSUE THREAD

**Issue by hahahah-single** [aristoteleo/dynamo-release#320]
Hi when I use Zebrafish data , runing dyn.tl.cell_velocities(adata, method='kmc'), I got this problem:ValueError: Input contains NaN, infinity or a value too large for dtype('float64').But when using other methods such as “fp” ,"cosine","pearson", it runs successfully.How should i solve it？

**Comment by Xiaojieqiu** [comment]
Dear @hahahah-single thanks for using dynamo. We don't recommend use kmc method at this time. Please use other kernels for velocity projections. thanks!

**Comment by hahahah-single** [comment]
Thanks ！I would like to ask what is the cause of this problem？Does your answer mean that this method is not recommended for this version of the dynamo?

**Comment by Xiaojieqiu** [comment]
kmc is not necessarily the best option for velocity projection. So it is not our intention to fix the bug at this moment  as it is not our high priority and you should use others as I recommended. The default method also works fine for most of the cases. 

We am working on some new projection approaches but it will only release later. Nevertheless, what is worthnoting is that dynamo' real power lays its downstream analytical vector field learning, dynamical systems and differential geometry analyses as well as most probable paths and in silico perturbation predictions. This is where it makes us unique. Please feel free to ask us questions on these fronts.
