### ISSUE TITLE
Problem of LAP

### ISSUE THREAD

**Issue by mhtksc** [aristoteleo/dynamo-release#322]
Hi,
I try to run the LAP's tutorial, and I get a different result of kinetic_heatmap( HSC->Bas) as the fig1. GATA2 was expressed from high to low in my result, but your tutorial is the opposite. I don't known why it happened. 
And I don't know how this is sorted. Is it sorted from highest to lowest expressed value from HSC to Bas, or is it sorted by the importance of the developmental events? 
Thanks.
![fig1](https://user-images.githubusercontent.com/102647944/160767374-1496af53-cf4a-4b84-9830-c331563d5a46.png)

**Comment by dummyindex** [comment]
Hi @mhtksc ,
Thanks for trying the LAP tutorial.
I confirmed that in our notebook case, GATA2 is indeed from low to high, which is different from yours. Can you provide your notebook? We can take a look and see what makes the results different. 
From our new notebook set: https://dynamo-release.readthedocs.io/en/latest/notebooks/tutorial_hsc_dynamo_basophil_lineage/tutorial_hsc_dynamo_basophil_lineage.html
![image](https://user-images.githubusercontent.com/12120524/160992936-9dbdc603-fc92-4f5b-9130-637e79aa87a9.png)

looks like GATA2 should go from low to high (expression) along the path from HSC->Bas, and GATA2's peak should appear later.

**Comment by mhtksc** [comment]
Hi @dummyindex I followed the tutorial step by step. The code is in the lap.zip. I can't download the data via `dyn.sample_data.hematopoiesis()`. I downloaded the data in https://pitt.box.com/shared/static/kyh3s4wrxdywupn9wk9r2j27vzlvk8vf.h5ad (hematopoiesis_v1.h5ad) from dynamo/sample_data.py
[lap.zip](https://github.com/aristoteleo/dynamo-release/files/8425503/lap.zip)
