### ISSUE TITLE
[old released version on Pypi] Dependencies issue. Newer pandas version yields a KeyError with dyn.pp.recipe_monocle 

### ISSUE THREAD

**Issue by LidiaML** [aristoteleo/dynamo-release#323]
Hi!

Thanks for developing and maintaining Dynamo, congratulations for your great work.

I am trying to play around with the Dentate Gyrus example and I got an error that has been previously reported that seems to be related with panda's version [KeyError looks like your var_names may be corrupted (i.e. include nan values)]. I tried to solve this by downgrading panda's from 1.3.4 to 1.1.1 but then I got some dependency conflicts with other tools that require pandas >=1.2.0. The closest I could get was pandas 1.2.4. It seems that this pandas version is compatible but the later (1.3.4) is not. 

It would be great if you could have a look at this.

Thanks!!!

Lídia

**Comment by LidiaML** [comment]
Hi again!

I could bypass the dependencies conflict regarding pandas but then ecountered another error that seems to be related with matplotlib version. When I ran the dyn.pl.umap function in the Zebrafish tutorial I get TypeError (register_cmap() got an unexpected keyword argument 'override_builtin'). I googled a bit and what seems more plausible is that dynamo is trying to use an argument that is deprecated since version 3.3.0.

I think I will have to create a conda environment with the specific versions that are compatible with dynamo but I could not find them listed anywhere. Perhaps the dynamo version that is released to PyPi has more dependency issues than the latest I can clone from GitHub?? I will try to use the latest version and see if I have less problems. 

Any advice on this regard will be more than welcome!

**Comment by dummyindex** [comment]
Hi @LidiaML ,

Thanks for reporting the issue. We will fix the cmap issue in the next release asap. Please try installing the latest github dynamo version since the pypi version was released 1 year ago.

**Comment by dummyindex** [comment]
You can try the following environment file. (import with conda
[dynamo-dev.txt](https://github.com/aristoteleo/dynamo-release/files/8175960/dynamo-dev.txt)
`conda env create -f environment.yml`

The environment file above is the version we used to reproduce several notebooks on readthedocs recently.

**Comment by dummyindex** [comment]
Regarding the matplotlib registercmap issue: register_cmap is still on 3.5.1's documentation: https://matplotlib.org/stable/api/cm_api.html
We tested most of the tutorial notebooks on matplotlib 3.4.3. Thanks for reporting this issue and in the future we will consider removing this argument or fix the matplotlib version in the release version.

**Comment by elfofmaxwell** [comment]
Thank you for reporting the issue and currently with `pandas 1.5.0` and `matplotlib 3.5.3` the problems seem to be solved. This issue would be closed. If you have any other new questions, please let us know.
