### ISSUE TITLE
dyn.pl.scatters() can only plot one figure

### ISSUE THREAD

**Issue by hyjforesight** [aristoteleo/dynamo-release#325]
Hello Dynamo,
I only can plot one figure when doing this following the Zebrafish pigmentation tutorial.
Could you please help me with this issue?
Thanks!
Best,
YJ

```python
dyn.pl.scatters(adata, x=np.repeat('umap_ddhodge_potential', 9), y=['mitfa', 'pax3a', 'tfec', 'dct', 'alx4b', 'tyrp1b', 'gpnmb', 'pmela', 'pnp4a'], color='Cell_type', layer='X_spliced', background='white', ncols=3, pointsize=0.25, alpha=0.8)
```
![image](https://user-images.githubusercontent.com/75048821/161341760-d2d0bc2a-6361-482f-9ad3-43857f4f659f.png)

numpy is 1.21.5, matplotlib is 3.4.3

**Comment by dummyindex** [comment]
Hi @hyjforesight ,

We found this issue and shoud have fixed it in a recent PR. Could you re-install the github main version?

Thanks,
Ke
