### ISSUE TITLE
Some troubles with Loading data

### ISSUE THREAD

**Issue by XUEbaogai0101** [aristoteleo/dynamo-release#332]
Hi Dr.Qiu,
I met problem when I use dyn.read() to read my loom data, which was processing by velocyto and run sucessfully in scvelo.
But it seems that something wrong with my data, but I don' know how to fix it.
Error shows as following:

> `
> adata = dyn.read('WT.loom')
> TypeError                                 Traceback (most recent call last)
> /tmp/ipykernel_1760149/501344354.py in <module>
> ----> 1 adata = dyn.read('WT.loom')
> 
> ~/miniconda3/envs/dynamo/lib/python3.7/site-packages/anndata/_io/h5ad.py in read_h5ad(filename, backed, as_sparse, as_sparse_fmt, chunk_size)
>     440     _clean_uns(d)  # backwards compat
>     441 
> --> 442     return AnnData(**d)
>     443 
>     444 
> 
> TypeError: __init__() got an unexpected keyword argument 'attrs'
> `

And I find some problems when I read a concatenated anndata as well which also was processing by velocyto and I didn't process it.

> `adata = scv.read('WT.loom', cache=True)
> ldata = scv.read('WC.loom', cache=True)
> aaa=adata.concatenate(ldata,join='outer')
> aaa.write('WT_WC_.h5ad',compression="gzip")
> adata = dyn.read('WT_WC_.h5ad')
> 
> KeyError                                  Traceback (most recent call last)
> ~/miniconda3/envs/dynamo/lib/python3.7/site-packages/anndata/_io/utils.py in func_wrapper(elem, *args, **kwargs)
>     155         try:
> --> 156             return func(elem, *args, **kwargs)
>     157         except Exception as e:
> 
> ~/miniconda3/envs/dynamo/lib/python3.7/site-packages/anndata/_io/h5ad.py in read_group(group)
>     531     if encoding_type:
> --> 532         EncodingVersions[encoding_type].check(
>     533             group.name, group.attrs["encoding-version"]
> 
> ~/miniconda3/envs/dynamo/lib/python3.7/enum.py in __getitem__(cls, name)
>     356     def __getitem__(cls, name):
> --> 357         return cls._member_map_[name]
>     358 
> 
> KeyError: 'dict'
> 
> During handling of the above exception, another exception occurred:
> 
> AnnDataReadError                          Traceback (most recent call last)
> /tmp/ipykernel_1760149/353394512.py in <module>
> ----> 1 adata = dyn.read('WT_WC_.h5ad')
> 
> ~/miniconda3/envs/dynamo/lib/python3.7/site-packages/anndata/_io/h5ad.py in read_h5ad(filename, backed, as_sparse, as_sparse_fmt, chunk_size)
>     424                 d[k] = read_dataframe(f[k])
>     425             else:  # Base case
> --> 426                 d[k] = read_attribute(f[k])
>     427 
>     428         d["raw"] = _read_raw(f, as_sparse, rdasp)
> 
> ~/miniconda3/envs/dynamo/lib/python3.7/functools.py in wrapper(*args, **kw)
>     838                             '1 positional argument')
>     839 
> --> 840         return dispatch(args[0].__class__)(*args, **kw)
>     841 
>     842     funcname = getattr(func, '__name__', 'singledispatch function')
> 
> ~/miniconda3/envs/dynamo/lib/python3.7/site-packages/anndata/_io/utils.py in func_wrapper(elem, *args, **kwargs)
>     161                 parent = _get_parent(elem)
>     162                 raise AnnDataReadError(
> --> 163                     f"Above error raised while reading key {elem.name!r} of "
>     164                     f"type {type(elem)} from {parent}."
>     165                 )
> 
> AnnDataReadError: Above error raised while reading key '/layers' of type <class 'h5py._hl.group.Group'> from /.
> `

Thank you very much!
XUE

**Comment by XUEbaogai0101** [comment]
I find some answers about the concatenated anndata, it seems that the format of an AnnData objects stored on disk is updated in the latest version.
https://github.com/scverse/anndata/issues/698#issue-1120878553

**Comment by Xiaojieqiu** [comment]
Hi @XUEbaogai0101 thanks for using dynamo. You are right, this is an anndata version issue. what is your anndata version? 

also have you tried to use `adata = dyn.read_loom('WT.loom')`?

**Comment by XUEbaogai0101** [comment]
Hi Dr.Qiu!@Xiaojieqiu 
Thank you for answering my question. My anndata version is 0.8.0.
I tried the use of read_loom, it worked. What a simple question, I am sorry for my sloppiness.
Thanks for your generous answer again.
