### ISSUE TITLE
Installation issue with most recent version

### ISSUE THREAD

**Issue by SJayYang** [aristoteleo/dynamo-release#334]
Hi,

I'm using the steps in the documentation to install the latest version of dynamo by cloning the repo and then installing using python. However, whenever I run dyn.get_all_dependencies_version(), I keep running into a KeyError for 'dynamo-release'. 

`Traceback (most recent call last):
  File "/Users/", line 2, in <module>
    dyn.get_all_dependencies_version()
  File "/Users/stanleyyang/.local/lib/python3.10/site-packages/dynamo/get_version.py", line 176, in 
get_all_dependencies_version
    _package = pkg_resources.working_set.by_key[_package_name]
KeyError: 'dynamo-release'`

How can I fix this? Downloading dynamo-release just using pip throws other errors for me. 

Whenever I install the latest release using pip, I get another set of errors whenever I call dyn.get_all_dependencies_version()

`Traceback (most recent call last):
 File "/Users/stanleyyang/", line 1, in <module>
    import dynamo as dyn
  File "/Users/stanleyyang/anaconda3/envs/dynamo/lib/python3.10/site-packages/dynamo/__init__.py", line 6, in <module>
    __version__ = get_version(__file__)
  File "/Users/stanleyyang/anaconda3/envs/dynamo/lib/python3.10/site-packages/get_version/__init__.py", line 280, in get_version
    raise NoVersionFound(Source.all, msg)
get_version.NoVersionFound: No version found:
- Directory name: name of directory “/Users/stanleyyang/anaconda3/envs/dynamo/lib/python3.10/site-packages” does not contain a valid version.
- VCS: could not find VCS from directory “/Users/stanleyyang/anaconda3/envs/dynamo/lib/python3.10/site-packages”.
- Package metadata: could not find distribution `“dynamo”.

**Comment by Xiaojieqiu** [comment]
This seems an issue from the recent `get_version` package 

have you tried installing via `pip install dynamo-release` or running `pip install . -e` in the folder of cloned copy? 

@dummyindex can you please take a close at this?

**Comment by Xiaojieqiu** [comment]
@SJayYang btw my latest commit comments get_version related code which should fix the issue for now: https://github.com/aristoteleo/dynamo-release/commit/e824590158612c2bb7eaf4ea688acb7ddf758c4e

**Comment by SJayYang** [comment]
Thanks! Should I install it using the normal pip3 distribution? Or how else should I try it?

**Comment by Xiaojieqiu** [comment]
pip install and setup install should both work

**Comment by Xiaojieqiu** [comment]
I have resolved the issue and release a new version 1.1.0 on PyPi too. 

Will close this issue for now. feel free to reopen if you find any additional issues
