### ISSUE TITLE
How to get the info in Table S1

### ISSUE THREAD

**Issue by pigraul** [aristoteleo/dynamo-release#340]
Hi Dr qiu,

How can I get effector-regulator pairs cross cell types？
I tried dynamo.vf.rank_jacobian_genes(mode='int') , it generated pairs in each cell type.

Thank you!

**Comment by dummyindex** [comment]
https://dynamo-release.readthedocs.io/en/latest/_autosummary/dynamo.vf.rank_jacobian_genes.html#dynamo.vf.rank_jacobian_genes

**Comment by pigraul** [comment]
Sorry, my description is not clear.

Now I can only get single cell type pair genes,

> Meg              Meg_values
>PLEK--FOXP1 5E-7

I  want to get pair genes between cell type,  such as "Mono_baso". 
I guess I should have the pairwise cell type information for some cells in the obs. Which API should I use to get the pairwise cell type information?

**Comment by Xiaojieqiu** [comment]
You need to manually select cells near the bifurcation point and then define those cells as `Mono_baso` or the like. Then you can perform differential geometry analyses for those cells.
