### ISSUE TITLE
How to find unknown Progenitor and terminal_cell_state? 

### ISSUE THREAD

**Issue by Roger-GOAT** [aristoteleo/dynamo-release#341]
Hi Dr.Qiu, wonderful tool!  After hearing your talk, I learn more about the dynamo. However, still some questions, here is the one.

In "ten_minutes_to_dynamo", it mentions "_Kinetic estimation of the conventional scRNA-seq and metabolic labeling based scRNA-seq is often tricky and has a lot pitfalls. Sometimes you may even observed undesired backward vector flow. You can evaluate the confidence of gene-wise velocity via:_" . 

I found I set different groups as Progenitor could get different streamline figures. If I am not sure which is progenitor, how to identify the progenitor and terminal_cell_state?  Could I let this argument blank and keep going next step then find them in dyn.pl.topography(adata)?

**Comment by Xiaojieqiu** [comment]
this option is used to correct RNA velocity when you do know the overall trend of your velocity flow but the RNA velocity from default pipeline has problems. Therefore, it is not useful in your case. 

In most cases, you can assume your velocity flow from default parameters works well and you can also judge whether it makes sense based on your biological understandings
