### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by FionaMoon** [aristoteleo/dynamo-release#342]
Hi dynamo group,
I met a problem after installation.
When I try to import dynamo in python3.9, I got the error like this.
```
   from KDEpy import FFTKDE
ModuleNotFoundError: No module named 'KDEpy'
```
I re-install dynamo several times from pip or git, but still got this error.
Thank you inadvance for you help.
Fiona

**Comment by FionaMoon** [comment]
Hi,
I install by this code from tutorial.
```
git clone https://github.com/aristoteleo/dynamo-release.git
cd dynamo-release/
python setup.py install --user
```
There is still some warnings after I installed KDEpy. I'm not sure what should I input after `warnings.warn( In:` .  Can I just ignore it?
```
>>> import dynamo as dyn
|-----> setting visualization default mode in dynamo. Your customized matplotlib settings might be overritten.
/home/***/.local/lib/python3.9/site-packages/nxviz-0.7.3-py3.9.egg/nxviz/__init__.py:18: UserWarning: 
nxviz has a new API! Version 0.7.3 onwards, the old class-based API is being
deprecated in favour of a new API focused on advancing a grammar of network
graphics. If your plotting code depends on the old API, please consider
pinning nxviz at version 0.7.3, as the new API will break your old code.

To check out the new API, please head over to the docs at
https://ericmjl.github.io/nxviz/ to learn more. We hope you enjoy using it!

(This deprecation message will go away in version 1.0.)

  warnings.warn(
In : 
In : dyn.get_all_dependencies_version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'dyn' is not defined
In : 
```

**Comment by xyn0813** [comment]
> >>> import dynamo as dyn
|-----> setting visualization default mode in dynamo. Your customized matplotlib settings might be overritten.
/home/***/.local/lib/python3.9/site-packages/nxviz-0.7.3-py3.9.egg/nxviz/__init__.py:18: UserWarning: 
nxviz has a new API! Version 0.7.3 onwards, the old class-based API is being
deprecated in favour of a new API focused on advancing a grammar of network
graphics. If your plotting code depends on the old API, please consider
pinning nxviz at version 0.7.3, as the new API will break your old code.

To check out the new API, please head over to the docs at
https://ericmjl.github.io/nxviz/ to learn more. We hope you enjoy using it!

(This deprecation message will go away in version 1.0.)

  warnings.warn(
In : 
In : dyn.get_all_dependencies_version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'dyn' is not defined
In : 


I've met the same question, and I tried to install dynamo by :

pip install dynamo-release &
pip install git+https://github.com/aristoteleo/dynamo-release

Is there a solution to this problem now？ @Xiaojieqiu

**Comment by dummyindex** [comment]
Hi @FionaMoon ,

It seems your dynamo is installed. You can ignore the warning message since it is from nxviz and we will force dynamo not to print it in the next version.

After you import dynamo, please try `import dynamo as dyn` again in your ipykernel prompt (`In : import dynamo as dyn` again), so you can use dynamo. Indeed it is weird that dynamo automatically goes to ipython kernel after importing and we will try fixing it in the future.
