### ISSUE TITLE
scNT-seq human hematopoiesis data not found 

### ISSUE THREAD

**Issue by zhuoqingzh** [aristoteleo/dynamo-release#347]
Hello Qiu,
Thank you for all the information provided and the very detailed tutorials.when i tried to follow the scNT-seq human hematopoiesis dynamics, I can't find scNT-seq human hematopoiesis data by dyn.sample_data.hematopoiesis_raw() or (https://pitt.box.com/v/hematopoiesis-processed).
![lADPJxf-xKDYjvrNBQDNAlA_592_1280](https://user-images.githubusercontent.com/102791707/167370375-af98006f-5484-4266-956f-0bef72b81199.jpg)
Could you please provide the links once again?

Thank you in advance!
Maria

**Comment by Xiaojieqiu** [comment]
thanks for reporting this. I will fix it shortly

**Comment by zhuoqingzh** [comment]
hi，Dr. Qiu
I still can't open the scNT-seq human hematopoiesis data。
Then，I build anndata with my own data, and the first step in preprocessing is to report an error ，
![image](https://user-images.githubusercontent.com/102791707/167594482-17fa07c7-64f1-45fe-82a3-61e7c1c096d4.png)
![image](https://user-images.githubusercontent.com/102791707/167595881-0177c6de-92d1-4a18-807c-87d55a9e11a2.png)
This is my own architecture on the anndata data structure。Is that part of the information missing? is adata.obs["batch"]?
![image](https://user-images.githubusercontent.com/102791707/167596254-5870e741-7f9d-44cb-bfad-0e09916d4f3a.png)
Thank you in advance!

**Comment by Xiaojieqiu** [comment]
@zhuoqingzh  can you try again after pulling my latest commit? you may need to use the vpn to access the data because dropbox service may be prohibited.
