### ISSUE TITLE
How confident_cell_velocities determine the streamline?

### ISSUE THREAD

**Issue by Roger-GOAT** [aristoteleo/dynamo-release#349]
Dear dynamo team and Dr.Qiu, thanks for the wonderful tool! As my previous issue [341](https://github.com/aristoteleo/dynamo-release/issues/341) mentioned, setting the lineage_dict significantly determines the streamline. And I found the https://dynamo-release.readthedocs.io/en/latest/notebooks/zebrafish.html is quite different from https://dynamo-release.readthedocs.io/en/latest/notebooks/tutorial_pancreatic_endocrinogenesis.html. 
Following is my code and results would you give some suggestions, thanks a lot!
```
adata = scv.utils.merge(ad, vel) (ad is the original data precessed by scanpy, vel is the original loom from velocity)
adata
AnnData object with n_obs × n_vars = 18034 × 1206
    obs: 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'pct_counts_hb', 'n_genes', 'n_counts', 'doublet_scores', 'predicted_doublets', 'doublet_info', 'batch', 'leiden', 'louvain', 'sample_batch', 'initial_size_spliced', 'initial_size_unspliced', 'initial_size'
    var: 'gene_ids', 'feature_types', 'mt', 'ribo', 'hb', 'n_cells_by_counts-day14', 'mean_counts-day14', 'pct_dropout_by_counts-day14', 'total_counts-day14', 'n_cells-day14', 'n_cells_by_counts-day2', 'mean_counts-day2', 'pct_dropout_by_counts-day2', 'total_counts-day2', 'n_cells-day2', 'n_cells_by_counts-day5', 'mean_counts-day5', 'pct_dropout_by_counts-day5', 'total_counts-day5', 'n_cells-day5', 'n_cells_by_counts-sham', 'mean_counts-sham', 'pct_dropout_by_counts-sham', 'total_counts-sham', 'n_cells-sham', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std', 'Accession', 'Chromosome', 'End', 'Start', 'Strand'
    uns: 'batch_colors', 'hvg', 'leiden', 'louvain', 'neighbors', 'pca', 'rank_genes_groups', 'umap', 'leiden_colors', 'louvain_colors'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    layers: 'matrix', 'ambiguous', 'spliced', 'unspliced'
    obsp: 'connectivities', 'distances'

del adata.layers['matrix']
adata.layers['X_unspliced']=adata.layers['unspliced']
adata.layers['X_spliced']=adata.layers['spliced']
dyn.pp.recipe_monocle(adata)
dyn.tl.dynamics(adata, model='stochastic', cores=10)
dyn.tl.gene_wise_confidence(adata, group='louvain',lineage_dict={'7':'6'})
dyn.tl.cell_velocities(adata, other_kernels_dict={'transform': 'sqrt'},basis='umap')
dyn.tl.cell_wise_confidence(adata)
dyn.tl.confident_cell_velocities(adata, group='louvain', lineage_dict={'7':'6'},basis='umap')
dyn.pl.streamline_plot(adata, color=['louvain'], basis='umap', show_legend='on data', show_arrowed_spines=True,
                       figsize=(6,4),pointsize=0.2)
dyn.vf.VectorField(adata, basis='umap', M=1000, pot_curl_div=True)
dyn.pl.topography(adata, basis='umap', background='white', color=['ntr', 'louvain'], 
                  streamline_color='black', show_legend='on data', frontier=True,figsize=(6,4),linewidth=3)
```
![image](https://user-images.githubusercontent.com/22614959/168409440-2a1e17a8-7364-49fb-b92f-d062f027477e.png)
![image](https://user-images.githubusercontent.com/22614959/168409451-bc2e8db8-1fa7-4e56-8d6f-02e7b6209e01.png)

```
adata = scv.utils.merge(ad, vel)
del adata.layers['matrix']
adata.layers['X_unspliced']=adata.layers['unspliced']
adata.layers['X_spliced']=adata.layers['spliced']
dyn.pp.recipe_monocle(adata, fg_kwargs={"shared_count": 20})
dyn.tl.dynamics(adata, model="stochastic")
dyn.tl.cell_velocities(adata, method="pearson", other_kernels_dict={"transform": "sqrt"})
dyn.tl.cell_velocities(adata, basis="pca")
dyn.pl.streamline_plot(adata, color=["louvain"], basis="umap", show_legend="on data", show_arrowed_spines=True)
progenitor = adata.obs_names[adata.obs.louvain.isin(["7"])]
dyn.tl.cell_velocities(adata, basis="pca")
dyn.vf.VectorField(adata, basis="pca", pot_curl_div=True)
dyn.vf.VectorField(adata, basis="umap", pot_curl_div=True)

dyn.vf.speed(adata, basis="pca")
dyn.vf.divergence(adata, basis="pca")
dyn.vf.acceleration(adata, basis="pca")
dyn.vf.curl(adata, basis="umap")
dyn.pl.topography(
    adata, basis="umap", background="white", color=["louvain"], streamline_color="black", show_legend="on data")
```
![image](https://user-images.githubusercontent.com/22614959/168409460-7ae170f8-00e6-4970-a486-e9cafebe1553.png)
![image](https://user-images.githubusercontent.com/22614959/168409468-9cb6a2f9-dc22-4f1f-947f-db6f4d79416d.png)

Which one should I use?
Thank you!
Best!

**Comment by Xiaojieqiu** [comment]
Dear @Roger-GOAT, as I explained in my previous issue, `confident_cell_velocities` is used to correct RNA velocity flow if you do know the broad RNA velocity direction and you found the velocity results from dynamo have problems. When you specify the `lineage_dict = {'7':'6'}` in `confident_cell_velocities`, you have enforce the RNA velocity flow moves from cluster 7 towards cluster 6. If you want to do, you need to make sure this overall flow makes sense. 

On the other hand, if using the default procedure to calculate RNA velocity, there is chance that your results will be problematic. In such cases, you will need to judge whether the results make any sense by looking at the trend of gene expression for markers. Progenitor markers should have overall high expression  in the beginning of the streamlines and mature lineage markers should have overall high expression from the end of the streamlines. 

Does this make sense?
