### ISSUE TITLE
If this tool published to cell, How the reviewer tested your tool? And they allowed you to publish this tool to cell with lots of problems?

### ISSUE THREAD

**Issue by Spartanzhao** [aristoteleo/dynamo-release#351]
When I am running this command:
adata = dyn.sample_data.DentateGyrus()
def dynamo_workflow(adata):
    adata = dyn.pp.recipe_monocle(adata)

    dyn.tl.dynamics(adata)

    dyn.tl.reduceDimension(adata)

    dyn.tl.cell_velocities(adata, calc_rnd_vel=True)

    dyn.vf.VectorField(adata, basis='umap')
dynamo_workflow(adata)
I got this:
|-----> recipe_monocle_keep_filtered_cells_key is None. Using default value from DynamoAdataConfig: recipe_monocle_keep_filtered_cells_key=True
|-----> recipe_monocle_keep_filtered_genes_key is None. Using default value from DynamoAdataConfig: recipe_monocle_keep_filtered_genes_key=True
|-----> recipe_monocle_keep_raw_layers_key is None. Using default value from DynamoAdataConfig: recipe_monocle_keep_raw_layers_key=True
|-----> apply Monocole recipe to adata...
|-----> <insert> pp to uns in AnnData Object.
|-----------> <insert> has_splicing to uns['pp'] in AnnData Object.
|-----------> <insert> has_labling to uns['pp'] in AnnData Object.
|-----------> <insert> splicing_labeling to uns['pp'] in AnnData Object.
|-----------> <insert> has_protein to uns['pp'] in AnnData Object.
|-----> ensure all cell and variable names unique.
|-----> ensure all data in different layers in csr sparse matrix format.
|-----> ensure all labeling data properly collapased
|-----------> <insert> tkey to uns['pp'] in AnnData Object.
|-----------> <insert> experiment_type to uns['pp'] in AnnData Object.
|-----? dynamo detects your data is size factor normalized and/or log transformed. If this is not right, plese set `normalized = False.
|-----> filtering cells...
|-----> <insert> pass_basic_filter to obs in AnnData Object.
|-----> 18213 cells passed basic filters.
|-----> filtering gene...
|-----> <insert> pass_basic_filter to var in AnnData Object.
|-----> 7960 genes passed basic filters.
|-----> calculating size factor...
|-----> selecting genes in layer: X, sort method: SVR...
|-----> <insert> frac to var in AnnData Object.
|-----> <insert> X_unspliced to layers in AnnData Object.
|-----> <insert> X_spliced to layers in AnnData Object.
|-----------> <insert> norm_method to uns['pp'] in AnnData Object.
|-----> applying PCA ...
|-----> <insert> pca_fit to uns in AnnData Object.
|-----> <insert> ntr to obs in AnnData Object.
|-----> <insert> ntr to var in AnnData Object.
|-----> cell cycle scoring...
|-----> computing cell phase...
|-----> [cell phase estimation] in progress: 100.0000%
|-----> [cell phase estimation] finished [210.0349s]
|-----> <insert> cell_cycle_phase to obs in AnnData Object.
|-----> <insert> cell_cycle_scores to obsm in AnnData Object.
|-----> [Cell Cycle Scores Estimation] in progress: 100.0000%
|-----> [Cell Cycle Scores Estimation] finished [3.4422s]
|-----> [recipe_monocle preprocess] in progress: 100.0000%
|-----> [recipe_monocle preprocess] finished [16.9428s]
|-----> dynamics_del_2nd_moments_key is None. Using default value from DynamoAdataConfig: dynamics_del_2nd_moments_key=False
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [34], in <cell line: 1>()
----> 1 dynamo_workflow(adata)

Input In [30], in dynamo_workflow(adata)
      1 def dynamo_workflow(adata):
      2     adata = dyn.pp.recipe_monocle(adata)
----> 4     dyn.tl.dynamics(adata)
      6     dyn.tl.reduceDimension(adata)
      8     dyn.tl.cell_velocities(adata, calc_rnd_vel=True)

File /opt/anaconda3/lib/python3.9/site-packages/dynamo/tools/dynamics.py:297, in dynamics(adata, filter_gene_mode, use_smoothed, assumption_mRNA, assumption_protein, model, est_method, NTR_vel, group, protein_names, concat_data, log_unnormalized, one_shot_method, fraction_for_deg, re_smooth, sanity_check, del_2nd_moments, cores, tkey, **est_kwargs)
     73 """Inclusive model of expression dynamics considers splicing, metabolic labeling and protein translation. It
     74 support learning high-dimensional velocity vector samples for droplet based (10x, inDrop, drop-seq, etc),
     75 scSLAM-seq, NASC-seq sci-fate, scNT-seq, scEU-seq, cite-seq or REAP-seq datasets.
   (...)
    291             log_unnormalized: Whether to log transform unnormalized data.
    292 """
    294 del_2nd_moments = DynamoAdataConfig.use_default_var_if_none(
    295     del_2nd_moments, DynamoAdataConfig.DYNAMICS_DEL_2ND_MOMENTS_KEY
    296 )
--> 297 if "pp" not in adata.uns_keys():
    298     raise ValueError(f"\nPlease run `dyn.pp.receipe_monocle(adata)` before running this function!")
    299 if tkey is None:

AttributeError: 'NoneType' object has no attribute 'uns_keys'

**Comment by Xiaojieqiu** [comment]
dyn.pp.recipe_monocle(adata) now by default return None by default. So if you replace , `adata = dyn.pp.recipe_monocle(adata)` with `dyn.pp.recipe_monocle(adata)`

**Comment by Xiaojieqiu** [comment]
I am assuming this issue is fixed and close it for now. feel free to ask other questions if you may find. Thanks

**Comment by hyjforesight** [comment]
Dynamo is fantastic. @Spartanzhao is so rude.看用户名应该是国人。
good luck with your job interview@Xiaojieqiu

**Comment by Xiaojieqiu** [comment]
thanks for the understanding!

**Comment by chansigit** [comment]
> Dynamo is fantastic. @Spartanzhao is rude. good luck with your job interview @Xiaojieqiu

agree.

@Spartanzhao  Zhao, Dynamo is not only a useful tool, but also a landscape perspective viewing the cells. Qiu and his team have been constantly improving the quality of this work. I believe It's your loss if you miss this work for minor issues.
