### ISSUE TITLE
cell_wise_confidence

### ISSUE THREAD

**Issue by chansigit** [aristoteleo/dynamo-release#355]
Hi developers,

I am using 1.1.0

in the tutorial of https://dynamo-release.readthedocs.io/en/latest/notebooks/zebrafish.html ,
there is a code segment:
`dyn.tl.cell_wise_confidence(adata, basis='pca')`

I ran it and got the following error

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_174073/1309032969.py in <module>
----> 1 dyn.tl.cell_wise_confidence(adata, basis='pca')
      2 dyn.tl.confident_cell_velocities(adata, group='ann0608', 
      3                                  lineage_dict={
      4                                     'αLP1.1': ['LTiP.1'],
      5                                     'αLP1.4': ['αLP1.6'] }
```

TypeError: cell_wise_confidence() got an unexpected keyword argument 'basis'

and I checked there is no basis parameter in the document:

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/18084613/169099684-d19784fc-63c6-4faa-8436-a4aff6c6471b.png">

should dynamo update the documents or tutorial?

Thank you for your great work.

**Comment by Xiaojieqiu** [comment]
Thanks for letting us know. We are working on updating the zebrafish notebook and otherwise. Unfortunately my time is very limited these days with 4 new papers, 2 grant writing, etc. Feel free to help us fix this and contribute to dynamo though. Highly appreciated!

**Comment by Xiaojieqiu** [comment]
@dummyindex when you got a chance, can you also help fix this bug?

**Comment by chansigit** [comment]
Thank you all. Already feel you have loads of new ideas from your docs. Looking forward to your future work.

**Comment by dummyindex** [comment]
This issue should have been fixed last week.
