### ISSUE TITLE
Can I specify ident_1, ident_2 for rank gene analysis methods like Seurat?

### ISSUE THREAD

**Issue by chansigit** [aristoteleo/dynamo-release#363]
Dear developers, 

In Seurat's differentially expressed gene analysis function FindMakers(), there are  "ident.1" "ident.2" parameters specifying group 1 vs group2. With these settings, users could flexibly compare customized two groups' differences without subsetting the anndata object. 

Can you add two parameters "ident_1" and "ident_2" to avoid the default "X vs rest" action in the rank_XXX functions including 
```
dyn.vf.rank_velocity_genes(adata, groups=‘Cell_type’)
dyn.vf.rank_divergence_genes(adata, groups=‘Cell_type’)
dyn.vf.rank_acceleration_genes(adata, groups=‘Cell_type’)
dyn.vf.rank_curvature_genes(adata, groups=‘Cell_type’)
dyn.vf.rank_jacobian_genes(adata, groups=‘Cell_type’)
```,
which would be far more convenient for users.

Many thanks

**Comment by Xiaojieqiu** [comment]
the ranking is not for differential analyses but just rank the differential geometry quantities in each cell group, etc. To perform differential analyses of velocity, acceleration and curvature, you will need to use the marker detection related code: 

[tl.find_group_markers](https://dynamo-release.readthedocs.io/en/latest/_autosummary/dynamo.tl.find_group_markers.html#dynamo.tl.find_group_markers)

[tl.two_groups_degs](https://dynamo-release.readthedocs.io/en/latest/_autosummary/dynamo.tl.two_groups_degs.html#dynamo.tl.two_groups_degs)(adata, genes, layer, ...)

[tl.glm_degs](https://dynamo-release.readthedocs.io/en/latest/_autosummary/dynamo.tl.glm_degs.html#dynamo.tl.glm_degs)(adata[, X_data, genes, layer, ...])

See more at `Markers and differential expressions` section in our API page. 

Notice that velocity, acceleration and curvature are matrices for each gene in each cell and thus you can use conventional differential analyses for these quantities. but of course you can also calculate magnitude of them for each cell. 

Jacobian is a tensor (it calculates a gene by gene matrix for each cell). Divergence, etc. are scale values for each cell
