### ISSUE TITLE
installing issue with the dynamo-release=1.10

### ISSUE THREAD

**Issue by aaronwolf1995** [aristoteleo/dynamo-release#366]
Hi,
I'm using dynamo in a python=3.9 environment with jupyter notebook. My dynamo is 1.1.0 through pip install dynamo-release.

However, whenever I run dyn.get_all_dependencies_version(), I keep running into a KeyError for 'dynamo-release'.

I have read this issue: 
[https://github.com/aristoteleo/dynamo-release/issues/334](url)

The eror is as following: 
KeyError                                  Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 dyn.get_all_dependencies_version()

File ~/.local/lib/python3.9/site-packages/dynamo/get_version.py:189, in get_all_dependencies_version(display)
    186 from IPython.display import display
    188 _package_name = "dynamo-release"
--> 189 _package = pkg_resources.working_set.by_key[_package_name]
    191 all_dependencies = [str(r).split(">")[0] for r in _package.requires()]  # retrieve deps from setup.py
    192 all_dependencies.sort(reverse=True)

KeyError: 'dynamo-release'

My environment is :
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
asttokens                 2.0.5              pyhd3eb1b0_0    anaconda
backcall                  0.2.0              pyhd3eb1b0_0    anaconda
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.4.26            h06a4308_0    anaconda
cfgv                      3.3.1                    pypi_0    pypi
decorator                 5.1.1              pyhd3eb1b0_0    anaconda
distlib                   0.3.4                    pypi_0    pypi
dynamo-release            1.1.0                    pypi_0    pypi
executing                 0.8.3              pyhd3eb1b0_0    anaconda
filelock                  3.7.0                    pypi_0    pypi
identify                  2.5.1                    pypi_0    pypi
ipython                   8.2.0            py39h06a4308_0    anaconda
jedi                      0.18.1           py39h06a4308_1    anaconda
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.12               h166bdaf_0    conda-forge
matplotlib-inline         0.1.2              pyhd3eb1b0_2    anaconda
ncurses                   6.3                  h27087fc_1    conda-forge
nodeenv                   1.6.0                    pypi_0    pypi
openssl                   3.0.3                h166bdaf_0    conda-forge
parso                     0.8.3              pyhd3eb1b0_0    anaconda
pexpect                   4.8.0              pyhd3eb1b0_3    anaconda
pickleshare               0.7.5           pyhd3eb1b0_1003    anaconda
pip                       22.1.1             pyhd8ed1ab_0    conda-forge
platformdirs              2.5.2                    pypi_0    pypi
pre-commit                2.19.0                   pypi_0    pypi
prompt-toolkit            3.0.20             pyhd3eb1b0_0    anaconda
ptyprocess                0.7.0              pyhd3eb1b0_2    anaconda
pure_eval                 0.2.2              pyhd3eb1b0_0    anaconda
pygments                  2.11.2             pyhd3eb1b0_0    anaconda
python                    3.9.13          h2660328_0_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
setuptools                62.3.2           py39hf3d152e_0    conda-forge
six                       1.16.0             pyhd3eb1b0_1    anaconda
sqlite                    3.38.5               h4ff8645_0    conda-forge
stack_data                0.2.0              pyhd3eb1b0_0    anaconda
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2                   pypi_0    pypi
traitlets                 5.1.1              pyhd3eb1b0_0    anaconda
tzdata                    2022a                h191b570_0    conda-forge
virtualenv                20.14.1                  pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0    anaconda
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.12               h166bdaf_0    conda-forge

**Comment by Xiaojieqiu** [comment]
dear @aaronwolf1995 thanks for using dynamo. this is a known error but it doesn't really affect any dynamo analyses. We will try to fix this soon

**Comment by aaronwolf1995** [comment]
Ok, thanks!
