### ISSUE TITLE
Animatation _ attribute error

### ISSUE THREAD

**Issue by lgmp315** [aristoteleo/dynamo-release#368]
![error1](https://user-images.githubusercontent.com/98027401/173782162-acedf43c-7ebd-4ecb-a63b-0a22015925f4.png)
![error2](https://user-images.githubusercontent.com/98027401/173782189-542818e7-d118-40fa-b72d-3e45bc882f70.png)

Dear Qiu：
        Im running the tutorial “Conventional SCRNA-seq: Zebrafish pigmentation”.
        and run into a attribute error in the section of **Animatation**.
        
        thanks in advance

**Comment by Xiaojieqiu** [comment]
@lgmp315 sorry for the late reply, what matplotlib version are you using? have you tried using `3.4.3`

**Comment by elfofmaxwell** [comment]
Hello @lgmp315 , thanks a lot for reporting the bug!  The problem would be fixed in next release very soon.
