### ISSUE TITLE
Is it possible to use all threads when generating animation?

### ISSUE THREAD

**Issue by hyjforesight** [aristoteleo/dynamo-release#378]
Hello Dynamo,
The system only uses 1 thread when encoding the animation. Is it possible to use all threads when generating animation?
Thanks!
Best,
YJ

```python
%%capture
instance = dyn.mv.StreamFuncAnim(adata=adata, basis='umap', n_steps= 100, color='Cell_type', ax=ax)
matplotlib.rcParams['animation.embed_limit'] = 2**128
anim = animation.FuncAnimation(instance.fig, instance.update, init_func=instance.init_background, frames=100, interval=100, blit=True)
writervideo = animation.FFMpegWriter(fps=100)
anim.save("C:/Users/hyjfo/Documents/animation.avi", writer=writervideo)
```

**Comment by Xiaojieqiu** [comment]
Hi @hyjforesight I don't think it is possible to use multiple threads to create the animation because animation itself is linear and sequential over time. However, to make it animation to be generated much faster, use less cells when predicting the cell trajectories, such as: 

```
dyn.pd.fate(adata, basis='umap', init_cells=progenitor[:10], interpolation_num=100,  direction='forward',
   inverse_transform=False, average=False, cores=3)
```

**Comment by hyjforesight** [comment]
Thanks @Xiaojieqiu . I also checked `matplotlib`. They didn't provide multithread encoding in `anim.save()` until now.
