### ISSUE TITLE
What is the meaning of M=1000 in dyn.vf.VectorField()?

### ISSUE THREAD

**Issue by hyjforesight** [aristoteleo/dynamo-release#379]
Hello Dynamo,
I'm wondering what the meaning of `M=1000` is for `dyn.vf.VectorField(adata, basis='umap', pot_curl_div=True, cores=8, M=1000)`, because it's not mentioned in the document.
Is is similar to `n=750` in `dyn.vf.topography(adata, basis='umap', n=750)`, which is the number of cells for calculating the fixed points?
Thanks!
Best,
YJ

**Comment by Xiaojieqiu** [comment]
Hey @hyjforesight M is the basis function
```The number of basis functions to approximate the vector field.```

Dynamo uses sparseVFC to learn the vector field, you can find all its parameters via: `?dyn.vf.SparseVFC`

You can also pass other arguments, such as `theta = 0.75,` to the `dyn.vf.VectorField `function

**Comment by hyjforesight** [comment]
Thanks @Xiaojieqiu . I'm reading the documents of `dyn.vf.SparseVFC()`.
