### ISSUE TITLE
Is it necessary to run dyn.vf.topography() after dyn.vf.VectorField() and before dyn.pl.topography()?

### ISSUE THREAD

**Issue by hyjforesight** [aristoteleo/dynamo-release#380]
Hello Dynamo,
I'm a little confused about the usage of dyn.vf.topography().
In the `conventional scRNA-seq Zebrafish pigmentation` tutorial, vector field was reconstructed on UMAP first, then visualized by vector field topology, like below coding. No `dyn.vf.topography()` was done after `dyn.vf.VectorField()` and before `dyn.pl.topography()`.
``` python
dyn.vf.VectorField(adata, basis='umap', pot_curl_div=True, cores=8, M=1000)
dyn.pl.topography(adata, basis='umap', fps_basis='umap', color=['ntr', 'Cell_type'], pointsize=0.5, show_legend='right margin', streamline_alpha=1, save_show_or_return='return', frontier=False)
```
However, in the `scNT-seq human hematopoiesis - Molecular mechanism of megakaryocytes` tutorial, `adata`, whose vector field has already been reconstructed was loaded. Then, `dyn.vf.topography()` was done before `dyn.pl.topography()`, like below coding.
```python
adata = dyn.sample_data.hematopoiesis()   # dyn.vf.VectorField() was already done.
dyn.vf.topography(adata, basis='umap', n=750)
dyn.pl.topography(adata, basis='umap', fps_basis='umap', color=['ntr', 'cell_type'], cmap=None, pointsize=None, show_legend='right margin', streamline_alpha=1, markersize=200, save_show_or_return='return', frontier=False)
```
Is it necessary to run dyn.vf.topography() after dyn.vf.VectorField() and before dyn.pl.topography()?
My understanding is that, `dyn.vf.topography()` is just for manipulating the number of fixed points we need. It don't have to be run every time after `dyn.vf.VectorField()` and before `dyn.pl.topography()`. Am I right?

Thanks!
Best,
YJ

**Comment by Xiaojieqiu** [comment]
By default, when you don't run `dyn.vf.topography` before you run `dyn.pl.topography`, `dyn.vf.topography` will be called internally in `dyn.pl.topograph`. In addition, in generally we can only map topograph on umap based vector field (or 2D vector field because identifying attractor, saddle points, etc. in high dimensional space is challenging). Furthermore, you can also pass `map_topography = True` to the `dyn.vf.VectorField`. Please read the documentations of these functions to understand more.

**Comment by hyjforesight** [comment]
Thanks @Xiaojieqiu. Now I only use `dyn.vf.topography()` for adjusting the number of fixed points I want. Is it right?

**Comment by Xiaojieqiu** [comment]
yes, that is the right way to do so

**Comment by hyjforesight** [comment]
Thanks @Xiaojieqiu !
