### ISSUE TITLE
How are the values of plt.xlim() and plt.ylim() determined when plotting vector field pseudotime by cosine potential?

### ISSUE THREAD

**Issue by hyjforesight** [aristoteleo/dynamo-release#381]
Hello Dynamo,
I was quite confused about how the values of `plt.xlim()` and `plt.ylim()` are determined when plotting vector field pseudotime by cosine potential in tutorial  `Differential geometry - scNT-seq human hematopoiesis - Molecular mechanism of megakaryocytes`?
The coding is as below, but I didn't get the point of the values of `plt.xlim()` and `plt.ylim()`. Why are they `plt.xlim(0.0, 0.008)` and `plt.ylim(0, 12)`. Is `plt.xlim()` determined by `cosine` values? But the max values of `cosine` is 0.05257646.
Thanks!
Best,
YJ

```python
df["cosine"] = potential_cosine[valid_indices]
df["fp"] = potential_fp[valid_indices]
sns.displot(
    data=df,
    x="cosine",
    hue="cell_type",
    kind="ecdf",
    stat="count",
    palette=dynamo_color_dict,
    height=2.5,
    aspect=95.5 / 88.8,
)
plt.xlim(0.0, 0.008)
plt.ylim(0, 12)
plt.xlabel("vector field pseudotime")
```
![image](https://user-images.githubusercontent.com/75048821/179385319-9c5240a3-8d19-45e5-950c-643ddb2021e3.png)

**Comment by Xiaojieqiu** [comment]
Basically we want to only show that Meg lineage appear earlier than others. therefore, we only need to show the start of the vector field pseudotime (the `xlim` is thus set to be `0 to 0.008`). Similary, we don't need to show the full range of the cell count (and thus cut `ylim` between `0 to 12`)

**Comment by hyjforesight** [comment]
Hello @Xiaojieqiu , thanks for the response. Now I get the point.
