### ISSUE TITLE
Issue of import  dynamo

### ISSUE THREAD

**Issue by wulc21** [aristoteleo/dynamo-release#382]
Hi dear professor,
After finishing install of dynamo on my MAC book,   I failed to import dynamo at the first step,  could you help me solve the problem, thank you very much.

######  #####
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
**>>> import dynamo as dyn**
|-----> setting visualization default mode in dynamo. Your customized matplotlib settings might be overritten.
/Users/zhuiyue718/opt/anaconda3/lib/python3.8/site-packages/nxviz/__init__.py:18: UserWarning: 
nxviz has a new API! Version 0.7.3 onwards, the old class-based API is being
deprecated in favour of a new API focused on advancing a grammar of network
graphics. If your plotting code depends on the old API, please consider
pinning nxviz at version 0.7.3, as the new API will break your old code.

To check out the new API, please head over to the docs at
https://ericmjl.github.io/nxviz/ to learn more. We hope you enjoy using it!

(This deprecation message will go away in version 1.0.)

  **warnings.warn(
In :**

**Comment by Xiaojieqiu** [comment]
did you import dynamo successfully? your warning information posted comes from nxviz and should not affect the importing

**Comment by wulc21** [comment]
Thanks for your kind reply.

I tried several times, but I still failed to import dynamo.

 I also tried to import  nxviz before import dynamo,  the process stoped at "In:"

########
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import nxviz
/Users/zhuiyue718/opt/anaconda3/lib/python3.8/site-packages/nxviz/__init__.py:18: UserWarning: 
nxviz has a new API! Version 0.7.3 onwards, the old class-based API is being
deprecated in favour of a new API focused on advancing a grammar of network
graphics. If your plotting code depends on the old API, please consider
pinning nxviz at version 0.7.3, as the new API will break your old code.

To check out the new API, please head over to the docs at
https://ericmjl.github.io/nxviz/ to learn more. We hope you enjoy using it!

(This deprecation message will go away in version 1.0.)

  warnings.warn(
>>> **import dynamo as dys
|-----> setting visualization default mode in dynamo. Your customized matplotlib settings might be overritten.
In : 
In : 
In :**

**Comment by Xiaojieqiu** [comment]
it looks to me you imported it successfully already. 
what do you mean by stopped at ln? can you run something like `adata = dyn.sample_data.pancreatic_endocrinogenesis()` when you are at that state?

**Comment by wulc21** [comment]
Thank you very much.  I mean  the command line stop at " In:" , I could not start run the new command line without  ">>> "

#############
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
**>>> import nxviz**
/Users/zhuiyue718/opt/anaconda3/lib/python3.8/site-packages/nxviz/__init__.py:18: UserWarning: 
nxviz has a new API! Version 0.7.3 onwards, the old class-based API is being
deprecated in favour of a new API focused on advancing a grammar of network
graphics. If your plotting code depends on the old API, please consider
pinning nxviz at version 0.7.3, as the new API will break your old code.

To check out the new API, please head over to the docs at
https://ericmjl.github.io/nxviz/ to learn more. We hope you enjoy using it!

(This deprecation message will go away in version 1.0.)

  warnings.warn(
  >>> **import dynamo as dys**
|-----> setting visualization default mode in dynamo. Your customized matplotlib settings might be overritten.
In : 
In : 
In : **adata = dyn.sample_data.pancreatic_endocrinogenesis()**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'dyn' is not defined
In : 
In : 
In :

**Comment by Xiaojieqiu** [comment]
this doesn't make any sense.This is  the screenshot on my end when I use python 3.7: 
<img width="1294" alt="Screen Shot 2022-07-19 at 11 45 33 PM" src="https://user-images.githubusercontent.com/7456281/179892366-ca7308cb-864f-4855-82ce-d568968e4c5c.png">

Also, please consider discussing with anyone in your lab who has better knowledge in python.

**Comment by Xiaojieqiu** [comment]
please also consider install via github, see: 
![image](https://user-images.githubusercontent.com/7456281/179893754-faa30339-5012-47f6-9279-c483a7b62806.png)

See our installation instruction here: 
https://dynamo-release.readthedocs.io/en/latest/ten_minutes_to_dynamo.html#how-to-install
