### ISSUE TITLE
OMP: Info #271: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

### ISSUE THREAD

**Issue by anshu957** [aristoteleo/dynamo-release#386]
The dynamo is working perfectly on my Intel Mac but on M1 (ARM based) mac, upon calling `dyn.tl.dynamics(adata)`, it throws the following error:
`OMP: Info #271: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.` Upon searching a little bit, it seems like a `numba` issue. 

* dynamo version: 1.1.0
* Mac OS: Monterey 12.4
* Mac Arch: M1

**Comment by Xiaojieqiu** [comment]
thanks for reporting this error. If it is a numba issue, it may be upstream of dynamo. I don't have a M1 system so it is difficult to test this for you. But have you tried installing a different version of numba and does that fix the bug?

**Comment by anshu957** [comment]
Okay, I've an update to this issue. After trying multiple things, I reinstalled anaconda and upgraded `numba` from `0.54.1` to `0.56.2` and it seems to do the trick. Now it just throws the warning `OMP: Info #271` instead of halting the execution. 

@Xiaojieqiu : closing this issue for now.
