### ISSUE TITLE
"cell" parameter for In silico perturbation

### ISSUE THREAD

**Issue by Mnew1288** [aristoteleo/dynamo-release#393]
Hi Xiaojie,

Could you show me how to set the "cell" parameter so I can do In silico perturbation in selected cell populations (for example, cluster1)?

Thanks!

**Comment by Xiaojieqiu** [comment]
thanks for the question, the `j_delta_x_perturbation` key from the resultant adata object include perturbation effect for all cells. you can manually for now set the values for cells not belong to cluster1 to be 0. Meanwhile, we will add a new argument for this later
