### ISSUE TITLE
dynamo downloads wrong datasets for scNT_seq

### ISSUE THREAD

**Issue by rorymaizels** [aristoteleo/dynamo-release#400]
Hi, very quick issue:

I have dynamo version 1.1.0, and if I run either `dyn.sample_data.scNT_seq_neuron_labeling()` or `dyn.sample_data.scNT_seq_neuron_splicing()` it seems to download the zebrafish dataset instead. 

Maybe the files have been accidentally updated to be the wrong dataset?

**Comment by Xiaojieqiu** [comment]
Thanks @rorymaizels for reporting this bug! 

My latest commit should fix the bug. 

For the neural activity data, you will need to use the activity genes for the velocity analyses. I have added the `adata.var['activity_genes']` info. Or you find the gene list here: https://www.dropbox.com/s/h2rtmj3et098xba/0408_grp_info.txt?dl=0

let me know if you have any additional questions!
