### ISSUE TITLE
UMAP for Hematopoiesis

### ISSUE THREAD

**Issue by StillJosh** [aristoteleo/dynamo-release#410]
Hi everyone,

In the tutorial for the hematopoiesis dataset, the data is supplied raw with the exception for the UMAP coordinates. We wanted to kindly ask, if you could supply us with the parameters that were used to generate this UMAP. I know that the UMAP generation is stochastic and that we could therefore not reproduce the exact coordinates, but it would still help us a lot!

Thank you very much!

**Comment by Xiaojieqiu** [comment]
@StillJosh we are trying to standardize the issue report, feature requests and discussion related issues to improve the user experience and ease the developer's life. For your specific question, you consider posting it in the discussion channel https://github.com/aristoteleo/dynamo-release/discussions or post as a tutorial related issue. 

the quick answer is that we used a few customized steps to get to that good looking umap. Once you adjust your questions, we can then help you there

**Comment by StillJosh** [comment]
Of course! Thanks for the hint
