### ISSUE TITLE
Why the weights of same regulator and target are different in Construct and visualize cell-type specific regulatory networks analysis

### ISSUE THREAD

**Issue by kzxkzx** [aristoteleo/dynamo-release#425]
I performed the construct and visualize cell-type specific regulatory network analysis using my own data, but I found same regulator and target have different weights, what is the reason for this? And what value should I choose for further analysis. By the way, I set the parameter abs=False when I run dyn.vf.rank_jacobian_genes

**Comment by kzxkzx** [comment]
![微信图片_20221017224849](https://user-images.githubusercontent.com/51022196/196209174-29453c07-6a4b-4532-9807-6f3fbb9fdf13.png)

**Comment by Xiaojieqiu** [comment]
Thanks for using dynamo. Hmm, that is odd. I will squeeze some time to figure this out and provide the solution soon!
