### ISSUE TITLE
the input data must run with scVelo before？

### ISSUE THREAD

**Issue by yanglq-bioinfo** [aristoteleo/dynamo-release#429]
Hi，
my scRNA data was analysised by seurat and translated it to h5ad format. after I load the data by dyn.read, I found my format is different from your examples. 

my adata is this:
`AnnData object with n_obs × n_vars = 9772 × 17325
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'RNA_snn_res.0.4', 'seurat_clusters', 'celltype'
    var: 'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'vst.variable'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs' `

and your example data like this
`AnnData object with n_obs × n_vars = 4181 × 16940
    obs: 'split_id', 'sample', 'Size_Factor', 'condition', 'Cluster', 'Cell_type', 'umap_1', 'umap_2', 'batch', 'nGenes', 'nCounts', 'pMito', 'use_for_pca', 'spliced_Size_Factor', 'initial_spliced_cell_size', 'unspliced_Size_Factor', 'initial_unspliced_cell_size', 'initial_cell_size', 'ntr'
    var: 'pass_basic_filter', 'score', 'log_m', 'log_cv', 'use_for_pca', 'ntr'
    uns: 'velocyto_SVR', 'pp_norm_method', 'PCs', 'explained_variance_ratio_', 'pca_fit', 'feature_selection'
    obsm: 'X_pca', 'X'
    layers: 'spliced', 'unspliced', 'X_spliced', 'X_unspliced'`

I don't have layers of spliced and unspliced.it may be results from scVelo?

**Comment by Xiaojieqiu** [comment]
please use kb-python (https://github.com/pachterlab/kb_python) or other tools to generate the spliced and unspliced data layers before you running any RNA velocity and vector field analyses. Dynamo doesn't require others to run RNA velocity analyses.
