### ISSUE TITLE
Need support for newly published .h5ad data generated with anndata>0.8.0

### ISSUE THREAD

**Issue by Jinerhal** [aristoteleo/dynamo-release#432]
Dynamo is currently restricting `anndata==0.7.5`. Since `anndata` has come to a major update of `>0.8.0`, the previous `0.7.5` can not load newly published data generated with `anndata>0.8.0`. Could you please help check if dynamo could work with `anndata>0.8.0`, and update the requirements? Thanks a lot.

**Comment by Xiaojieqiu** [comment]
Thanks Zehua @Jinerhal this has been fixed in our dynamo 1.2.0
