### ISSUE TITLE
Interpretation of perturbation `delta_Y` matrix

### ISSUE THREAD

**Issue by yanwu2014** [aristoteleo/dynamo-release#436]
Thanks for the great package! I was wondering how I should interpret the `delta_Y` matrix generated by multiplying the jacobian with the perturbed expression matrix. For example, if I wanted to get the absolute perturbed expression values should it be `Y_pert = delta_Y + Y` or `Y_pert = delta_Y * Y` where `Y_pert` represents the perturbed expression values and `Y` is the unperturbed expression

**Comment by Xiaojieqiu** [comment]
thanks for your interests in our tool @yanwu2014. The gene expression after the perturbation is `Y_pert = delta_Y + Y`. However, please note that Jacobian calculation is local and the delta_Y = J \delta X is instant. You can multiple a factor for `\delta x` to observe more apparent perturbation outcomes. 

Hope this helps!

**Comment by yanwu2014** [comment]
Thanks! So just to clarify to observe stronger perturbation effects I should multiply `delta_Y` by a constant, i.e. `10`?

**Comment by Xiaojieqiu** [comment]
that is right, or you can make delta_Y to be big (like 100 or -100 for activation or suppression respectively)

**Comment by yanwu2014** [comment]
Perfect thanks so much!
