### ISSUE TITLE
Using pre-computed dimensional reductions/embeddings

### ISSUE THREAD

**Issue by yanwu2014** [aristoteleo/dynamo-release#437]
Is there any way to use dynamo with pre-computed dimensional reductions (i.e. using scVI)? If so, how would you recommend inputting these pre-computed reductions into dynamo?

**Comment by Xiaojieqiu** [comment]
Hey @Yan, you can use adata.obsm['X_other_embedding'] = other_embedding.

Thanks,
Xiaojie

**Comment by yanwu2014** [comment]
Sorry to clarify it seems like some functions (i.e. `dynamo.tl.cell_velocities`) can take a custom dimensional reduction while others (i.e. `dynamo.tl.reduceDimension`, `dynamo.pd.perturbation`) require the `basis` parameter to be one of a pre-specified list

For example if I try to run `dynamo.pd.perturbation` with `basis='scanvi'` I get the following error:
```
Vector field function VecFld_pca is not included in the adata object! Try firstly running dyn.vf.VectorField(adata, basis='pca')
```

even though I've run `dyn.vf.VectorField(adata, basis='scanvi')`

Are there specific functions that require PCA as to be the basis?

**Comment by yanwu2014** [comment]
Ah makes sense, thanks for clarifying! I think with models like scVI and SCANVI you can project back to the original space, however you would need to supply the trained model to do so

**Comment by wangjiawen2013** [comment]
+1, I feel scVI performs better than PCA

**Comment by christophechu** [comment]
using scVI or harmony PCA to complete acceleration and curvature
