### ISSUE TITLE
What is the meaning of "M_s" and "velocity_S"?

### ISSUE THREAD

**Issue by baoyulinn** [aristoteleo/dynamo-release#442]
In the tutorial dataset of Zebrafish pigmentation,  using the function (dyn.pl.phase_portraits), spliced/unspliced expression values can be got. However, i want to know the excise meaning of "M_s" and "velocity_S"  in the following pictures?
<img width="787" alt="image" src="https://user-images.githubusercontent.com/111479371/217131510-13054cc3-2a30-4a73-8a24-b4b913eda268.png">

I apologize for taking up your valuable time and I look forward to hearing from you!

**Comment by Xiaojieqiu** [comment]
Hi @baoyulinn thanks for your interests in dynamo. The `M_s` means the first moment (M) of spliced RNA (S) or locally smoothed spliced RNA expression. `velocity_S` is the calculated RNA velocity velocity for the smoothed RNA expression. 

Hope these helps!
