### ISSUE TITLE
UMAP space or PCA space

### ISSUE THREAD

**Issue by wangjiawen2013** [aristoteleo/dynamo-release#447]
Hi,
 thanks for this great work and it really helps me a lot.

I am tring to follow dynamo tutorial https://test-forkedver.readthedocs.io/projects/tutorials/en/latest/zebrafish.html, however, I cannot reproduce some results, such as dyn.pl.umap(adata,  color='umap_ddhodge_potential', frontier=True) and dyn.pl.scatters(adata, x=np.repeat('umap_ddhodge_potential', 9), pointsize=0.25, alpha=0.8, y=fig3_si5, layer='X_spliced', color='Cell_type', ncols=3, background='white', figsize=(7, 4)). Then I use pca_ddhodge_potential instead, this time the results are similar to the tutorial！

All the code in dynamo differential tutorial used PCA space (https://test-forkedver.readthedocs.io/projects/tutorials/en/latest/Differential_geometry.html). I feel that the results of PCA space are more reasonable. Considering that some functions use UMAP space as the default setting, which one should we use ?

**Comment by Xiaojieqiu** [comment]
Thanks again! We hired software engineers to help us with updating the package, tutorials, etc. Hopefully they can help us fix these issues soon.  

re differential geometry, once you calculate it in pca space, you can get gene wise acceleration, curvature, divergences, etc by projecting the data back to original gene expression space. You can not do that in umap space. However, you can calculate the norm (length of the vector) of these quantities in both umap and pca space. the norm on umap space could be more clear.
