### ISSUE TITLE
cell wise vector color

### ISSUE THREAD

**Issue by wangjiawen2013** [aristoteleo/dynamo-release#448]
Hi, 
Here is the figure in dynamo tutorial:
![zebrafish_24_1](https://user-images.githubusercontent.com/29703450/218634884-89cd5a17-f36e-4eec-99ab-ed867166461d.png)

and this is the same one I plot using dyn.pl.cell_wise_vectors(adata, color=['Cell_type'], basis='umap', show_legend='on data', quiver_length=6, quiver_size=6, pointsize=0.1, show_arrowed_spines=False), which is copyed from zebrafish pigmentation tutorial:

![cell_wise](https://user-images.githubusercontent.com/29703450/218634946-1ced164c-48a8-4874-b652-e8e1b0eefba9.png)

It seems that the color cannot be displayed properly, all the arrows are in the same color. So how to adjust the color and alpha?

**Comment by Xiaojieqiu** [comment]
Thanks for reporting this bug, we will look into this and fix it soon.

**Comment by wangjiawen2013** [comment]
Hi, has it been fixed now ?

**Comment by Xiaojieqiu** [comment]
@Sichao25 can you please also look into this error please?
