### ISSUE TITLE
RNA velocity measure

### ISSUE THREAD

**Issue by wangjiawen2013** [aristoteleo/dynamo-release#450]
Hi,
What's the measure metrics of RNA velocity and acceleration ? mol/L/seconds (mol/L*s) or something else ?

**Comment by Xiaojieqiu** [comment]
for metabolic labeling data, the velocity has a unit of (normalized RNA counts per cells ) / hours and for acceleration it is (normalized RNA counts per cells ) / hours^2. 

For the conventional RNA velocity data, the velocity is scaled to the splicing rate for each gene. You can find more details in the method section of our dynamo paper.

**Comment by wangjiawen2013** [comment]
Here is the description about RNA velocity for dynamo paper:
![image](https://user-images.githubusercontent.com/29703450/219246456-d458c0ca-b1a9-422f-b445-356e9913db65.png)
And this is fig.3E:
![image](https://user-images.githubusercontent.com/29703450/219246829-aebcba97-1dcb-4b1e-bfa8-7fa62f61075f.png)
It was said that "u and s are the copies of unspliced and spliced RNA for a particular gene in a cell, respectively". In fig.3E

**Comment by Xiaojieqiu** [comment]
they are normalized, and locally smoothed. Otherwise they will be integers. The normalization and locally smoothing are necessary preprocessing steps to deal with high noisy and dropout single cell data.
