### ISSUE TITLE
Is the data in each column of the matrix in the calculation of the Gini coefficient really sorted?

### ISSUE THREAD

**Issue by yujcccc** [aristoteleo/dynamo-release#451]
The Gini coefficient is smaller than I expected
![image](https://user-images.githubusercontent.com/110595598/220027601-f875848e-0f53-4bae-9bde-de226d53cb2a.png)

You can see that each column of data in CM is not sorted
![image](https://user-images.githubusercontent.com/110595598/220028034-748a6c41-c25f-4d1c-b2ab-a0bb4186d7d6.png)

**Comment by Xiaojieqiu** [comment]
thanks for reporting this bug @yujcccc 

looks like we need to use ` np.sort(cur_cm, axis=0)`?

**Comment by Ukyeon** [comment]
Thank you, @yujcccc, for bringing this bug to our attention!

The bug will be addressed by #441 as Xiaojie`s guidance.
For the test results, please refer to the link below.
https://drive.google.com/file/d/1D9gYOZ8DuZ20eRT9IQYXZrBRbgZviY2R/view?usp=share_link

Thank you for your attention to this matter. Please let us know if you have any further questions or concerns.

**Comment by yujcccc** [comment]
It seems that there will be bugs in the dispersion fitting. I seem to understand the cause of the error according to the URL of the document but I don’t know how to solve it.

**Comment by Xiaojieqiu** [comment]
thanks @yujcccc can you please describe this other issue in further details? I am sure I understand what you are saying
