### ISSUE TITLE
import dynamo warnings.warn( in:

### ISSUE THREAD

**Issue by QianChwnLyn** [aristoteleo/dynamo-release#452]
Hello, when I import dynamo in python of Linux, the following problems always arise. Any command I type is useless. I import dynamo in the terminal python of my mac, and this issue also occurs. How can you solve it?
![image](https://user-images.githubusercontent.com/102777768/220119771-f6e9fb98-a6d3-45e7-ae96-f0af37d9455d.png)
<img width="930" alt="f09191b2c6ab87abc44ec0d3b026c3c" src="https://user-images.githubusercontent.com/102777768/220120553-17c62926-d36a-4eb3-a5e1-e418a0e09d57.png">

**Comment by Xiaojieqiu** [comment]
Looks like dynamo is not imported properly. can you please provide more information on how did you install dynamo and which version is it? 

Can you try something like `pip3 install dynamo-release --no-binary :all:` --no-binary :all: is making pip compile dependencies from source code instead of using any pre-compiled wheels potentially available.

**Comment by QianChwnLyn** [comment]
> 
I installed dynamo according to the installation tutorial given by GitHub [https://dynamo-release.readthedocs.io/en/latest/ten_minutes_to_dynamo.html#how-to-install]. But every method has this problem. At the same time, this problem only occurs when importing dynamo from the python command line. This problem will not occur in Jupyter or deliver tasks to the background. My dynamo-release is V1.2.0. 

I try to install dynamo by `pip3 install dynamo-release --no-binary :all:`, also useless.

Meanwhile, I met another issue. When I run `dyn.tl.leiden` function, the Jupyter or task will be terminated. I change to `dyn.tl.louvain` function, and the Jupyter or task will be continued.

**Comment by Xiaojieqiu** [comment]
@QianChwnLyn thanks for reporting this issue. It seems quiet strange. Can you please try to pull the latest changes of dynamo on github and reinstall it again? Once you installed the latest version you can use `dyn.session_info()` to print your environment and we can take a close look at it. 

The latest code has also overhaul and optimize the louvain and leiden clustering functions which should give a significant speedup. 

Hope these helps!

**Comment by yh154** [comment]
Hi, 

I got the exact the same problem on terminal, no matter installed by following tutorial or by adding '--no-binary :all:' by pip or git. This only happens using terminal, but works within IDE. Enclosed session info within IDE:

dyn.session_info()
-----
dynamo      1.2.0
-----
KDEpy                       1.1.0
PIL                         9.0.1
PyQt5                       NA
anndata                     0.8.0
appnope                     0.1.2
asttokens                   NA
atomicwrites                1.4.0
backcall                    0.2.0
beta_ufunc                  NA
binom_ufunc                 NA
bottleneck                  1.3.4
cffi                        1.15.0
chardet                     4.0.0
cloudpickle                 2.0.0
colorama                    0.4.4
colorcet                    1.0.0
cutils                      NA
cycler                      0.10.0
cython_runtime              NA
cytoolz                     0.11.0
dask                        2022.02.1
dateutil                    2.8.2
debugpy                     1.5.1
decorator                   5.1.1
defusedxml                  0.7.1
executing                   0.8.3
fsspec                      2022.02.0
google                      NA
h5py                        3.6.0
igraph                      0.10.4
importlib_metadata          NA
importlib_resources         NA
ipykernel                   6.9.1
ipython_genutils            0.2.0
ipywidgets                  7.6.5
jedi                        0.18.1
jinja2                      3.1.2
joblib                      1.1.0
jupyter_server              1.13.5
kiwisolver                  1.3.2
llvmlite                    0.38.0
markupsafe                  2.0.1
matplotlib                  3.7.1
matplotlib_inline           NA
mkl                         2.4.0
mpl_toolkits                NA
natsort                     8.2.0
nbinom_ufunc                NA
networkx                    2.7.1
numba                       0.55.1
numdifftools                0.9.41
numexpr                     2.8.1
numpy                       1.21.5
nxviz                       NA
packaging                   21.3
palettable                  3.3.0
pandas                      1.4.2
parso                       0.8.3
patsy                       0.5.2
pexpect                     4.8.0
pickleshare                 0.7.5
pkg_resources               NA
plotly                      5.6.0
prompt_toolkit              3.0.20
psutil                      5.8.0
ptyprocess                  0.7.0
pure_eval                   0.2.2
pycparser                   2.21
pydev_ipython               NA
pydevconsole                NA
pydevd                      2.6.0
pydevd_concurrency_analyser NA
pydevd_file_utils           NA
pydevd_plugins              NA
pydevd_tracing              NA
pygments                    2.14.0
pynndescent                 0.5.8
pyparsing                   3.0.4
pytz                        2021.3
ruamel                      NA
scipy                       1.7.3
seaborn                     0.11.2
session_info                1.0.0
setuptools                  61.2.0
setuptools_scm              NA
sip                         NA
six                         1.16.0
sklearn                     1.0.2
snappy                      NA
sphinxcontrib               NA
spyder                      5.1.5
spyder_kernels              2.1.3
spydercustomize             NA
stack_data                  0.2.0
statsmodels                 0.13.2
tblib                       1.7.0
texttable                   1.6.4
threadpoolctl               2.2.0
tlz                         0.11.0
toolz                       0.11.2
tornado                     6.1
tqdm                        4.64.0
traitlets                   5.1.1
typing_extensions           NA
wcwidth                     0.2.5
wurlitzer                   3.0.2
yaml                        6.0
zipp                        NA
zmq                         22.3.0
zope                        NA
zstandard                   0.19.0
-----
IPython             8.2.0
jupyter_client      6.1.12
jupyter_core        4.9.2
jupyterlab          3.3.2
notebook            6.4.8
-----
Python 3.9.12 (main, Apr  5 2022, 01:53:17) [Clang 12.0.0 ]
macOS-10.16-x86_64-i386-64bit
-----


>dyn.get_all_dependencies_version()
package umap-learn pynndescent anndata seaborn statsmodels   numba  \
version      0.5.3       0.5.8   0.8.0  0.11.2      0.13.2  0.55.1   

package session-info scikit-learn pandas  scipy   numpy colorcet networkx  \
version        1.0.0        1.0.2  1.4.2  1.7.3  1.21.5    2.0.6    2.7.1   

package loompy openpyxl get-version typing-extensions    tqdm setuptools  \
version  3.0.7    3.0.9       3.5.4             4.1.1  4.64.0     61.2.0   

package  cdlib numdifftools python-igraph dynamo-release pre-commit matplotlib  
version  0.2.6       0.9.41        0.10.4          1.2.0      3.1.1      3.7.1

**Comment by cherrie-g** [comment]
Does anyone have solution of this issue？I have tried installing the newest version and --no-binary :all:, both are useless.

**Comment by cherrie-g** [comment]
> Does anyone have solution of this issue？I have tried installing the newest version and --no-binary :all:, both are useless.

I tried to uninstall the ipython package and the "In : " was go back to ">>>"

**Comment by Xiaojieqiu** [comment]
Thanks @cherrie-g can you please let us know how did you install the package? 

@Sichao25 can provide more helps as well

**Comment by cherrie-g** [comment]
> Thanks @cherrie-g can you please let us know how did you install the package?
> 
> @Sichao25 can provide more helps as well

Yes. I installed the dynamo package in a conda environment with "pip install spateo-release".

**Comment by cherrie-g** [comment]
> Hi @cherrie-g , thanks for reporting the issue. Is the Dynamo package also failing in the terminal but working in an IDE or notebook, or is it failing in all environments? Could you please provide the console output to provide more information?

I tried to instal the package both in terminal and in local notebook. It works well in local notebook. Actually, it can also work in the terminal although the command line start with “In : ” in interactive mode python. I can just use it like in notebook. But, when I execute function in other packages, like spateo.tl.scc (I am not sure whether it is the reason), my python is quit with no error or warnings. And core file was generated, but sorry I didn't keep it.

**Comment by Sichao25** [comment]
`spateo.tl.scc` also uses `dyn.tl.leiden`. Looks like it's the same issue mentioned above. I will investigate it and go back to you.

**Comment by Sichao25** [comment]
Regarding the terminal problem, it seems that importing Dynamo will unexpectedly turn the Python interactive mode into something similar to an IPython interactive shell. I will investigate further on this. In the meantime, you can continue to use it like Jupyter Notebook. Sorry for any inconvenience.

As for the Leiden problem, I can't reproduce it in my environment. The `dyn.tl.leiden `clustering works in my terminal/notebook/IDE. As the first step to debug this, I wonder if you have installed the additional requirement `leidenalg`, as it was not visible in the session info shared by yh154.

**Comment by cherrie-g** [comment]
> Regarding the terminal problem, it seems that importing Dynamo will unexpectedly turn the Python interactive mode into something similar to an IPython interactive shell. I will investigate further on this. In the meantime, you can continue to use it like Jupyter Notebook. Sorry for any inconvenience.
> 
> As for the Leiden problem, I can't reproduce it in my environment. The `dyn.tl.leiden `clustering works in my terminal/notebook/IDE. As the first step to debug this, I wonder if you have installed the additional requirement `leidenalg`, as it was not visible in the session info shared by yh154.
> 
> Just to provide more information, I use Python 3.9.16, and IPython 8.12.0.

I just checked that I have installed the leidenalg package, and I use Python 3.8.12 and IPython 8.12.2. 
I installed the spateo and dynamo in one environment with stereopy, I‘m not sure if they have some conflict. And I will try to create another Python 3.9 environment to test.

**Comment by cherrie-g** [comment]
I think I find the reason. The `leidenalg` package 0.8.10 requires `igraph` <0.10,>=0.9.0, while my `igraph` package was 0.10.5. I downgraded the `igraph` package to 0.9.11 and the leiden issue is solved. But `igraph` 0.9.11 doesn't meet the requirement of other packages like `louvain`, so maybe there will be other issues we didn't meet.
