### ISSUE TITLE
A function in the document "10 minutes to dynamo" is missing a letter.

### ISSUE THREAD

**Issue by asdChenJin** [aristoteleo/dynamo-release#459]
### There is a small error in the "Visualization" document of "10 minutes to dynamo"
![image](https://user-images.githubusercontent.com/33625968/224620359-746d1103-5673-4ef7-916e-2685d46c91ae.png)
The “dyn.pl.streamline_plot” function in the code is missing an "a".
`dyn.pl.stremline_plot(adata, color=colors, ncols=3)`
Please fix this small error in the document.

**Comment by Xiaojieqiu** [comment]
thanks Chen! We recently hired two software engineers and they are actively work on optimizing the code and we will fix this issue as well as others quickly! Thanks again

**Comment by Ukyeon** [comment]
Hello @asdChenJin,

Thank you for bringing this issue to our attention. We greatly appreciate your efforts in helping us maintain the high quality of our tutorials. Please feel free to check the updated documents and let us know if you come across any further issues. Thank you once again for your valuable feedback and have a wonderful day!
<img width="435" alt="Screenshot 2023-03-14 at 11 02 17 AM" src="https://user-images.githubusercontent.com/101152633/225044588-8a546b28-88db-468a-928d-7dca843fc954.png">
