### ISSUE TITLE
scatters and heatmap plot

### ISSUE THREAD

**Issue by wangjiawen2013** [aristoteleo/dynamo-release#463]
Hi,
Some pseudotime tools such as palantir can plot very beautiful figures (refer to https://github.com/dpeerlab/Palantir/blob/master/notebooks/Palantir_sample_notebook.ipynb)

![image](https://user-images.githubusercontent.com/29703450/225220024-52afa92e-54e1-4ad8-a78c-12aa766042db.png)

![image](https://user-images.githubusercontent.com/29703450/225220081-a9af36b3-1c78-4918-98c3-5a0d94dc3256.png)

![image](https://user-images.githubusercontent.com/29703450/225220116-31248386-294a-4f84-be7c-c26382b903a6.png)

Though we can show gene trends with scatter and heatmap using dynamo, the data are discrete and they don't look so beautiful. Hopy you can develop more visulization functions for beautify.

**Comment by Xiaojieqiu** [comment]
Thanks for your great suggestion, @wangjiawen2013! Have you tried `dyn.pl.kinetic_heatmap` and `dyn.pl.kinetic_curves` function?
