### ISSUE TITLE
fail to import dynamo

### ISSUE THREAD

**Issue by heyouzhe** [aristoteleo/dynamo-release#464]
![image](https://user-images.githubusercontent.com/108378568/225580518-f089aea7-6fdc-42e7-bb00-000ec8d7d903.png)
ValueError                                Traceback (most recent call last)
Cell In[1], line 9
      7 import sklearn
      8 import spateo as st
----> 9 import dynamo as dyn
     10 import cv2
     11 import anndata

File /usr/local/lib/python3.8/site-packages/dynamo/__init__.py:13
      7 del get_version
      9 # from .get_version import get_dynamo_version
     10 #
     11 # __version__ = get_dynamo_version()
---> 13 from . import pp
     14 from . import est
     15 from . import tl

File /usr/local/lib/python3.8/site-packages/dynamo/pp.py:4
      1 """Mapping Vector Field of Single Cells
      2 """
----> 4 from .preprocessing import *

File /usr/local/lib/python3.8/site-packages/dynamo/preprocessing/__init__.py:4
      1 """Mapping Vector Field of Single Cells
      2 """
----> 4 from .cell_cycle import cell_cycle_scores
      5 from .dynast import lambda_correction
      6 from .preprocess import (
      7     Gini,
      8     SVRs,
   (...)
     19     select_genes_monocle,
     20 )

File /usr/local/lib/python3.8/site-packages/dynamo/preprocessing/cell_cycle.py:12
      9 import pandas as pd
     10 from scipy.sparse import issparse
---> 12 from ..tools.utils import einsum_correlation, log1p_
     13 from ..utils import LoggerManager, copy_adata
     16 def group_corr(adata: anndata.AnnData, layer: Union[str, None], gene_list: list) -> tuple:

File /usr/local/lib/python3.8/site-packages/dynamo/tools/__init__.py:9
      1 """Mapping Vector Field of Single Cells
      2 """
      4 # inclusive expression dynamics model related
      5 # from .dynamo import sol_u, sol_s, fit_gamma_labelling, fit_alpha_labelling, fit_gamma_splicing, fit_gamma
      6 # from .dynamo_fitting import sol_u, sol_s, sol_p, sol_ode, sol_num, fit_gamma_labelling, fit_beta_lsq, fit_alpha_labelling, fit_alpha_synthesis, fit_gamma_splicing, fit_gamma
----> 9 from .cell_velocities import (
     10     cell_velocities,
     11     confident_cell_velocities,
     12     diffusion,
     13     expected_return_time,
     14     generalized_diffusion_map,
     15     stationary_distribution,
     16 )
     18 # clustering related
     19 from .clustering import (
     20     cluster_community,
     21     cluster_community_from_graph,
   (...)
     27     scc,
     28 )

File /usr/local/lib/python3.8/site-packages/dynamo/tools/cell_velocities.py:23
     14 from ..dynamo_logger import (
     15     LoggerManager,
     16     main_critical,
   (...)
     20     main_warning,
     21 )
     22 from ..utils import areinstance
---> 23 from .connectivity import _gen_neighbor_keys, adj_to_knn, check_and_recompute_neighbors
     24 from .dimension_reduction import reduceDimension
     25 from .graph_calculus import calc_gaussian_weight, fp_operator, graphize_velocity

File /usr/local/lib/python3.8/site-packages/dynamo/tools/connectivity.py:13
     10 from sklearn.decomposition import TruncatedSVD
     11 from sklearn.utils import sparsefuncs
---> 13 from ..configuration import DynamoAdataKeyManager
     14 from ..docrep import DocstringProcessor
     15 from ..dynamo_logger import LoggerManager, main_info, main_warning

File /usr/local/lib/python3.8/site-packages/dynamo/configuration.py:297
    295 # register cmap
    296 plt.register_cmap("zebrafish", zebrafish_cmap)
--> 297 plt.register_cmap("fire", fire_cmap)
    298 plt.register_cmap("darkblue", darkblue_cmap)
    299 plt.register_cmap("darkgreen", darkgreen_cmap)

File /usr/local/lib/python3.8/site-packages/matplotlib/_api/deprecation.py:200, in deprecated.<locals>.deprecate.<locals>.wrapper(*args, **kwargs)
    198 def wrapper(*args, **kwargs):
    199     emit_warning()
--> 200     return func(*args, **kwargs)

File /usr/local/lib/python3.8/site-packages/matplotlib/cm.py:274, in register_cmap(name, cmap, override_builtin)
    270 # override_builtin is allowed here for backward compatibility
    271 # this is just a shim to enable that to work privately in
    272 # the global ColormapRegistry
    273 _colormaps._allow_override_builtin = override_builtin
--> 274 _colormaps.register(cmap, name=name, force=override_builtin)
    275 _colormaps._allow_override_builtin = False

File /usr/local/lib/python3.8/site-packages/matplotlib/cm.py:143, in ColormapRegistry.register(self, cmap, name, force)
    139 if name in self:
    140     if not force:
    141         # don't allow registering an already existing cmap
    142         # unless explicitly asked to
--> 143         raise ValueError(
    144             f'A colormap named "{name}" is already registered.')
    145     elif (name in self._builtin_cmaps
    146             and not self._allow_override_builtin):
    147         # We don't allow overriding a builtin unless privately
    148         # coming from register_cmap()
    149         raise ValueError("Re-registering the builtin cmap "
    150                          f"{name!r} is not allowed.")

ValueError: A colormap named "fire" is already registered.

**Comment by Xiaojieqiu** [comment]
I believe this issue has been resolved in the latest version. Please pull the latest version on github and install it
