### ISSUE TITLE
Refactor the preprocessing module

### ISSUE THREAD

**Issue by Sichao25** [aristoteleo/dynamo-release#465]
Refactor the preprocessing module and implement essential new functions. Tasks include:

- [x] Implement callers for convert2symbol & basic_stat & scale functions in the Preprocessor class.
- [x] Find ways to reduce the processing time for PCA.
- [x] Implement a regress out function.
- [x] Implement fano feature selection.
- [x] Add preprocessed data saving functionality: adata.raw = adata.
- [x] Fix any issues to make the code more applicable to a wider range of heterogeneous datasets.
- [x] Try to reduce duplicate operations in multiple functions.
- [x] Optimize code and decompose long functions if needed.
- [x] Update docstrings and type hints for all functions.
- [x] Add more tests for preprocessing.
- [x] Update preprocessing tutorials.

**Comment by Sichao25** [comment]
Here are more details on duplicate operations. Some operations (most related to layers) appear multiple times in different functions. We can either create new functions in utils or use DynamoAdataKeyManger to get rid of them. Examples includes:
```
if layer == "raw":
    CM = adata.raw.X
elif layer == "X":
    CM = adata.X
elif layer == "protein":
    if "protein" in adata.obsm_keys():
        CM = adata.obsm[layer]
    else:
         continue
else:
    CM = adata.layers[layer]
```
and
```
if not X_total_layers:
    excluded_layers.extend(["X"])
if not splicing_total_layers:
    excluded_layers.extend(["spliced", "unspliced"])
```

**Comment by Xiaojieqiu** [comment]
thanks @Sichao25, can you clarify why these two script snippets are duplicated?

**Comment by Sichao25** [comment]
I think similar structures appear in multiple places. The similar structures of code snippet 1 exists in `GINI(), SVRs(), calc_sz_factor(), sz_util(), disp_calc_helper_NB()` and other functions. It may be possible to create a function like `DynamoAdataKeyManager.select_layer_data` to handle this. 
Code snippet 2 appears both in `normalize_cell_expr_by_size_factors_legacy() and calc_sz_factor()`. We can simply replace them with a new util function.
