### ISSUE TITLE
anndata version

### ISSUE THREAD

**Issue by wangjiawen2013** [aristoteleo/dynamo-release#471]
Hi, 
anndata has updated to 0.8.0 (even 0.9.0). If we use dynamo, we must reinstall anndata to 0.7.5, while in this case, we cannot read the anndata objects constructed with 0.8.0. Of course in this case we can create a new conda environment to install dynamo, but it's better for dynamo to compatiable with anndata 0.8.0. The good compatibility makes it convinient to communicate with other anndata objects.

here is the error:
dynamo-release 1.2.0 requires anndata==0.7.5, but you have anndata 0.8.0 which is incompatible.

**Comment by Xiaojieqiu** [comment]
Thanks Jiawen! dynamo on pypi still depends on anndata 0.7.5, but the latest one on github now upgraded its requirement for at least 0.8.0.  We will release a dynamo 1.3.0 version  shortly after we will refactor the code in the preprocessing. You can always upgrade to 0.8.

**Comment by Yao-14** [comment]
Hi Xiaojie, could you release a dynamo new version?
![image](https://user-images.githubusercontent.com/89448797/232966622-bd8d2bec-683f-4bf8-adb2-e13489816c9b.png)

**Comment by Xiaojieqiu** [comment]
we will release a new version of dynamo on pip in a few days. But for now please install the latest version of dynamo through github
