### ISSUE TITLE
how to get cell wise beta gamma

### ISSUE THREAD

**Issue by changyunjian** [aristoteleo/dynamo-release#477]
Hi ,
How can i get cell wise beta, gamma in layers?  I can get cell wise alpha using 'two step' estimate method only.

**Comment by Xiaojieqiu** [comment]
Hi Changyuan, currently we only provide cell-wise alpha but beta and gamma are assumed to be constants. Please refer to our method section for details on this (https://www.sciencedirect.com/science/article/pii/S0092867421015774#sec5). 

We will extend our approach shortly and cell-wise kinetic parameters related to RNA life will be provided shortly. 

Thanks,
Xiaojie
