### ISSUE TITLE
How to control the directionality?

### ISSUE THREAD

**Issue by wulabupenn** [aristoteleo/dynamo-release#5]
Hi Xiaojie,

I tested dynamo on a time series data set. I get a complete reserve direction of the arrows since I have actual time points as a reference. 

1) So i am wondering whether there is a way to control the directionality (such as reverse =T in monocle setting)?

2) Is there any quantitative way to measure dynamo is better than traditional RNA velocyto analysis? In here _dynamo-notebooks/main_figs/Fig1C.ipynb_ , the visualization of the dynamo seems better ordered that the traditional RNA velocyto but sometimes it is kind of a little bit arbitrary.

Thanks in advance,
Peng

**Comment by Xiaojieqiu** [comment]
Hi Peng, 

Thanks for using dynamo, could you please let me a little more details about the experimental setup and how did you run dynamo? If you want, you can share your code and some reproducible data (or email me some example data if you have certain confidential concerns). I am here to help. 

I used the other nice velocity tool (scvelo) for Fig1C actually but I will update it soon with our dynamo analysis.

**Comment by wulabupenn** [comment]
Hi Xiaojie, thank you for your clarification about the code for Figure 1C. I look forward to trying your dynamo package in near future. I'd be happy to share with your some of our nascent single cell RNA-seq data soon. Keep in touch, cheers!
________________________________

**Comment by wulabupenn** [comment]
Hi Xiaojie, thank you for your clarification about the code for Figure 1C. I look forward to trying your dynamo package in near future. I'd be happy to share with your some of our nascent single cell RNA-seq data soon. Keep in touch, cheers!

**Comment by Xiaojieqiu** [comment]
Of course, let me know if you need any further helps. I just noticed that two single-cell SLAM-seq papers are out (NASC-seq: https://www.nature.com/articles/s41467-019-11028-9, scSLAM-seq: https://www.nature.com/articles/s41586-019-1369-y). I will update our notebooks with tutorials on analyzing their published data this week.

**Comment by Xiaojieqiu** [comment]
@wulabupenn please check this tutorial for the velocity / vector field analysis on NASC-seq with dynamo: https://github.com/aristoteleo/dynamo-notebooks/blob/master/NASC_seq/NASC_seq_analysis.ipynb
