### ISSUE TITLE
Bug for dyn.pp.recipe_monocle when the normalized data of the gene expression was used

### ISSUE THREAD

**Issue by Mingsenli** [aristoteleo/dynamo-release#523]
When the normalized data of the gene expression was used,  "dyn.pp.recipe_monocle(adata)"  sometimes fails to run, but strangely, when running this command repeatedly multiple times, sometimes it works. It’s all a matter of luck.

When the conunts was used, this command can always be run successfully.

Can the normalized data  be used?
How to solve this bug?

The following was the error:
--> recipe_monocle_keep_filtered_cells_key is None. Using default value from DynamoAdataConfig: recipe_monocle_keep_filtered_cells_key=True
|-----> recipe_monocle_keep_filtered_genes_key is None. Using default value from DynamoAdataConfig: recipe_monocle_keep_filtered_genes_key=True
|-----> recipe_monocle_keep_raw_layers_key is None. Using default value from DynamoAdataConfig: recipe_monocle_keep_raw_layers_key=True
|-----> apply Monocole recipe to adata...
|-----> <insert> pp to uns in AnnData Object.
|-----------> <insert> has_splicing to uns['pp'] in AnnData Object.
|-----------> <insert> has_labling to uns['pp'] in AnnData Object.
|-----------> <insert> splicing_labeling to uns['pp'] in AnnData Object.
|-----------> <insert> has_protein to uns['pp'] in AnnData Object.
|-----> ensure all cell and variable names unique.
|-----> ensure all data in different layers in csr sparse matrix format.
|-----> ensure all labeling data properly collapased
|-----------> <insert> tkey to uns['pp'] in AnnData Object.
|-----------> <insert> experiment_type to uns['pp'] in AnnData Object.
|-----? dynamo detects your data is size factor normalized and/or log transformed. If this is not right, plese set `normalized = False.
|-----> filtering cells...
|-----> <insert> pass_basic_filter to obs in AnnData Object.
|-----> 14270 cells passed basic filters.
|-----> filtering gene...
|-----> <insert> pass_basic_filter to var in AnnData Object.
|-----> 1567 genes passed basic filters.
|-----> calculating size factor...
|-----? only 1567 genes passed basic filtering, but you requested 2000 genes for feature selection. Try lowering the gene selection stringency: {'min_expr_cells': 0, 'min_expr_avg': 0, 'max_expr_avg': inf, 'svr_gamma': None, 'winsorize': False, 'winsor_perc': (1, 99.5), 'sort_inverse': False}
|-----> selecting genes in layer: X, sort method: SVR...
|-----> <insert> frac to var in AnnData Object.
|-----> <insert> X_spliced to layers in AnnData Object.
|-----> <insert> X_unspliced to layers in AnnData Object.
|-----------> <insert> norm_method to uns['pp'] in AnnData Object.
|-----> applying PCA ...
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[3], line 1
----> 1 dyn.pp.recipe_monocle(adata)
      2 dyn.tl.dynamics(adata, cores=48)
      3 dyn.tl.reduceDimension(adata)

File ~/.local/lib/python3.8/site-packages/dynamo/preprocessing/preprocess.py:1288, in recipe_monocle(adata, reset_X, tkey, t_label_keys, experiment_type, normalized, layer, total_layers, splicing_total_layers, X_total_layers, genes_use_for_norm, genes_to_use, genes_to_append, genes_to_exclude, exprs_frac_for_gene_exclusion, method, num_dim, sz_method, scale_to, norm_method, pseudo_expr, feature_selection, n_top_genes, maintain_n_top_genes, relative_expr, keep_filtered_cells, keep_filtered_genes, keep_raw_layers, scopes, fc_kwargs, fg_kwargs, sg_kwargs, copy, feature_selection_layer)
   1285 logger.info("applying %s ..." % (method.upper()))
   1287 if method == "pca":
-> 1288     adata = pca(adata, pca_input, num_dim, "X_" + method.lower())
   1289     # TODO remove adata.obsm["X"] in future, use adata.obsm.X_pca instead
   1290     adata.obsm["X"] = adata.obsm["X_" + method.lower()]

File ~/.local/lib/python3.8/site-packages/dynamo/preprocessing/utils.py:1022, in pca(adata, X_data, n_pca_components, pca_key, pcs_key, genes_to_append, layer, svd_solver, random_state, use_truncated_SVD_threshold, use_incremental_PCA, incremental_batch_size, return_all)
   1014         fit, X_pca = _pca_fit(
   1015             X_data,
   1016             pca_func=PCA,
   (...)
   1019             random_state=random_state,
   1020         )
   1021     else:
-> 1022         fit, X_pca = _truncatedSVD_with_center(
   1023             X_data,
   1024             n_components=n_pca_components,
   1025             random_state=random_state,
   1026         )
   1027 else:
   1028     # TruncatedSVD is the fastest method we have. It doesn't center the
   1029     # data. It only performs SVD decomposition, which is the second part
   1030     # in our _truncatedSVD_with_center function.
   1031     fit, X_pca = _pca_fit(
   1032         X_data, pca_func=TruncatedSVD, n_components=n_pca_components + 1, random_state=random_state
   1033     )

File ~/.local/lib/python3.8/site-packages/dynamo/preprocessing/utils.py:846, in _truncatedSVD_with_center(X, n_components, random_state)
    836 X_centered = LinearOperator(
    837     shape=X.shape,
    838     matvec=matvec,
   (...)
    842     dtype=X.dtype,
    843 )
    845 # Solve SVD without calculating individuals entries in LinearOperator.
--> 846 U, Sigma, VT = svds(X_centered, solver="arpack", k=n_components, v0=v0)
    847 Sigma = Sigma[::-1]
    848 U, VT = svd_flip(U[:, ::-1], VT[::-1])

File ~/.local/lib/python3.8/site-packages/scipy/sparse/linalg/_eigen/_svds.py:447, in svds(A, k, ncv, tol, which, v0, maxiter, return_singular_vectors, solver, random_state, options)
    104 def svds(A, k=6, ncv=None, tol=0, which='LM', v0=None,
    105          maxiter=None, return_singular_vectors=True,
    106          solver='arpack', random_state=None, options=None):
    107     """
    108     Partial singular value decomposition of a sparse matrix.
    109 
   (...)
    445     True
    446     """
--> 447     args = _iv(A, k, ncv, tol, which, v0, maxiter, return_singular_vectors,
    448                solver, random_state)
    449     (A, k, ncv, tol, which, v0, maxiter,
    450      return_singular_vectors, solver, random_state) = args
    452     largest = (which == 'LM')

File ~/.local/lib/python3.8/site-packages/scipy/sparse/linalg/_eigen/_svds.py:40, in _iv(A, k, ncv, tol, which, v0, maxiter, return_singular, solver, random_state)
     37 if not (np.issubdtype(A.dtype, np.complexfloating)
     38         or np.issubdtype(A.dtype, np.floating)):
     39     message = "`A` must be of floating or complex floating data type."
---> 40     raise ValueError(message)
     41 if np.prod(A.shape) == 0:
     42     message = "`A` must not be empty."

ValueError: `A` must be of floating or complex floating data type.

**Comment by Xiaojieqiu** [comment]
@Sichao25 can you help this please?

**Comment by Sichao25** [comment]
@Mingsenli Thank you very much for reporting the bug. I will fix this soon. 

When you used normalized data, the `recipe_monocle` will copy your raw layers to the preprocessed layers (e.g. `.layers["splice"]` -> `.obsm["X_spliced]`). This operation unexpectedly changes the value of the layers list to the last element in the original list. The error happens when this element is "X". Due to the randomness when initializing anndata object, this element will not always be X, that's why it doesn't raise the error every time.

One way to avoid this problem before the fix is to use counts instead of normalized data. Alternatively, you can avoid running `recipe_monocle` by running the necessary preprocessing steps one by one. Also, if all of your layers have been normalized, you can remove any layers that are not X from your anndata object, run `recipe_monocle` only on X layer, and then copy those layers back to your preprocessed anndata.

**Comment by Mingsenli** [comment]
Thank you very much for solving my problems.
I found that using normalized data and counts will result in different results.
I hope both normalized data and counts can be used so that the users can choose which one is better.
