### ISSUE TITLE
what is the adata.layers['matrix'] ? 

### ISSUE THREAD

**Issue by Mingsenli** [aristoteleo/dynamo-release#526]
I have a question. 
what is the adata.layers['matrix'] ? 
The 'matrix' in the layers is the original gene expression?

Thank you!

**Comment by Xiaojieqiu** [comment]
Hi @Mingsenli  are you reading data from loom file format? if so, matrix is the sum of spliced, unspliced and unambiguous layers. See discussion about this issue here: https://github.com/velocyto-team/velocyto.py/issues/361

**Comment by Mingsenli** [comment]
Hi @Xiaojieqiu 
Thank you for your help!
I read data from loom file.
So my question has been solved.
