### ISSUE TITLE
what is 'M_u', 'M_uu', 'M_s', 'M_us', 'M_ss' in adata.layer? What do they represent?

### ISSUE THREAD

**Issue by Mingsenli** [aristoteleo/dynamo-release#536]
Hi,Xiaojieqiu:
 what is 'M_u', 'M_uu', 'M_s', 'M_us', 'M_ss' in adata.layer? What do they represent?
Thank you !

**Comment by Xiaojieqiu** [comment]
M means moments, u / s are unspliced and spliced RNAs. uu/ss means uncentered second moments of unspliced or spliced RNA, us is the cross moments between unspliced and spliced RNAs

**Comment by Xiaojieqiu** [comment]
you can find details in our dynamo paper's method section, see places near `Second moments (uncentered variances and covariances) provide information in`
