### ISSUE TITLE
TypeError: unhashable type: 'slice'

### ISSUE THREAD

**Issue by Mingsenli** [aristoteleo/dynamo-release#540]
Hi, Xiaojieqiu:

I failed to run dyn.pl.topography. I need the help. Thank you!
The following is my code and the error:

dyn.pp.recipe_monocle(adata)
dyn.tl.dynamics(adata, cores=48)
dyn.tl.reduceDimension(adata)

dyn.tl.cell_velocities(adata, basis='umap')
dyn.vf.VectorField(adata, basis='umap', M=1000, pot_curl_div=True)

dyn.pl.topography(adata, basis='umap', background='white', color=['group', 'leiden_anno'], streamline_color='black', show_legend='on data', frontier=True)

|-----> Vector field for umap is but its topography is not mapped. Mapping topography now ...
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[90], line 1
----> 1 dyn.pl.topography(adata, basis='umap', background='white', color=['group', 'leiden_anno'], streamline_color='black', show_legend='on data', frontier=True)

File ~/.local/lib/python3.8/site-packages/dynamo/plot/topography.py:1110, in topography(adata, basis, fps_basis, x, y, color, layer, highlights, labels, values, theme, cmap, color_key, color_key_cmap, background, ncols, pointsize, figsize, show_legend, use_smoothed, xlim, ylim, t, terms, init_cells, init_states, quiver_source, fate, approx, quiver_size, quiver_length, density, linewidth, streamline_color, streamline_alpha, color_start_points, markersize, marker_cmap, save_show_or_return, save_kwargs, aggregate, show_arrowed_spines, ax, sort, frontier, s_kwargs_dict, q_kwargs_dict, **streamline_kwargs_dict)
   1108     with warnings.catch_warnings():
   1109         warnings.simplefilter("ignore")
-> 1110         _topology(adata, fps_basis, VecFld=None)
   1111 else:
   1112     if fps_vecfld_dict["Xss"].size > 0 and fps_vecfld_dict["Xss"].shape[1] > 2:

File ~/.local/lib/python3.8/site-packages/dynamo/vectorfield/topography.py:737, in topography(adata, basis, layer, X, dims, n, VecFld, **kwargs)
    724 if dims is None:
    725     dims = np.arange(adata.obsm["X_" + basis].shape[1])
    727 (
    728     X_basis,
    729     xlim,
    730     ylim,
    731     confidence,
    732     NCx,
    733     NCy,
    734     Xss,
    735     ftype,
    736     fp_ind,
--> 737 ) = util_topology(adata, basis, X, dims, func, VecFld, n=n, *kwargs)
    739 # commented for now, will go back to this later.
    740 # sep = compute_separatrices(vecfld.Xss.get_X(), vecfld.Xss.get_J(), vecfld.func, xlim, ylim)
    742 if layer is None:

File ~/.local/lib/python3.8/site-packages/dynamo/vectorfield/topography.py:643, in util_topology(adata, basis, dims, func, VecFld, X, n, **kwargs)
    612 def util_topology(
    613     adata: AnnData,
    614     basis: str,
   (...)
    620     **kwargs,
    621 ):
    622     """A function that computes nullclines and fixed points defined by the function func.
    623 
    624     Args:
   (...)
    641             - an array of shape (n, ) containing the indices of the fixed points in the original data.
    642     """
--> 643     X_basis = adata.obsm["X_" + basis][:, dims] if X is None else X[:, dims]
    645     if X_basis.shape[1] == 2:
    646         fp_ind = None

TypeError: unhashable type: 'slice'

**Comment by Sichao25** [comment]
Hi, thank you very much for reporting the issue. This is a bug in version 1.2. It has been fixed in the version after that. If you are using 1.2, updating the Dynamo will fix it. If that doesn't solve your problem, please let me know which version and dataset you are using, allowing me to reproduce the error and provide further assistance.

**Comment by Mingsenli** [comment]
Hi, Thank you for the help. It has been solved in the latest 1.3 version.
