### ISSUE TITLE
How to generate "X_umap_distances" and "cosine_transition_matrix"

### ISSUE THREAD

**Issue by Mingsenli** [aristoteleo/dynamo-release#544]
Hi, Sorry for bothering you so many times.
 LAP analyses need "X_umap_distances" and "cosine_transition_matrix". But there is no corresponding tutorial in the official website.
I do not know how to generate them in adata. 

Thank you!
Good luck!

**Comment by Xiaojieqiu** [comment]
you can generate these information via running neighborhood calculation, using something like `dyn.tl.neighbors(adata, basis='X_umap')`

**Comment by Mingsenli** [comment]
Hi Xiaojie:

**When i run dyn.tl.neighbors(adata, basis="umap",result_prefix="umap"), it runs successfully. But "X_umap_distances" and "cosine_transition_matrix" did not been generated in adata.obsp. Instead, umap_distances was generated.

obsp: 'moments_con', 'distances', 'connectivities', 'pearson_transition_matrix', 'umap_distances', 'umap_connectivities'

So the following codes fail to run.**

%%capture
dyn.dynamo_logger.main_silence()
transition_graph = {}
cell_type = ["E_cornea.basal", "E_cornea.superficial", "adult_cornea.superficial"]
start_cell = [
    E_cornea_basal_cells_indices,
    E_cornea_superficial_cells_indices,
   adult_cornea_superficial_cells_indices,
]
end_cell = start_cell
for i, start in enumerate(start_cell):
    for j, end in enumerate(end_cell):
        if start is not end:
            min_lap_t = True if i == 0 else False
            dyn.pd.least_action(
                adata,
                [adata.obs_names[start[0]][0]],
                [adata.obs_names[end[0]][0]],
                basis="umap",
                adj_key="X_umap_distances",
                min_lap_t= min_lap_t,
                EM_steps=2,
            )
            dyn.pl.least_action(adata, basis="umap")
            lap = dyn.pd.least_action(
                adata,
                [adata.obs_names[start[0]][0]],
                [adata.obs_names[end[0]][0]],
                basis="pca",
                adj_key="cosine_transition_matrix",
                min_lap_t=min_lap_t,
                EM_steps=2,
            )
            dyn.pl.kinetic_heatmap(
                adata,
                basis="pca",
                mode="lap",
                genes=adata.var_names[adata.var.use_for_transition],
                project_back_to_high_dim=True,
            )
            # The `GeneTrajectory` class can be used to output trajectories for any set of genes of interest
            gtraj = dyn.pd.GeneTrajectory(adata)
            gtraj.from_pca(lap.X, t=lap.t)
            gtraj.calc_msd()
            ranking = dyn.vf.rank_genes(adata, "traj_msd")

            print(start, "->", end)
            genes = ranking[:5]["all"].to_list()
            arr = gtraj.select_gene(genes)

            dyn.pl.multiplot(lambda k: [plt.plot(arr[k, :]), plt.title(genes[k])], np.arange(len(genes)))

            transition_graph[cell_type[i] + "->" + cell_type[j]] = {
                "lap": lap,
                "LAP_umap": adata.uns["LAP_umap"],
                "LAP_pca": adata.uns["LAP_pca"],
                "ranking": ranking,
                "gtraj": gtraj,
            }


KeyError                                  Traceback (most recent call last)
Cell In[33], line 14
     12 if start is not end:
     13     min_lap_t = True if i == 0 else False
---> 14     dyn.pd.least_action(
     15         adata,
     16         [adata.obs_names[start[0]][0]],
     17         [adata.obs_names[end[0]][0]],
     18         basis="umap",
     19         adj_key="X_umap_distances",
     20         min_lap_t= min_lap_t,
     21         EM_steps=2,
     22     )
     23     dyn.pl.least_action(adata, basis="umap")
     24     lap = dyn.pd.least_action(
     25         adata,
     26         [adata.obs_names[start[0]][0]],
   (...)
     31         EM_steps=2,
     32     )

File ~/.local/lib/python3.8/site-packages/dynamo/prediction/least_action_path.py:487, in least_action(adata, init_cells, target_cells, init_states, target_states, paired, min_lap_t, elbow_method, num_t, basis, vf_key, vecfld, adj_key, n_points, init_paths, D, PCs, expr_func, add_key, **kwargs)
    483     vf = vecfld
    485 coords = adata.obsm["X_" + basis]
--> 487 T = adata.obsp[adj_key]
    488 G = nx.convert_matrix.from_scipy_sparse_matrix(T)
    490 init_states, _, _, _ = fetch_states(
    491     adata,
    492     init_states,
   (...)
    497     None,
    498 )

File ~/.local/lib/python3.8/site-packages/anndata/_core/aligned_mapping.py:148, in AlignedActualMixin.__getitem__(self, key)
    147 def __getitem__(self, key: str) -> V:
--> 148     return self._data[key]

KeyError: 'X_umap_distances'

**Then i run dyn.tl.neighbors(adata, basis="X_umap") as your suggested, an error was generated:**

|-----> Start computing neighbor graph...
|-----------> X_data is None, fetching or recomputing...
|-----> fetching X data from layer:None, basis:X_umap
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[37], line 1
----> 1 dyn.tl.neighbors(adata, basis="X_umap")

File ~/.local/lib/python3.8/site-packages/dynamo/tools/connectivity.py:588, in neighbors(adata, X_data, genes, basis, layer, n_pca_components, n_neighbors, method, metric, metric_kwads, cores, seed, result_prefix, **kwargs)
    586     else:
    587         logger.info("fetching X data from layer:%s, basis:%s" % (str(layer), str(basis)))
--> 588         genes, X_data = fetch_X_data(adata, genes, layer, basis)
    590 if method is None:
    591     logger.info("method arg is None, choosing methods automatically...")

File ~/.local/lib/python3.8/site-packages/dynamo/tools/utils.py:1732, in fetch_X_data(adata, genes, layer, basis)
   1730 def fetch_X_data(adata, genes, layer, basis=None):
   1731     if basis is not None:
-> 1732         return None, adata.obsm["X_" + basis]
   1734     if genes is not None:
   1735         genes = adata.var_names.intersection(genes).to_list()

File ~/.local/lib/python3.8/site-packages/anndata/_core/aligned_mapping.py:148, in AlignedActualMixin.__getitem__(self, key)
    147 def __getitem__(self, key: str) -> V:
--> 148     return self._data[key]

KeyError: 'X_X_umap'

So adj_key="X_umap_distances" should be changed to adj_key="umap_distances"?
How to generate 'cosine_transition_matrix' ?
How to generate "fp_transition_rate" ?

Thank you!

**Comment by Xiaojieqiu** [comment]
Dear @Mingsenli, please put some efforts to reformat your questions in the future. We are happy to help you but we also have our own research to conduct and many commitments to fullfill. So it will be extremely helpful to make sure your question is well formatted and articulated. We highly appreciate it and less well formatted questions will likely be ignored in the future 

Regarding your question, you can simply change the resultant key `umap_distances` to `X_umap_distances`, or `adata.layers['X_umap_distances'] = adata.layers['umap_distances'].copy()`

**Comment by Mingsenli** [comment]
Hi @Xiaojieqiu,
I am very sorry for causing you so much inconvenience. Thanks very much for your reformatting. I'll pay attention to the format in the future.

When i change the resultant key umap_distances to X_umap_distances, it works. However, "cosine_transition_matrix" is also needed in dyn.pd.least_action with the parameter adj_key="cosine_transition_matrix". Cosine_transition_matrix is also used in "Kinetics heatmap of gene expression dynamics along the LAP" section.

There is no cosine_transition_matrix in my adata. So my question is how to generate cosine_transition_matrix.

You really helped me a lot. I hope most of the dynamo program can be used in my paper.
I apologise again for the trouble. 
Thank you very much.

**Comment by Xiaojieqiu** [comment]
Similar to `X_umap_distances`, the `cosine_transition_matrix` means the the transition matrix is calculated using the cosine kernel. you can do something like 

`dyn.tl.cell_velocities(adata, method = 'cosine', add_transition_key='cosine_transition_matrix', enforce=True)`
