### ISSUE TITLE
Please refer to igraph instead of python-igraph

### ISSUE THREAD

**Issue by szhorvat** [aristoteleo/dynamo-release#562]
Can you please refer to `igraph` instead of `python-igraph` in the below two instances?

https://github.com/search?q=repo%3Aaristoteleo%2Fdynamo-release%20python-igraph&type=code

See https://github.com/igraph/python-igraph/issues/699 for an explanation.

**Comment by Sichao25** [comment]
Thank you for the notification! Will do it soon.
