### ISSUE TITLE
Error in gene_wise_confidence correction and confident_cell_velocities correction

### ISSUE THREAD

**Issue by Jordanfink970** [aristoteleo/dynamo-release#566]
I am getting an error only when trying to correct the velocity directions for both cell_wise and the gene_wise corrections.

The general code workflow I have been running is below

# Perform the monocle pipeline for analysis
dyn.pp.recipe_monocle(adata, keep_filtered_cells=False, keep_filtered_genes=True, n_top_genes=1000)
adata

## Perform UMAP using scanpy and prepare the data that way
sc.pp.neighbors(ldata, n_neighbors=10, n_pcs=10)
sc.tl.umap(adata, min_dist=0.5)

sc.tl.leiden(adata)
dyn.tl.reduceDimension(adata)

# DYNO RNA VELOCITY CALCULATIONS
dyn.tl.dynamics(adata)

# CORRECT THE TRAJECTORY BASED ON PREVIOUS KNOWLEDGE (Progenitor --> End Cell Type)
dyn.tl.gene_wise_confidence(adata, group='leiden', lineage_dict={'4': ['9']})

 This is the error when the gene_wise_confidence is run

calculating gene velocity vectors confidence based on phase portrait location with priors of progenitor/mature cell types: 1000it [00:05, 184.74it/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[41], line 2
      1 # CORRECT THE TRAJECTORY BASED ON PREVIOUS KNOWLEDGE (HE --> DEFINITIVES)
----> 2 dyn.tl.gene_wise_confidence(ldata, group='leiden', lineage_dict={'4': ['9']})

File ~/software/miniconda3/envs/dynamo/lib/python3.10/site-packages/dynamo/tools/metric_velocity.py:436, in gene_wise_confidence(adata, group, lineage_dict, genes, ekey, vkey, X_data, V_data, V_threshold)
    431 confidence.astype(dtype={"prog_confidence": "float64", "prog_confidence": "float64"})
    432 adata.var["avg_prog_confidence"], adata.var["avg_mature_confidence"] = (
    433     np.nan,
    434     np.nan,
    435 )
--> 436 avg = confidence.groupby("gene")["prog_confidence", "mature_confidence"].mean()
    437 avg = avg.reset_index().set_index("gene")
    438 adata.var.loc[genes, "avg_prog_confidence"] = avg.loc[genes, "prog_confidence"]

File ~/software/miniconda3/envs/dynamo/lib/python3.10/site-packages/pandas/core/groupby/generic.py:1767, in DataFrameGroupBy.__getitem__(self, key)
   1763 # per GH 23566
   1764 if isinstance(key, tuple) and len(key) > 1:
   1765     # if len == 1, then it becomes a SeriesGroupBy and this is actually
   1766     # valid syntax, so don't raise
-> 1767     raise ValueError(
   1768         "Cannot subset columns with a tuple with more than one element. "
   1769         "Use a list instead."
   1770     )
   1771 return super().__getitem__(key)

ValueError: Cannot subset columns with a tuple with more than one element. Use a list instead.

I get the same error if I try confident_cell_velocities correction

# CALCULATE THE CELL VELOCITIES
dyn.tl.cell_velocities(ldata, method='pearson', other_kernels_dict={'transform': ['sqrt']})

# CALCULATE THE CONFIDENCE
dyn.tl.cell_wise_confidence(ldata)

# Correct the cell velocities
dyn.tl.confident_cell_velocities(ldata, group='leiden', lineage_dict={'12': ['9']})

This is the error I get out
calculating gene velocity vectors confidence based on phase portrait location with priors of progenitor/mature cell types: 1000it [00:05, 186.47it/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[46], line 1
----> 1 dyn.tl.confident_cell_velocities(ldata, group='leiden', lineage_dict={'12': ['9']})

File ~/software/miniconda3/envs/dynamo/lib/python3.10/site-packages/dynamo/tools/cell_velocities.py:666, in confident_cell_velocities(adata, group, lineage_dict, ekey, vkey, basis, confidence_threshold, only_transition_genes)
    663 else:
    664     genes = adata.var_names[adata.var.use_for_dynamics]
--> 666 gene_wise_confidence(
    667     adata,
    668     group,
    669     lineage_dict,
    670     genes=genes,
    671     ekey=ekey,
    672     vkey=vkey,
    673 )
    675 adata.var.loc[:, "avg_confidence"] = (
    676     adata.var.loc[:, "avg_prog_confidence"] + adata.var.loc[:, "avg_mature_confidence"]
    677 ) / 2
    678 confident_genes = genes[adata[:, genes].var["avg_confidence"] > confidence_threshold]

File ~/software/miniconda3/envs/dynamo/lib/python3.10/site-packages/dynamo/tools/metric_velocity.py:436, in gene_wise_confidence(adata, group, lineage_dict, genes, ekey, vkey, X_data, V_data, V_threshold)
    431 confidence.astype(dtype={"prog_confidence": "float64", "prog_confidence": "float64"})
    432 adata.var["avg_prog_confidence"], adata.var["avg_mature_confidence"] = (
    433     np.nan,
    434     np.nan,
    435 )
--> 436 avg = confidence.groupby("gene")["prog_confidence", "mature_confidence"].mean()
    437 avg = avg.reset_index().set_index("gene")
    438 adata.var.loc[genes, "avg_prog_confidence"] = avg.loc[genes, "prog_confidence"]

File ~/software/miniconda3/envs/dynamo/lib/python3.10/site-packages/pandas/core/groupby/generic.py:1767, in DataFrameGroupBy.__getitem__(self, key)
   1763 # per GH 23566
   1764 if isinstance(key, tuple) and len(key) > 1:
   1765     # if len == 1, then it becomes a SeriesGroupBy and this is actually
   1766     # valid syntax, so don't raise
-> 1767     raise ValueError(
   1768         "Cannot subset columns with a tuple with more than one element. "
   1769         "Use a list instead."
   1770     )
   1771 return super().__getitem__(key)

ValueError: Cannot subset columns with a tuple with more than one element. Use a list instead.

Thanks for any help you can provide!

Also, this seems like a new issue because I had the code working a few months ago but recently it stopped working.

**Comment by Sichao25** [comment]
Thank you so much for reporting the bug! Based on the error message, I feel like the issue might be related to the pandas/numpy version.  I wonder which versions you are currently running? If you consider downgrading to an older version, it might help resolve the problem. 

Honestly, current requirements on those packages are somewhat outdated. We are committed to making a quick fix on this issue. I will keep you updated about the progress. In the meantime, you might consider trying to downgrade the packages as a temporary workaround.

**Comment by Jordanfink970** [comment]
Thanks for the help! 

My version of pandas was 2.0.3 and numpy was 1.24.4

So I downgraded the version for pandas to 1.5.3 and that seems to fix the issue with the future warning when I run the code: 

calculating gene velocity vectors confidence based on phase portrait location with priors of progenitor/mature cell types: 1000it [00:05, 178.69it/s]
~/software/miniconda3/envs/dynamo/lib/python3.10/site-packages/dynamo/tools/metric_velocity.py:436: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  avg = confidence.groupby("gene")["prog_confidence", "mature_confidence"].mean()

**Comment by Sichao25** [comment]
Yes, it seems that Pandas has deprecated this feature in the latest version. I'm glad this solves your error. I have made a quick fix on the `gene_wise_confidence` in github so it should now work without any warning or error. However, there's a possibility of similar problems in other functions as well. We we're planning to update Pandas in the entire codebase soon. Before that, using an earlier version of Pandas might be a better option.
