### ISSUE TITLE
AttributeError: 'KernelMarkovChain' object has no attribute 'P' in cell_velocities(adata,method='kmc')

### ISSUE THREAD

**Issue by HuangYutong2021** [aristoteleo/dynamo-release#571]
Hi dyanmo,
I have encountered this issue when I use 'kmc' method in runnning the following code:
dyn.tl.cell_velocities(adata,method='kmc')

The version of dynamo I used is 1.3.3
The error message is shown below
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], line 1
----> 1 dyn.tl.cell_velocities(adata,method='kmc')

File ~/anaconda3/envs/scvelo/lib/python3.11/site-packages/dynamo/tools/cell_velocities.py:375, in cell_velocities(adata, ekey, vkey, X, V, X_embedding, transition_matrix, use_mnn, n_pca_components, transition_genes, min_r2, min_alpha, min_gamma, min_delta, basis, neighbor_key_prefix, adj_key, add_transition_key, add_velocity_key, n_neighbors, method, neg_cells_trick, calc_rnd_vel, xy_grid_nums, correct_density, scale, sample_fraction, random_seed, enforce, preserve_len, **kernel_kwargs)
    373     kmc = KernelMarkovChain(P=T)
    374 else:
--> 375     kmc = KernelMarkovChain()
    376 kmc_args = {
    377     "n_recurse_neighbors": 2,
    378     "M_diff": 2,
   (...)
    381     "tol": 1e-7,
    382 }
    383 kmc_args = update_dict(kmc_args, kernel_kwargs)

File ~/anaconda3/envs/scvelo/lib/python3.11/site-packages/dynamo/tools/Markov.py:571, in KernelMarkovChain.__init__(self, P, Idx, n_recurse_neighbors)
    570 def __init__(self, P=None, Idx=None, n_recurse_neighbors=None):
--> 571     super().__init__(P)
    572     self.Kd = None
    573     if n_recurse_neighbors is not None and Idx is not None:

File ~/anaconda3/envs/scvelo/lib/python3.11/site-packages/dynamo/tools/Markov.py:493, in MarkovChain.__init__(self, P, eignum, check_norm, sumto, tol)
    487 def __init__(self, P=None, eignum=None, check_norm=True, sumto=1, tol=1e-3):
    488     """
    489     The elements in the transition matrix P_ij encodes transition probability from j to i, i.e.:
    490             P_ij = P(j -> i)
    491     Consequently, each column of P should sum to `sumto`.
    492     """
--> 493     if check_norm and not self.is_normalized(P, axis=0, sumto=sumto, tol=tol):
    494         if self.is_normalized(P, axis=1, sumto=sumto, tol=tol):
    495             LoggerManager.main_logger.info(
    496                 f"Column sums of the input matrix are not {sumto} but row sums are. "
    497                 "Transposing the transition matrix"
    498             )

File ~/anaconda3/envs/scvelo/lib/python3.11/site-packages/dynamo/tools/Markov.py:558, in MarkovChain.is_normalized(self, P, tol, sumto, axis, ignore_nan)
    542 def is_normalized(self, P=None, tol=1e-3, sumto=1, axis=0, ignore_nan=True):
    543     """
    544     check if the matrix is properly normalized up to `tol`.
    545 
   (...)
    556             1 - check if the matrix is row normalized.
    557     """
--> 558     P = self.P if P is None else P
    559     sumfunc = np.sum if not ignore_nan else np.nansum
    560     return np.all(np.abs(sumfunc(P, axis=axis) - sumto) < tol)

AttributeError: 'KernelMarkovChain' object has no attribute 'P'

I hope you can help. Thanks!

Best wishes!

**Comment by Sichao25** [comment]
Hi, thank you very much for reporting this issue. This seems to be a bug in our KMC input check. I will fix this as soon as possible and keep you updated.
