### ISSUE TITLE
Can anybody offer an alternative link for downloading hematopoisis tutorial hd5a data?

### ISSUE THREAD

**Issue by US36zcai** [aristoteleo/dynamo-release#572]
the original link https://pitt.box.com/v/hematopoiesis-processed does not work for me. 
Any body can share it in Dropbox or Google Drive? Thanks.

**Comment by Sichao25** [comment]
Hi, sorry for that the link does not work. Could you specify which tutorial you are talking about? All tutorials on the read the doc should have a colab link right now. We also have a [public repo](https://github.com/aristoteleo/dynamo-tutorials) for dynamo tutorials. Let me know if these help you.

**Comment by L1angyan** [comment]
In 23th Aug, [the link of zebrafish.h5ad](https://pitt.box.com/shared/static/w81022hta7lymss36i8m5ughppjjagqw.h5ad) does not work.

**Comment by Sichao25** [comment]
I see. We'll make sure to update the link shortly. You can find the Colab link right at the top of any tutorials (for example, [zebrafish tutorial](https://dynamo-release.readthedocs.io/en/latest/notebooks/zebrafish.html), corresponding [Colab](https://colab.research.google.com/github/aristoteleo/dynamo-tutorials/blob/master/zebrafish.ipynb)) on Read the Docs, just look for the little button labeled "Open in Colab".

**Comment by Sichao25** [comment]
Hi, we just updated the sample data url in this [pull request](https://github.com/aristoteleo/dynamo-release/pull/577). Please let me know if any of these URLs don't work.
