### ISSUE TITLE
Got an AttributeError: 'NoneType' object has no attribute '_get_renderer' when trying to plot

### ISSUE THREAD

**Issue by lijxug** [aristoteleo/dynamo-release#574]
- [x] I am sure this issue is not simply a general python programming problem
      (if so, please google the answers).
- [x] I have searched github issues and confirm this issue has not reported previously.
- [x] I have confirmed this bug is not related to dynamo version and it exists on the latest version of dynamo.

---

**If this is a question and not a bug report or enhancement request, please post to our Github Discussions channel at [https://github.com/aristoteleo/dynamo-release/discussions](https://github.com/aristoteleo/dynamo-release/discussions)**

**Describe the bug**
This issue is more like a heads-up, for I already found the solution.
I was following the tutorial *Zebrafish pigementation* and *10 minutes to dynamo*. Some functions, for example, `dyn.pl.phase_portraits`, failed to plot and raised an AttributeError: 'NoneType' object has no attribute '_get_renderer'. It seems that `dynamo-1.3.3` might have a compatibility issue with `matplotlib-3.7x`, because downgrading `matplotlib` to 3.5.3 solved this issue.
The error logs are attached below in case you need it.

Great tool btw. Really appreciate it!

**To Reproduce**

**Traceback**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File /data1/jason/tools/softwares/anaconda3/envs/py3.8_dynamo/lib/python3.8/site-packages/IPython/core/formatters.py:339, in BaseFormatter.__call__(self, obj)
    337     pass
    338 else:
--> 339     return printer(obj)
    340 # Finally look for special method names
    341 method = get_real_method(obj, self.print_method)

File /data1/jason/tools/softwares/anaconda3/envs/py3.8_dynamo/lib/python3.8/site-packages/IPython/core/pylabtools.py:168, in retina_figure(fig, base64, **kwargs)
    159 def retina_figure(fig, base64=False, **kwargs):
    160     """format a figure as a pixel-doubled (retina) PNG
    161 
    162     If `base64` is True, return base64-encoded str instead of raw bytes
   (...)
    166         base64 argument
    167     """
--> 168     pngdata = print_figure(fig, fmt="retina", base64=False, **kwargs)
    169     # Make sure that retina_figure acts just like print_figure and returns
    170     # None when the figure is empty.
    171     if pngdata is None:

File /data1/jason/tools/softwares/anaconda3/envs/py3.8_dynamo/lib/python3.8/site-packages/IPython/core/pylabtools.py:151, in print_figure(fig, fmt, bbox_inches, base64, **kwargs)
    148     from matplotlib.backend_bases import FigureCanvasBase
    149     FigureCanvasBase(fig)
--> 151 fig.canvas.print_figure(bytes_io, **kw)
    152 data = bytes_io.getvalue()
    153 if fmt == 'svg':

File /data1/jason/tools/softwares/anaconda3/envs/py3.8_dynamo/lib/python3.8/site-packages/matplotlib/backend_bases.py:2353, in FigureCanvasBase.print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, pad_inches, bbox_extra_artists, backend, **kwargs)
   2350         bbox_inches = bbox_inches.padded(pad_inches)
   2352     # call adjust_bbox to save only the given area
-> 2353     restore_bbox = _tight_bbox.adjust_bbox(
   2354         self.figure, bbox_inches, self.figure.canvas.fixed_dpi)
   2356     _bbox_inches_restore = (bbox_inches, restore_bbox)
   2357 else:

File /data1/jason/tools/softwares/anaconda3/envs/py3.8_dynamo/lib/python3.8/site-packages/matplotlib/_tight_bbox.py:28, in adjust_bbox(fig, bbox_inches, fixed_dpi)
     26 locator = ax.get_axes_locator()
     27 if locator is not None:
---> 28     ax.apply_aspect(locator(ax, None))
     29 locator_list.append(locator)
     30 current_pos = ax.get_position(original=False).frozen()

File /data1/jason/tools/softwares/anaconda3/envs/py3.8_dynamo/lib/python3.8/site-packages/matplotlib/colorbar.py:156, in _ColorbarAxesLocator.__call__(self, ax, renderer)
    154 def __call__(self, ax, renderer):
    155     if self._orig_locator is not None:
--> 156         pos = self._orig_locator(ax, renderer)
    157     else:
    158         pos = ax.get_position(original=True)

File /data1/jason/tools/softwares/anaconda3/envs/py3.8_dynamo/lib/python3.8/site-packages/mpl_toolkits/axes_grid1/inset_locator.py:73, in AnchoredLocatorBase.__call__(self, ax, renderer)
     71 def __call__(self, ax, renderer):
     72     self.axes = ax
---> 73     bbox = self.get_window_extent(renderer)
     74     px, py = self.get_offset(bbox.width, bbox.height, 0, 0, renderer)
     75     bbox_canvas = Bbox.from_bounds(px, py, bbox.width, bbox.height)

File /data1/jason/tools/softwares/anaconda3/envs/py3.8_dynamo/lib/python3.8/site-packages/matplotlib/offsetbox.py:399, in OffsetBox.get_window_extent(self, renderer)
    396 def get_window_extent(self, renderer=None):
    397     # docstring inherited
    398     if renderer is None:
--> 399         renderer = self.figure._get_renderer()
    400     bbox = self.get_bbox(renderer)
    401     try:  # Some subclasses redefine get_offset to take no args.

AttributeError: 'NoneType' object has no attribute '_get_renderer'

**Expected behavior**

**Screenshots**

**session_info.show():**
-----
anndata             0.9.1
bbknn               1.6.0
dynamo              1.3.3
gseapy              1.0.5
matplotlib          3.7.2
numpy               1.21.5
pandas              1.4.3
scanpy              1.9.3
scvelo              0.2.5
session_info        1.0.0
velocyto            0.17.17
-----
Click to view modules imported as dependencies
PIL                         9.2.0
annoy                       NA
asttokens                   NA
backcall                    0.2.0
beta_ufunc                  NA
binom_ufunc                 NA
bottleneck                  1.3.5
cairo                       1.24.0
certifi                     2022.06.15
charset_normalizer          3.2.0
colorcet                    3.0.0
cvxopt                      1.3.0
cycler                      0.10.0
cython_runtime              NA
dateutil                    2.8.2
debugpy                     1.5.1
decorator                   5.1.1
entrypoints                 0.4
executing                   0.8.3
h5py                        3.6.0
idna                        3.4
igraph                      0.10.5
importlib_resources         NA
ipykernel                   6.9.1
jedi                        0.18.1
joblib                      1.1.0
kiwisolver                  1.4.2
llvmlite                    0.38.0
loompy                      3.0.7
louvain                     0.8.0
matplotlib_inline           NA
mkl                         2.4.0
mpl_toolkits                NA
natsort                     8.4.0
nbinom_ufunc                NA
networkx                    2.8.4
numba                       0.55.1
numdifftools                0.9.40
numexpr                     2.8.3
numpy_groupies              0.9.17
packaging                   21.3
param                       1.12.2
parso                       0.8.3
patsy                       0.5.3
pexpect                     4.8.0
pickleshare                 0.7.5
pkg_resources               NA
prompt_toolkit              3.0.20
ptyprocess                  0.7.0
pure_eval                   0.2.2
pydev_ipython               NA
pydevconsole                NA
pydevd                      2.6.0
pydevd_concurrency_analyser NA
pydevd_file_utils           NA
pydevd_plugins              NA
pydevd_tracing              NA
pygments                    2.11.2
pynndescent                 0.5.10
pyparsing                   3.0.4
pysam                       0.19.1
pytz                        2022.1
requests                    2.31.0
scipy                       1.7.3
seaborn                     0.11.2
setuptools                  61.2.0
setuptools_scm              NA
six                         1.16.0
sklearn                     1.0.2
stack_data                  0.2.0
statsmodels                 0.14.0
texttable                   1.6.7
threadpoolctl               2.2.0
tornado                     6.1
tqdm                        4.65.0
traitlets                   5.1.1
typing_extensions           NA
umap                        0.5.3
urllib3                     2.0.4
wcwidth                     0.2.5
yaml                        6.0.1
zipp                        NA
zmq                         23.2.0
-----
IPython             8.4.0
jupyter_client      7.2.2
jupyter_core        4.10.0
-----
Python 3.8.0 (default, Nov  6 2019, 21:49:08) [GCC 7.3.0]
Linux-5.15.0-76-generic-x86_64-with-glibc2.10
-----
Session information updated at 2023-08-04 12:51

**Additional context**

**Comment by Sichao25** [comment]
Thank you for sharing your experience and solution regarding the compatibility issue. Your heads-up is valuable for others who might encounter a similar problem. I will keep this issue open before we upgrade to matplotlib 3.7.
