### ISSUE TITLE
dyn.pl.kinetic_curves() received wrong `genes` argument

### ISSUE THREAD

**Issue by dyinboisry4u** [aristoteleo/dynamo-release#583]
Hi, Dynamo
In `dynamo.prediction.utils`, `fetch_exprs()` seems return an unsorted `valid_genes` and it will cause `dyn.pl.kinetic_curves()` received wrong `genes` argument.

`set.intersection()` and `pd.Series().isin()` lost the `genes` order
https://github.com/aristoteleo/dynamo-release/blob/153f5b7c84b7b16d36be62bb9547a8a41ff011a8/dynamo/prediction/utils.py#L539
https://github.com/aristoteleo/dynamo-release/blob/153f5b7c84b7b16d36be62bb9547a8a41ff011a8/dynamo/prediction/utils.py#L546

https://github.com/aristoteleo/dynamo-release/blob/153f5b7c84b7b16d36be62bb9547a8a41ff011a8/dynamo/plot/time_series.py#L134-L140

**Comment by dyinboisry4u** [comment]
> Hi, Dynamo In `dynamo.prediction.utils`, `fetch_exprs()` seems return an unsorted `valid_genes` and it will cause `dyn.pl.kinetic_curves()` received wrong `genes` argument.
> 
> `set.intersection()` and `pd.Series().isin()` lost the `genes` order
> 
> https://github.com/aristoteleo/dynamo-release/blob/153f5b7c84b7b16d36be62bb9547a8a41ff011a8/dynamo/prediction/utils.py#L539
> 
> 
> https://github.com/aristoteleo/dynamo-release/blob/153f5b7c84b7b16d36be62bb9547a8a41ff011a8/dynamo/prediction/utils.py#L546
> 
> https://github.com/aristoteleo/dynamo-release/blob/153f5b7c84b7b16d36be62bb9547a8a41ff011a8/dynamo/plot/time_series.py#L134-L140

change Line 539 to
```
# valid_genes = list(set(genes).intersection(fate_genes))
valid_genes = list(sorted(set(genes).intersection(fate_genes), key=genes.index))
```
and Line 546 to
```
# exprs = exprs[np.isfinite(time), :][:, pd.Series(fate_genes).isin(valid_genes)]
exprs = exprs[np.isfinite(time), :][:, pd.Index(fate_genes).get_indexer(valid_genes)]
```
could solve my problem temporary.
by the way, why not allow the `color` for all mode to plot all gene in one fig?
https://github.com/aristoteleo/dynamo-release/blob/153f5b7c84b7b16d36be62bb9547a8a41ff011a8/dynamo/plot/time_series.py#L113
Thanks!

**Comment by Sichao25** [comment]
Hi, thank you very much for identifying this issue. We will fix the bug in `kinetic_curves` soon. 

The `color` is disabled because "lap" and "vector_field" modes use the time information from the trajectory predicted by `fate`, which is different from the size of raw data most of the time. In the current implementation of `kinetic_curves`, we just skip this instead of subsetting the `color` input.  We probably will add this as an enhancement in the future.
