### ISSUE TITLE
save h5ad error [TypeError: Can't implicitly convert non-string objects to strings]

### ISSUE THREAD

**Issue by Jingle0814** [aristoteleo/dynamo-release#622]
- [ ] I am sure this issue is not simply a general python programming problem
      (if so, please google the answers).
- [ ] I have searched github issues and confirm this issue has not reported previously.
- [ ] I have confirmed this bug is not related to dynamo version and it exists on the latest version of dynamo.

--- Hi,

**If this is a question and not a bug report or enhancement request, please post to our Github Discussions channel at [https://github.com/aristoteleo/dynamo-release/discussions](https://github.com/aristoteleo/dynamo-release/discussions)**

**Describe the bug**
      Thank you to your team for developing dynamo, I encountered an error while running dynamo.
   I want to save the processed result of dynamo but could not.
   first, I encountered "TypeError: Can't implicitly convert non-string objects to strings

Above error raised while writing key 'beta' of <class 'h5py._hl.group.Group'> to /" 
And then I change the .var['beta'] to string type: adata_hsc_raw.var['beta'] = adata_hsc_raw.var['beta'].astype(str) .
But it reports the same error with 'gamma'. 
How do I solve this problem? Thanks a lot!

![image](https://github.com/aristoteleo/dynamo-release/assets/111042514/20f13e2f-61fa-4003-a3bf-1a0c39bbe4ef)
**To Reproduce**
The code that produced the bug:

Minimal data may be provided to reproduce the bug
**Traceback**
Post the error message from the Tracebook output:

**Expected behavior**

**Screenshots**

**session_info.show():**
Install session-info via `pip install session-info` and post the output after running session_info.show()

```
import dynamo
import session_info
session_info.show()
```

**Additional context**

**Comment by Sichao25** [comment]
Hi, thanks for reporting this issue. Could you tell me which version of Dynamo you are using? I feel like this may be related to a [recent pull request](https://github.com/aristoteleo/dynamo-release/pull/580). It is not available in the released version yet.

**Comment by Jingle0814** [comment]
@Sichao25 Hi, the version I used is 1.1.0.

**Comment by Jingle0814** [comment]
@Sichao25  hi  thanks to your reply. I try the code: 
  python -m pip install git+https://github.com/aristoteleo/dynamo-release@master 
and it success,
![image](https://github.com/aristoteleo/dynamo-release/assets/111042514/111589ef-ea2c-4cc3-9ea7-7dccb9635c4a)

 but when I try to load dynamo,it turns :
![image](https://github.com/aristoteleo/dynamo-release/assets/111042514/ac0abd30-4cfe-4c86-b24d-768f309b60d0)

**Comment by Sichao25** [comment]
This is a compatibility issue with `Ipython`. It forces the command line to enter the `Ipython` mode after importing the Dynamo. You can use it like a notebook. To solve this problem, you may uninstall `Ipython`, or avoid using the command line.

**Comment by Jingle0814** [comment]
@Sichao25 Thank you very much for your prompt reply! By installing the latest version of dynamo and using notebook to analysis,  I  can save the h5ad files normally with dyn.export_h5ad() function.
Thanks again!
