### ISSUE TITLE
ModuleNotFoundError: No module named 'hnswlib' when running dyn.tl.cell_velocities(adata_hsc_raw)

### ISSUE THREAD

**Issue by Jingle0814** [aristoteleo/dynamo-release#631]
Hi, 
Thank you to your team for developing dynamo, I encountered an error while running dynamo.
I installed the latest version of dynamo(pip install git+https://github.com/aristoteleo/dynamo-release@master) and follow the Typical workflow in dyamo Tutorial:
![image](https://github.com/aristoteleo/dynamo-release/assets/111042514/13caa411-401f-47de-a7e9-d31295f0271d)
When I ran dyn.tl.cell_velocities(adata_hsc_raw) it turns :ModuleNotFoundError: No module named 'hnswlib'

![image](https://github.com/aristoteleo/dynamo-release/assets/111042514/78105967-e961-4800-953a-762138772929)
By the way, previously I ran dynamo with version 1.3.2 it is normal.
How do I solve it?
Thanks a lot!

**Comment by Sichao25** [comment]
Thank you for reporting this issue. This seems to be a bug in the latest version of Dynamo. `hnswlib `is an awesome package we added recently for faster nearest neighbors calculation. I will set it to be an optional dependency to address the issue. Before that, you can just install `hnswlib`.
