### ISSUE TITLE
Is there a function that can generate velocity graph, similar to scv.tl.velocity_graph?

### ISSUE THREAD

**Issue by VivLon** [aristoteleo/dynamo-release#659]
Hi Dynamo team,

Thank you very much for your great work! As in the title, I'm wondering if there's a function similar to scv.tl.velocity_graph in Dynamo?
<img width="876" alt="截屏2024-02-18 上午10 50 55" src="https://github.com/aristoteleo/dynamo-release/assets/88369024/8c489efd-f1d4-476e-9a67-29a1cf534a4e">

**Comment by Sichao25** [comment]
Hi, thanks for using Dynamo. I think `dynamo.tl.cell_velocities()` may be what you are looking for. See more details [here](https://dynamo-release.readthedocs.io/en/latest/_autosummary/dynamo.tl.cell_velocities.html#dynamo.tl.cell_velocities).
