### ISSUE TITLE
Which two layers of dynast are suitable as new and total for scNT-seq？

### ISSUE THREAD

**Issue by mingjianPeng** [aristoteleo/dynamo-release#672]
For the layers of the dynamo scNT-seq tutorial new and total, which two layers from the dynast results are more appropriate to use?
I tried to use adata.X as total, X _ l _ TC or X _ l _ TC _ est as new. It seems that the calculated NTR is quite different. Which two layers should be used to calculate NTR more accurately ?
This is the adata structure I got with dynast：
![7ee62eb235fff04977f6a25c7204976](https://github.com/aristoteleo/dynamo-release/assets/118865890/54861b04-4ec0-42bf-bcea-476ddb55823f)
Looking forward to hearing from you all, thanks!

**Comment by Sichao25** [comment]
Hi, thanks for raising the issue. Could you try with the "labeled" layers and "total" layers?
