### ISSUE TITLE
gene names missing when using dyn.pl.highest_frac_genes 

### ISSUE THREAD

**Issue by chansigit** [aristoteleo/dynamo-release#680]
orient ='h'  is ok but 'v' is problematic.

probably there should be get_xlim and get_xticks https://github.com/aristoteleo/dynamo-release/blob/2e7eb21b22c20e385853fbfb1a32aba745627e3f/dynamo/plot/preprocess.py#L936 and 
https://github.com/aristoteleo/dynamo-release/blob/2e7eb21b22c20e385853fbfb1a32aba745627e3f/dynamo/plot/preprocess.py#L937 
```
dyn.pl.highest_frac_genes(adata, figsize=(6, 4),orient='v')
```

![image](https://github.com/aristoteleo/dynamo-release/assets/18084613/6a27e440-2f66-40ce-a539-b982dacc469d)

**Comment by Sichao25** [comment]
Thank you very much for identifying this bug. We will fix this soon.

**Comment by chansigit** [comment]
fixed
