### ISSUE TITLE
can't get dyn.tl.moments to work

### ISSUE THREAD

**Issue by paupaiz** [aristoteleo/dynamo-release#699]
- [x] I am sure this issue is not simply a general python programming problem
      (if so, please google the answers).
- [x] I have searched github issues and confirm this issue has not reported previously.
- [x] I have confirmed this bug is not related to dynamo version and it exists on the latest version of dynamo.

---

dyn.tl.moments(adata, group="time")

error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/home/paulina/dynamo/dynamo.ipynb Cell 32 line 1
----> <a href='vscode-notebook-cell://westeros./home/paulina/dynamo/dynamo.ipynb#X43sdnNjb2RlLXJlbW90ZQ%3D%3D?line=0'>1</a> dyn.tl.moments(adata, group="time")

File ~/miniconda3/lib/python3.12/site-packages/dynamo/tools/moments.py:167, in moments(adata, X_data, genes, group, conn, use_gaussian_kernel, normalize, use_mnn, layers, n_pca_components, n_neighbors, copy)
    <a href='~/miniconda3/lib/python3.12/site-packages/dynamo/tools/moments.py:164'>164</a>                         cur_conn = normalize_knn_graph(cur_kNN > 0)
    <a href='~/miniconda3/lib/python3.12/site-packages/dynamo/tools/moments.py:166'>166</a>                     cur_cells_ = np.where(cur_cells)[0]
--> <a href='~/miniconda3/lib/python3.12/s

**Comment by Sichao25** [comment]
Hi, thanks for reporting this bug. Could you please share the full traceback error information?
