### ISSUE TITLE
Matplotlib issue

### ISSUE THREAD

**Issue by MagpiePKU** [aristoteleo/dynamo-release#80]
Hi,

We were testing the package on a cluster with python 3.8  and  when it comes to 

dyn.pl.streamline_plot(adata, save_show_or_return='save',save_kwargs={"prefix":'dynamo.streamline',"dpi":1000, "ext":'png'},contour=True)

it pops up "In:" without a way to exit. 

I guess this is an issue with  matplotlib because when we try to set 

dyn.configuration.set_figure_params('dynamo', background='white') 

The same issue pops out again. 

The structure of adata is:

 adata.obs_keys
<bound method AnnData.obs_keys of AnnData object with n_obs × n_vars = 7525 × 60662
    obs: 'TotalUMIs', 'orig_ident', 'batch', 'nGenes', 'nCounts', 'pMito', 'use_for_pca', 'spliced_Size_Factor', 'initial_spliced_cell_size', 'unspliced_Size_Factor', 'initial_unspliced_cell_size', 'Size_Factor', 'initial_cell_size', 'ntr', 'cell_cycle_phase', 'jaccard_velocity_confidence', 'umap_ddhodge_sampled', 'umap_ddhodge_div', 'umap_potential'
    var: 'Accession', 'AccessionVersion', 'Aliases', 'CcdsID', 'Chromosome', 'ChromosomeEnd', 'ChromosomeStart', 'CosmicID', 'DnaBindingDomain', 'FullName', 'GeneType', 'HgncID', 'IsTF', 'Location', 'LocationSortable', 'LocusGroup', 'LocusType', 'MgdID', 'MirBaseID', 'OmimID', 'PubmedID', 'RefseqID', 'RgdID', 'UcscID', 'UniprotID', 'VegaID', 'pass_basic_filter', 'score', 'log_cv', 'log_m', 'use_for_pca', 'ntr', 'beta', 'gamma', 'half_life', 'alpha_b', 'alpha_r2', 'gamma_b', 'gamma_r2', 'gamma_logLL', 'delta_b', 'delta_r2', 'uu0', 'ul0', 'su0', 'sl0', 'U0', 'S0', 'total0', 'use_for_dynamics', 'use_for_transition'
    uns: 'velocyto_SVR', 'pp_norm_method', 'PCs', 'explained_variance_ratio_', 'pca_fit', 'feature_selection', 'dynamics', 'neighbors', 'umap_fit', 'grid_velocity_umap', 'VecFld_umap', 'VecFld'
    obsm: 'X_pca', 'X', 'cell_cycle_scores', 'X_umap', 'velocity_umap', 'velocity_umap_SparseVFC', 'X_umap_SparseVFC'
    layers: 'matrix', 'spliced', 'unspliced', 'X_spliced', 'X_unspliced', 'M_u', 'M_uu', 'M_s', 'M_us', 'M_ss', 'velocity_S'
    obsp: 'moments_con', 'connectivities', 'distances', 'pearson_transition_matrix'>

We were using it like:

import dynamo as dyn
import anndata
import pandas as pd
import numpy as np
import matplotlib 
import matplotlib.pyplot as plt

**Comment by Xiaojieqiu** [comment]
hi @MagpiePKU thanks for using our tool! indeed it looks to me a matplotlib issue, I tried your exact code and found I am able to save the figure fine (no surprise~): 
```
dyn.configuration.set_figure_params('dynamo', background='white')
dyn.pl.streamline_plot(adata, save_show_or_return='save',save_kwargs={"prefix":'dynamo.streamline',"dpi":1000, "ext":'png'},contour=True)
```
I would like to ask for two things so that I can provide more informative suggestions for you: 

1. Can you plot your figure in jupter notebooks fine?
2. And also could you please which version of matplotlib are you using? I am using `3.3.1`.  

Btw, there is no contour argument in dynamo and I guess you are referring to `frontier` (see the third cheatsheet from matplotlib: https://github.com/matplotlib/cheatsheets). In addition, setting `dpi` to 300 will be fine (which is the default resolution required for major journals). 1000 is just not necessary. To save figures for manuscripts, I generally use `set_pub_style` function. so it will be something like: 

```
dyn.configuration.set_pub_style()
dyn.pl.streamline_plot(adata, color=['cell_type'], basis='umap_ori', show_legend='on data', 
                        show_arrowed_spines=False, save_show_or_return='save',
                        pointsize=0.4, 
                       streamline_kwargs = {
                             "linewidth": None,
                             "cmap": None,
                             "norm": None,
                             "arrowsize": 1,
                             "arrowstyle": "fancy",
                             "minlength": 0.1,
                             "transform": None,
                             "start_points": None,
                             "maxlength": 4.0,
                             "integration_direction": "both",
                             "zorder": 3,
                         }, 
                       save_kwargs={'prefix': 'tmp', 'ext': 'png',
                                     "bbox_inches": None}, 
                        figsize=(4, 3))
```

**Comment by Xiaojieqiu** [comment]
sorry, I want to revert what I mentioned yesterday: we do have the `contour` argument in `dyn.tl.scatters` which :

1 uses alpha-hull convex to calculate a `frontier` or `outline` of the dataset; 
2 use `tricontourf` to plot contour for non-gridded data. 

In general, I find the contour produced from this approach is not visually appealing than the `frontier` created when setting `frontier=True` so using `frontier` is recommended.  sorry for this mistake

**Comment by MagpiePKU** [comment]
Thank you very much. 

We have now tested it in Jupyter notbooks and it worked just fine. Also it is working on script mode. So I guess we would use the notebook for interactive exploratory analysis for now. Thank you again for the support. 

PS. We would read your preprint to understand better the novel parameters (curl, divergence etc) but do you have a general recommendation for background reference?

**Comment by Xiaojieqiu** [comment]
glad to hear that you figured it out. For curl, divergence, and other vector calculus, please refer to the zebrafish tutorial [here](https://dynamo-release.readthedocs.io/en/latest/zebrafish.html#Beyond-RNA-velocity). The documentation for those relevant functions is also a good place to start. For full details, please wait for our final publication!
