### ISSUE TITLE
module 'dynamo.tl' has no attribute 'estimation'

### ISSUE THREAD

**Issue by pigraul** [aristoteleo/dynamo-release#85]
Hi @Xiaojieqiu ,
I followed the dynamo-notebooks/NASC_seq/NASC_seq_analysis.ipynb ( In [3] ).

The command "dyn.tl.estimation"  returned "module 'dynamo.tl' has no attribute 'estimation'"
Also "dyn.tl.velocity" returned "module 'dynamo.tl' has no attribute 'velocity'"

Did I install dynamo unsucseccfully or missed some commands?

Thanks,
Raulee

**Comment by Xiaojieqiu** [comment]
Hey @pigraul  thanks for using dynamo. Please note that tutorials in `dynamo-notebooks` repo are outdated. Please check out our more updated tutorial repos [here](https://github.com/aristoteleo/dynamo-tutorials). Also I suggest you go through our readthedocs [pages](https://dynamo-release.readthedocs.io/) to help you get started: this includes the Introduction, 10 minutes to dynamo, API, tutorials on how to analyzing conventional scRNA-seq and tutorials on analyzing both `scNT-seq, scEU-seq` datasets. (those are also in the updated tutorial repo)

Let me know how it goes, and I am happy to ask any other questions!
