### ISSUE TITLE
Adding the dataset for scNT-seq to sample_data

### ISSUE THREAD

**Issue by 2064240P** [aristoteleo/dynamo-release#88]
I was going through the dynamo tutorials and found it very helpful to play with the zebrafish dataset. Would it be possible to add the scNT-seq already preprocessed data to the sample_data in dynamo?

Thanks

**Comment by Xiaojieqiu** [comment]
certainly, please wait for a few days as my schedule is a little hectic now but I am promised to upload it before the end of next week the latest.

**Comment by 2064240P** [comment]
Great! Thank you very much!

**Comment by 2064240P** [comment]
Any progress on this?

**Comment by Xiaojieqiu** [comment]
sorry for the delay. but I just finished my duties. Will upload the data today. See also the following information that may be of interests to you: 

we finally developed the full-fledged theory and proved the broad utility of dynamo. It was definitely the most intellectually changeling project I had In case you are interested, please see the  the completely rewritten biorxiv version here: https://www.biorxiv.org/content/10.1101/696724v2 .

 For a 3 minute digest of the manuscript, you can see our tweetorial below (welcome retweet): 
https://twitter.com/Xiaojie_Qiu/status/1359183325198512132

(Basically dynamo reconciles intrinsic splicing and labeling kinetics to estimate absolute RNA velocities, reconstructs continuous velocity vector fields that predict future cell fates, and finally employs differential geometry analyses to elucidate 
the underlying regulatory networks.)

Welcome any other comments or suggestions!

**Comment by Xiaojieqiu** [comment]
Hi @2064240P, 

The `scNT_seq.h5ad` is here: 
the https://www.dropbox.com/s/zyl282ep88ktvo2/scNT_seq.h5ad?dl=0

While the `neuron_splicing_4_11.h5ad` is here: 
https://www.dropbox.com/s/zyl282ep88ktvo2/scNT_seq.h5ad?dl=0

I will update the tutorial and our package to make those data directly downloadable from dynamo very soon. 

Let me know if you have any further questions.

**Comment by 2064240P** [comment]
Great! Thanks so much!

**Comment by Xiaojieqiu** [comment]
my pleasure. let me know if any other questions come up. Also I recommend you to re-read the fully rewritten preprint (https://www.biorxiv.org/content/10.1101/696724v2 ). It introduces quite many amazing analyses we can do with dynamo (those relavant tutorials will be released soon also).

**Comment by mkyriak** [comment]
> https://www.dropbox.com/s/zyl282ep88ktvo2/scNT_seq.h5ad?dl=0

Hello, I was going through the dynamo tutorials and I realized that the provided dropbox links for the labeling and the splicing information of the scNT-seq data are the same link. Could you please provide the links once again?

Thank you in advance!

**Comment by Spartanzhao** [comment]
I am wondering could you provide me a dropbox link of zebra fish h5ad file? I can't open the h5ad through the command adata = dyn.sample_data.zebrafish(). I want to take a try to directly read this h5ad。

**Comment by Spartanzhao** [comment]
The scNT_seq.h5ad is here:
the https://www.dropbox.com/s/zyl282ep88ktvo2/scNT_seq.h5ad?dl=0

While the neuron_splicing_4_11.h5ad is here:
https://www.dropbox.com/s/zyl282ep88ktvo2/scNT_seq.h5ad?dl=0
These two links are exactly the same link! can you sent the links again?

**Comment by Spartanzhao** [comment]
until now , none of your tutorial is working, I can't get result you showed on your tutorial, there are too many bugs and problems, I had lunched issued for several month. Can you update your tutorial and provide all the test data that we need in the tutorial?

**Comment by Xiaojieqiu** [comment]
> I am wondering could you provide me a dropbox link of zebra fish h5ad file? I can't open the h5ad through the command adata = dyn.sample_data.zebrafish(). I want to take a try to directly read this h5ad。

Dear @Spartanzhao I am sorry for the late reply, unfortunately I want to be honest that I am unfortunately very busy these days as I currently have at least 4 papers needs to take care (3 of them will be needed to help others to graduate), a few grants needs to write and the faculty job interviews I am preparing now. 

Please don't get disappointed though, I are here to  help as much as I can if I get a chance. 

Regarding this error, if you see something like the following: 
```adata = dyn.sample_data.zebrafish()
|-----> Downloading data to ./data/zebrafish.h5ad
adata
Out[4]: 
AnnData object with n_obs × n_vars = 4181 × 16940
    obs: 'split_id', 'sample', 'Size_Factor', 'condition', 'Cluster', 'Cell_type', 'umap_1', 'umap_2', 'batch'
    layers: 'spliced', 'unspliced'```
It means you have downaloaded the data. So if you see this, you should be able to move forward with your analyses. Please let me know what is your exact issue is

**Comment by Xiaojieqiu** [comment]
> The scNT_seq.h5ad is here: the https://www.dropbox.com/s/zyl282ep88ktvo2/scNT_seq.h5ad?dl=0
> 
> While the neuron_splicing_4_11.h5ad is here: https://www.dropbox.com/s/zyl282ep88ktvo2/scNT_seq.h5ad?dl=0 These two links are exactly the same link! can you sent the links again?

Please see my updated links above. 

Also you can  use `dyn.sample_data.scNT_seq_neuron_splicing()`and `dyn.sample_data.scNT_seq_neuron_labeling()` to download the respective datasets.

**Comment by Xiaojieqiu** [comment]
> until now , none of your tutorial is working, I can't get result you showed on your tutorial, there are too many bugs and problems, I had lunched issued for several month. Can you update your tutorial and provide all the test data that we need in the tutorial?

Please see all the sample datasets here and please check my above answers: 
https://github.com/aristoteleo/dynamo-release/blob/master/dynamo/sample_data.py

Again, I apologize for the delay in reply. But I will try to answer any your further questions when I got a chance
