### ISSUE TITLE
An alternative way to show gene expression dynamics over time.

### ISSUE THREAD

**Issue by sunon77** [aristoteleo/dynamo-release#89]
Thanks for developing this powerful software to analyze the dynamics of cells from single-cell data. 

We recently used dynamo to analyze the CART cell clone dynamics from single-cell time course data. It helped us a lot to elucidate accelerated and diverted cell differentiation dynamics. However, there are several issues that we could like to discuss to enable more people to use this powerful tool for more convenient analysis.

1) An alternative way to show gene expression dynamics over time
Currently, we have gene expression dynamics over time like this:
![image](https://user-images.githubusercontent.com/12102715/95001382-75d49a00-0597-11eb-824b-beb5798626af.png)

Could we also offer an alternative way to show gene expression dynamics over time as a heatmap
![image](https://user-images.githubusercontent.com/12102715/95001391-94d32c00-0597-11eb-9c8d-d0735212715e.png)

Thus, we can compare the multiple genes in a uniform and formalized way.

**Comment by Xiaojieqiu** [comment]
We have a function in dynamo to plot kinetic heatmaps over pseudotime, basically you need to use something like the following: 

```
dyn.ext.ddhodge(adata, basis='pca') 
dyn.pl.kinetic_heatmap(adata, adata.var_names, mode='pseudotime', tkey='pca_ddhodge_potential', save_show_or_return='save',
                       save_kwargs={'prefix': './figures/Fig4_kinetic_heatmap', 'ext': 'pdf',
                                     "bbox_inches": None},
                        figsize=(1, 1))
```

Note: **you need to have vector field reconstructed before the above snippet.**

**Comment by stanveer-97** [comment]
Is there a way to get the gene expression change with time in  tabular form?

**Comment by 117999** [comment]
Hi, Dr Qiu,
I am also curious about the kinetic heatmap. how can we visualize the gene ID and the scale bar of intensity and cell identity with the argument in the `dyn.pl.kinetic_heatmap`

**Comment by Xiaojieqiu** [comment]
this is documented in the `kinetic_heatmap` function please run check via `dyn.pl.kinetic_heatmap`
