### ISSUE TITLE
Failed to install package, because of statsmodels

### ISSUE THREAD

**Issue by ChengxiangQiu** [aristoteleo/dynamo-release#9]
Hi,
Thanks for providing this exciting single-cell analysis tool. I have some problems while installing dynamo. Now I am using Python 3.7.3 with miniconda. I am sure I have installed the package statsmodels (version 0.10.1), which can be loaded successfully in the python session. But I always got the error message while installing the dynamo " import statsmodels.api as sm
    ModuleNotFoundError: No module named 'statsmodels'". Anything could you suggest? For example, is there any specific version of statsmodels needed?
Thank you!!

**Comment by Xiaojieqiu** [comment]
thanks for asking and using dynamo! dynamo only requires statsmodels to be 0.9.0 or higher. 
In python3.6.8 or python3.6.9, I am able to install dynamo successfully with statsmodels 0.9.0 or statsmodels 0.10.1, respectively (No other combination is tested).

Maybe the pip you used is for a different python version? Can you please try to install dynamo in its main folder (where setup.py located) using something like ``` python3.7.3 setup.py install --user```?

**Comment by ChengxiangQiu** [comment]
I tried "python setup.py install --user" in the folder and it works, thank you!

**Comment by Xiaojieqiu** [comment]
wonderful
