### ISSUE TITLE
An alternative way to show gene expression dynamics over time

### ISSUE THREAD

**Issue by sunon77** [aristoteleo/dynamo-release#90]
Thanks for developing this powerful software to analyze the dynamics of cells from single-cell data. 

We recently used dynamo to analyze the CART cell clone dynamics from single-cell time course data. It helped us a lot to elucidate accelerated and diverted cell differentiation dynamics. However, there are several issues that we could like to discuss to enable more people to use this powerful tool for more convenient analysis.

1) An alternative way to show gene expression dynamics over time
Currently, we have gene expression dynamics over time like this:
![image](https://user-images.githubusercontent.com/12102715/95001382-75d49a00-0597-11eb-824b-beb5798626af.png)

Could we also offer an alternative way to show gene expression dynamics over time as a heatmap
![image](https://user-images.githubusercontent.com/12102715/95001391-94d32c00-0597-11eb-9c8d-d0735212715e.png)

Thus, we can compare the multiple genes in a uniform and formalized way.

**Comment by Xiaojieqiu** [comment]
looks like this issue is a duplication. I will close this and discuss from the other one
