### ISSUE TITLE
How to visualize development trajectory with deeper channel?

### ISSUE THREAD

**Issue by sunon77** [aristoteleo/dynamo-release#91]
Thanks for developing this powerful software to analyze the dynamics of cells from single-cell data. 

We recently used dynamo to analyze the CART cell clone dynamics from single-cell time course data. It helped us a lot to elucidate accelerated and diverted cell differentiation dynamics. However, there are several issues that we could like to discuss to enable more people to use this powerful tool for more convenient analysis.

1) How to visualize development trajectory with a deeper channel?

From our experiment data, we know that one sample of cells differentiate 3 days earlier and cells are more committed. It seems that the differentiation channel is deeper and steeper. Could we have a better way to visualize and distinguish these two cases?

![image](https://user-images.githubusercontent.com/12102715/95001547-f778f780-0598-11eb-8467-846e859cda79.png)

2) Usually top 30 genes will determine the RNA velocity. Could we identify the genes which control the lineage decision and contribute to certain cell lineage most? It is a little bit like the toggle switch genes near the branching point which are identified by Monocle.

**Comment by Xiaojieqiu** [comment]
@sunon77 for 1, you can visualize the cells by coloring the ddhoge based pseudotime (dyn.ext.hodge(adata))

for 2, please check our new tutorial on how to do ranking for different differential geometry quantities: 
https://dynamo-release.readthedocs.io/en/latest/Differential_geometry.html
