### ISSUE TITLE
Is it possible to choose a subset of cells to do a streamline plot?

### ISSUE THREAD

**Issue by sunon77** [aristoteleo/dynamo-release#92]
Thanks for developing this powerful software to analyze the dynamics of cells from single-cell data. 

We recently used dynamo to analyze the CART cell clone dynamics from single-cell time course data. It helped us a lot to elucidate accelerated and diverted cell differentiation dynamics. However, there are several issues that we could like to discuss to enable more people to use this powerful tool for more convenient analysis.

1) Currently streamline plot the whole cell population, is it possible to choose a subset of cells to do a streamline plot? For example, we have several clones of cells from our lineage tracing, could we plot a streamline plot from each clone?
![image](https://user-images.githubusercontent.com/12102715/95001846-ea113c80-059b-11eb-8b78-2e3d67e8f70b.png)

2) Could we plot a transition-growth network for each clone as well?
![image](https://user-images.githubusercontent.com/12102715/95001848-f1d0e100-059b-11eb-866e-d2261f1105b2.png)

**Comment by Xiaojieqiu** [comment]
Hi Joseph, to plot streamlines for subset of cells, you just need to subset adata object when you make the streamline plot. Something like this will work: 
`dyn.pl.streamline_plot(adata[adata.obs.clone == 'clone_0']], color='cell_type'])`

Hope this helps! 

(Your second question will be answered in the issue you wrote. )
