### ISSUE TITLE
How much do landscape-derived attractor and transition pathway overlap with cell cluster and pseudo-time?

### ISSUE THREAD

**Issue by sunon77** [aristoteleo/dynamo-release#93]
Thanks for developing this powerful software to analyze the dynamics of cells from single-cell data. 

We recently used dynamo to analyze the CART cell clone dynamics from single-cell time course data. It helped us a lot to elucidate accelerated and diverted cell differentiation dynamics. However, there are several issues that we could like to discuss to enable more people to use this powerful tool for more convenient analysis.

It is cool to derive the pointed attractors and saddle points from RNA velocity data. From a theoretical point of view, pointed attractors should correspond to stable cell types and transition trajectories should correspond to single-cell transition manifold, which is usually inferred by pseudo-time.

How much do landscape-derived attractor and transition trajectories overlap with cell clusters and pseudo-time?

![image](https://user-images.githubusercontent.com/12102715/95001697-74f13780-059a-11eb-8a82-073f52140fd5.png)

**Comment by Xiaojieqiu** [comment]
@sunon77 very good question.  Under dynamo's perspective, we believe the separatrices of an attractor define the boundaries of cell states. But of course, the calculation of separatrices in high dimensional space is very challenging. An approximate approach is to probably just take the transition matrix that can be constructed based RNA velocity estimates to perform cell clustering. 

Regarding pseudotime, I think given a vector field function, you can also get the pseudotime. please take a look at the dyn.ext.ddhodge function
