### ISSUE TITLE
Could we output the dynamics as a network with growth and transition rates?

### ISSUE THREAD

**Issue by sunon77** [aristoteleo/dynamo-release#94]
Thanks for developing this powerful software to analyze the dynamics of cells from single-cell data. 

We recently used dynamo to analyze the CART cell clone dynamics from single-cell time course data. It helped us a lot to elucidate accelerated and diverted cell differentiation dynamics. However, there are several issues that we could like to discuss to enable more people to use this powerful tool for more convenient analysis.

Currently, the RNA velocity output is mostly a visualization. When we want to quantify the dynamics with some numbers, could we output the dynamics as a network with growth and transition rates? Such as:

![image](https://user-images.githubusercontent.com/12102715/95001799-58a1ca80-059b-11eb-8aa1-2a77273de9a7.png)

**Comment by Xiaojieqiu** [comment]
@sunon77 please see the dyn.pd.state_graph function
