### ISSUE TITLE
If we want to plot some specific gene’s RNA velocity, where can we find it ?

### ISSUE THREAD

**Issue by sunon77** [aristoteleo/dynamo-release#95]
Usually, RNA velocity in 2D projection is decided by the top 30 ~ 50 genes.

However, since we are especially interested in certain predefined genes. If we want to plot these specific gene’s RNA velocity, where can we find it and how to implement it in the current APIs?

**Comment by Xiaojieqiu** [comment]
Thanks for asking. However, I am afraid your description of the question is kinda sloppy...  

First of all, you can never plot the velocities of more than two genes (or three genes if doing it in 3D) with the cell-wise, grid, streamline or integral convolution lines plots. In addition, by default, we are projecting the velocity of transition genes (genes with good fitting, etc) to 2D for plotting. 

So if your question is about plotting velocity of any two genes, as I mentioned in our zebrafish tutorial: 

`Note that, if you pass x='gene_a', y='gene_b' to cell_wise_vectors, grid_vectors or streamline_plot, you can visualize the raw gene-pair velocity flows. gene_a and gene_b need to have velocity calculated (or use_for_dynamics in .var for those genes are True)
`

If your question is about using different sets of genes as input to project their velocities down to 2 dimensions, you need to read the docs for `dyn.tl.cell_velocities`. And basically, you will use something like the following
```
dyn.tl.cell_velocities(adata, transition_genes=list_of_your_genes_of_interests, enforce=True)
dyn.pl.stremline_plot(adata, color=colors, ncols=3)
```
