### ISSUE TITLE
About data in scNT-seq

### ISSUE THREAD

**Issue by houruiyan** [aristoteleo/dynamo-release#97]
Dear Dr Qiu,

Thank you very much for this great package. I found you use tow data sets in scNT-seq. One is splicing dataset. Another is labeling dataset. Splicing dataset can get the spliced and unspliced count. Labeling dataset can get new counts and total counts. I knew the labeling dataset is the result of scNT-seq. But I really want to know how can I get the splicing dataset. Is it another experiment?

**Comment by ChristopherLeeZG** [comment]
Dear Xiao:
I don't know what abbreviation (or means) about those layers from scNT seq database:

> layers: 'M_n', 'M_nn', 'M_t', 'M_tn', 'M_tt', 'X_new', 'X_total', 'velocity_alpha_minus_gamma_s'
Could you tell to me?
Thanks.

**Comment by ChristopherLeeZG** [comment]
Dear Xiao:
I don't know what abbreviation (or means) about those layers from scNT seq database:
`layers: 'M_n', 'M_nn', 'M_t', 'M_tn', 'M_tt', 'X_new', 'X_total', 'velocity_alpha_minus_gamma_s'`

Could you tell to me?
Thanks.

>

**Comment by Xiaojieqiu** [comment]
@ChristopherLeeZG 
thanks for your question. It looks like you are looking at our human hematopoesis dataset (please don't confused with the data from the original scNT-seq paper).
M_n: first moment of new RNA  
M_nn: second moment of new RNA  
M_t: first moment of total RNA
M_tn: mixed moment of total and new RNA  
X_new: normalized new RNA  
X_total: normalized total RNA  
velocity_alpha_minus_gamma_s: this is one type of our total RNA velocity: alpha - gamma S. 

you will find the definitation to all the above terms from the cell paper here to : [dynamo](https://www.sciencedirect.com/science/article/pii/S0092867421015774#ack0010)

**Comment by ChristopherLeeZG** [comment]
您好，已经收到您的信件。我会及时阅读并回复。谢谢。                                                                       Lee.ZG

**Comment by ChristopherLeeZG** [comment]
thanks a lot for reply!

**Comment by ChristopherLeeZG** [comment]
您好，已经收到您的信件。我会及时阅读并回复。谢谢。                                                                       Lee.ZG

**Comment by ChristopherLeeZG** [comment]
您好，已经收到您的信件。我会及时阅读并回复。谢谢。                                                                       Lee.ZG
