### ISSUE TITLE
Possible bug in find_fixed_points() (+ tqdm progress bars)

### ISSUE THREAD

**Issue by rorymaizels** [aristoteleo/dynamo-release#99]
Hey,

I've encounter a strange error a couple times when running dyn.vf.VectorField(). It doesn't happen every time, and is subject to the particular data and dimensionality of the vector field being learnt. As such, it is pretty hard for me to give thoroughly reproducible code, but it seems to me that the issue happens only in certain contexts depending on the output of remove_redundant_points() within find_fixed_points().

Sometime when I run  something like:
`vf = dyn.vf.VectorField(adata, basis='pca', return_vf_object=True, pot_curl_div=True, dims=[0,1])`

I get the following error message:
```
s)
    207             data_2d = self.adata.copy()
    208             print('Low-dimension:')
--> 209             vf_2d = dyn.vf.VectorField(data_2d, basis=self.basis, return_vf_object=True, pot_curl_div=True, dims=[0,1])
    210             self.vf_dict['{0}_2D'.format(name)] = (data_2d, vf_2d)
    211             if plot:

~/.local/lib/python3.8/site-packages/dynamo_release-0.95.2-py3.8.egg/dynamo/vectorfield/topography.py in VectorField(adata, basis, layer, dims, genes, normalize, grid_velocity, grid_num, velocity_key, method, return_vf_object, map_topography, pot_curl_div, cores, **kwargs)
    701             warnings.simplefilter("ignore")
    702 
--> 703             adata = topography(
    704                 adata, basis=basis, X=X, layer=layer, dims=[0, 1], VecFld=vf_dict['VecFld'], **tp_kwargs
    705             )

~/.local/lib/python3.8/site-packages/dynamo_release-0.95.2-py3.8.egg/dynamo/vectorfield/topography.py in topography(adata, basis, layer, X, dims, n, VecFld)
    499     vecfld.find_fixed_points_by_sampling(n, xlim, ylim)
    500     if vecfld.get_num_fixed_points() > 0:
--> 501         vecfld.compute_nullclines(xlim, ylim, find_new_fixed_points=True)
    502     # sep = compute_separatrices(vecfld.Xss.get_X(), vecfld.Xss.get_J(), vecfld.func, xlim, ylim)
    503     #

~/.local/lib/python3.8/site-packages/dynamo_release-0.95.2-py3.8.egg/dynamo/vectorfield/topography.py in compute_nullclines(self, x_range, y_range, find_new_fixed_points, tol_redundant)
    439         if find_new_fixed_points:
    440             sample_interval = ds * 10
--> 441             X, J = find_fixed_points_nullcline(
    442                 self.func, self.NCx, self.NCy, sample_interval, tol_redundant, True
    443             )

~/.local/lib/python3.8/site-packages/dynamo_release-0.95.2-py3.8.egg/dynamo/vectorfield/topography.py in find_fixed_points_nullcline(func, NCx, NCy, sample_interval, tol_redundant, full_output)
    227     int_P = np.array(int_P)
    228     if full_output:
--> 229         P, J, _ = find_fixed_points(int_P, func, tol_redundant, full_output=True)
    230         return P, J
    231     else:

~/.local/lib/python3.8/site-packages/dynamo_release-0.95.2-py3.8.egg/dynamo/vectorfield/topography.py in find_fixed_points(X0, func_vf, tol_redundant, full_output)
     61         if full_output:
     62             X, discard = remove_redundant_points(X, tol_redundant, output_discard=True)
---> 63             J = J[~discard]
     64             fval = fval[~discard]
     65         else:

IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 1
```

It seems like an error with numpy dimensions but I'm not sure exactly what's causing it. Sorry I couldn't be more helpful this time. Let me know if you know what's causing this.

Also, since I'm posting I thought I'd drop an additional little request: I see that with fate prediction and vector field learning, tqdm progress bars are used. This verbosity is actually a bit undesirable for my usage case, so it would be excellent to have a user argument to disable progress bars/verbosity.

Thanks again for this fantastic package, I've really enjoyed using it so far. 

Cheers,
Rory

**Comment by Xiaojieqiu** [comment]
Hi Rory, 

Thanks again for your very in-depth question. I am glad you enjoyed using it! This bug seems a little complicated and involved and may be difficult to debug without some reproducible data. Especially I never encounter such an issue as I tested it across more than 15 different datasets. 

Is it possible for you to share an example dataset that reproduces the error? Feel free to email via xqiu@wi.mit.edu or send me a direct slack message on our dynamo slack channel here: 
https://join.slack.com/t/dynamo-discussionhq/shared_invite/zt-itnzjdxs-PV~C3Hr9uOArHZcmv622Kg

**Comment by Xiaojieqiu** [comment]
Regarding the progress bar, certainly, I can make it optional

**Comment by rorymaizels** [comment]
Hi Xiaojie,

It is indeed an odd issue. I've struggled to even get an example case where the error consistently happens so I can send the dataset over, which makes me think it might have been a particular issue in the code I had written, rather than a bug in dynamo. I've joined the slack channel so if I get any more information I'll let you know, but the issue isn't affecting me at the moment!

Cheers,
Rory

**Comment by Xiaojieqiu** [comment]
Hi Rory, please check the slack channel, I have sent you a file that implements an alternative method to map the topology of the vector field. It may alleviate the issue you are having and welcome to test it and let me know how it goes. we will update our topology calculation later.
